>fig|6666666.155597.peg.1331|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------MSGSINKDPRDVIIAPVVSEKSYGLIDEGKYTFL
VDPRSNKSEIKQAVERIFNVDVASVNTLNRSGKRRRTRFGWGQRKSTKRAIVTLKDGTID
IFGGPLA
>fig|6666666.235531.peg.1754|430840
MKTVQVDLPAELFDVQSNVPLMHQVVVAQLAAARQGTHKTKRRGEVSGAGRKPFKQKGTG
RARQGSIRAPHMTGGGVVHGPTPRDYSQRTPKKMKAAALRGALSDRARNGRVHVIEALVS
GTTPSTKAAKAGLASLNTGRKNVLLVIDRADDVAALSARNLPAVHTLYRRPAEHLRRARL
RRRRVHPGGLRGVRGPGFRRQEGGCPVSGSINKDPRDVIIAPVVSEKSYGLIDEGKYTFL
VDPRSNKSEIKQAVERIFNVDVASVNTLNRSGKRRRTRFGWGQRKSTKRAIVTLKDGTID
IFGGPLA
>fig|6666666.68540.peg.1704|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|2.1418.peg.462|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|2.1421.peg.1672|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|2.1425.peg.1340|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|33013.175.peg.1780|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|33013.181.peg.483|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|6666666.374469.peg.1779|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSATQKDPRDIIIAPVVSEKSYGLIDQGKYTFI
VDPRSNKTEIKLAIEKIFGVQVASVNTLNKQGKTRRTKFGMGKRKDTKRAIVSLKSGSID
IF-TTVG
>fig|2.1422.peg.1346|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MTAVNKDPRDIILKPVVSEKSYSLIDEGKYTFL
VDPRSSKTEIKLAIEKIFGVKVASVNTINRVGKARRTRFGIGKRKDTKRAIVSLKSGTID
IF-TSVG
