>fig|2.1422.peg.3181|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MIDIQRAGLAPHYVPYLDGWAHQRRVHADVVARERGDTLLLLEHEA
VYTAGKRTEAHERPDDGTPVVDVDRGGKITWHGPGQLVGYPIVRLPEPIDVVAHVRRLEG
LLIDALSVHGVDGFRVEGRSGVWVRRPLGVD-------KVAAIGVRVERGVTMHGFAVNC
DNTLAGFRHIVPCGISDAGVTTVSEIVGADVSPADLVDAIERVFR----------AEYAA
VAA------
>fig|6666666.155597.peg.1967|300756
MHHPLAVQARESLGDRDEHGDGLPRAQGSDPLHHVLQRAGRAVLGEDPEAPVRLHHAEHA
QQMGMRDPSGLRLRRQRIRRRAGTGHLQGGPDAPTVLDEPDLRLGARAEQPDGFPARGAR
RSRARLRRPLRFGLRPAADASGRAAVRLVPVPHRSPLSAAPSVPAQGAACPRASRRLSTG
PGPRTTVDVMPETPLPPLRVLGLAPDLVDYHAAWDAQRALHADVVAGRSDGEFLLLEHEA
VYTAGRRTEDAERPTDGAPVVDVDRGGKITWHGPGQLVGYPVVRLRDRAHVKDYVWFLEE
LLIRTAAEFGVTAVRVDGRAGIWVLADRDDDGAARPDRKVGAIGLSIHDGVSMHGFALNC
SNSLAPYEGIIACGITDAATTTLSVETGRTITPADVVPVLTRH----LDELG---PAYIA
VTPTEGIPA
>fig|6666666.235531.peg.1505|430840
MHHPLAVQARESLGDRDEHGDGLPRAQGSDPLHHVLQRAGRAVLGEDPEAPVRLHHAEHA
QQMGMRAPSGRRLRRQRIRPRAGTGHLQGGPDAPTVLDEPDLRLGARAEQPDGFPARGAR
RSRARLRPPLRFGLRPAADASGRAAVRLVPVPHRSPLSAAPSVPAQGGACPRASRRLSTG
PGPRTTVDVMPETPLPPLRVLGLAPDLVDYHAAWDAQRALHADVVAGRSDGEFLLLEHEA
VYTAGRRTEDAERPTDGAPVVDVDRGGKITWHGPGQLVGYPVVRLRDRAHVHVYVWFLVA
LLIRTAAEFGVTAVRVDGRAGIWVLADRDDDGTARPDRKVGAIGLSIHDGVSMHGFALNC
SNSLAPYEGIIACGITDAATTTLSVETGRTITPADVVPVLTRH----LDELG---PAYIA
VTPTEGIPA
>fig|2.1421.peg.1397|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MHGFALNC
SNSLDAYDRIVPCGIRDAGVTTLSRVIGRTVTPADVVPLLRPHLVRALDPNGSAMPATAP
LSPATGARA
>fig|2.1425.peg.686|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------MAHVRRLED
ALIALLADLDVASYRVDGRSGVWIRGAAPDG--SPRDEKVAAIGVRVAERVTMHGFALNC
SNAFDAYDCIVPCGIRDAGVTSISRAIGRTVTPADVVPLLRPHLVRALSSNGSAMPATAP
LSSVAGARA
>fig|33013.175.peg.464|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------MAHVRRLED
ALIALLADLDVASYRVDGRSGVWIRGAAPDG--SPRDEKVAAIGVRVAERVTMHGFALNC
SNAFDAYDCIVPCGIRDAGVTSISRAIGRTVTPADVVPLLRPHLVRALSSNGSAMPATAP
LSSVAGARA
>fig|33013.181.peg.2013|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------MAHVRRLED
ALIALLADLDVASYRVDGRSGVWIRGAAPDG--SPRDEKVAAIGVRVAERVTMHGFALNC
SNAFDAYDCIVPCGIRDAGVTSISRAIGRTVTPADVVPLLRPHLVRALSSNGSAMPATAP
LSSVAGARA
>fig|2.1418.peg.1026|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------MRRLED
ALIALLADLDVASYRVDGRSGVWIRGAAPDG--SPRDEKVAAIGVRVAERVTMHGFALNC
SNAFDAYDCIVPCGIRDAGVTSISRAIGRTVTPADVVPLLRPHLVRALSSNGSAMPATAP
LSSVAGARA
>fig|6666666.68540.peg.356|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MHGFALNC
SNAFDAYDRIVPCGIRDAGVTSISRAIGRTVTPADVVPLLRPHLVRALSSNGSAMPATAP
LSSVAGARA
>fig|6666666.374469.peg.71|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MVDIVVTGLSANSVPYIEALERQRALHADVVAGRAQDTVILLEHPS
VYTAGRRTEPEDRPRDGTPVIDVDRGGRITWHGPGQLVGYPIVRLPEPLDVVAHVRRLED
ALIALLADLDVASYRVDGRSGVWIRGAAPDG--SPRDEKVAAIGVRVAERVTMHGFALNC
SNAFDAYDRIVPCGIRDAGVTSISRAIGRTVTPADVVPLLRPHLVRALSSNGSAMPATAP
LSSVAGARA
