>fig|2.1422.peg.1881|594139
------MIEWILAE------WMQILGFATGAACVVLAARRNVWTYPIGIANNVVFLAVFV
--------PAGLYASAALQLVYLVLGVHGWIRWTRGVEHDRGYVARTPRRAVPW------
--LIAVAIGGTAVLTWVLATFTDSQVAVADAATTSASLVAQYMLNRKWIENWGVWIAVDV
AFVGLSIATGLWIIAALYALFIVLCIGGWRGWTRVM-RESPAAAPA--DARV--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|6666666.155597.peg.968|300756
MDWLVDAFNWTIPVAGGGLLMREVLGNVFGLASALGGMARRVWAWPVGILGNLILLTVFL
ASLFTGADHATLLGQAGRQVMFIAVSVYGWARWRQA---RRGRAEDAPAITPEWAGWRGR
VFLVTAMAVGTVALTPVFRALGSWEPVWADAWTFVGSLLATYGMARGWVEFWLIWVAVDV
VGVPLLWSTGYYASAVMYAFYGAFTLIGFFVWLRATDRDKPAVETLLPDGP--EGDVAR-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|6666666.235531.peg.272|430840
----MDAFNWTIPVAGGGLLMREVLGNVFGLASALGGMARRVWAWPVGILGNLILLTVFL
ASLFTGADHATLLGQAGRQVMFIAVSVYGWARWRQA---RRGHAEDAPAITPEWAGWRGR
VFLVTAMAVGTVALTPVFRALGSWEPVWADAWTFVGLLLATYGMARGWVEFWLIWVAVDV
VGVPLLWSTGYYASAVMYAFYGAFTLIGFFVWLRATDRDKPAVETLLPDGP--EGDVAR-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|2.1421.peg.1710|594133
MAALEWLFDAQLRIGDQVVLWREIVGNLFGLASALGGMRRKVWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQA---RHGGA----PVVPQWASGRER
VLLVVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VGVPLLVSAGYYASAFMYVFYGAFTLTGFFVWMRARGTASPAVETAFPDPRVVEAPAER-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|33013.175.peg.2552|614133
-----------------------------------------MWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQA---RHGGA----PVVPQWASGRER
ILLVVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VCGPLLVSAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|6666666.68540.peg.664|151744
------------------------------------------------------------
--------------------------------------------------MPQWASGRER
ILLVVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VGVPLLVSAGYYASAFMYVFYGAFTLTGLFVWMRARGTDAPAVETAFPDPRIVEAPAER-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|33013.181.peg.1457|614141
MAALEWLFDAQLRIGDQAILWREIVGNLFGLASALGGMRRKVWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQA---RHGGA----PVVPQWASGRER
ILLVVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VGVPLLVSAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAERG
VTAPGSLGPGRPAEVVAHEHAGPRVGHVPDLLGPHVPEPDALVEVDGRRQVDAAAEHDGA
RSPSSCLVERGQEQPPPGPPPADGLVDRHLGELPHAVALGDQGHAADDAVPIAGEEHRAA
AVDDLAAGVRQHALVVGLEREQRRDPCLVEGAEGVGVGVAAERRDLDRGGRGRGRALGVR
GHGSSFPAAASRVQYERHRSDSFREWISTSASSAPSSPSPTSGTSAGPPSSSASRSRCCP
SRCSASSAGSA
>fig|6666666.374469.peg.2905|645144
MAALEWLFDAQLRIGDQAILWREIVGNLFGLASALGGMRRKVWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQA---RHGGA----PVVPQWASGRER
ILLVVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VGVPLLVSAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|2.1418.peg.2109|594099
------------------------------------------------------------
------------------------MSVYGWYRWQQA---RHGGA----PVVPQWASGRER
ILLVVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VGVPLLVSAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>fig|2.1425.peg.2633|594242
------------------------------------------------------------
------------------------------------------------------------
---MVALVGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDL
VGVPLLVSAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
