>fig|6666666.155597.peg.1470|300756
----------------------------------------------------MRSRYTAF
ARLGEAGPAEARAMADYLAATWVPEHRPTAAELLPAAGEQAPRFTRLAVLDVRDGGPFQD
AGTVEFVAVGTGAEGRFRLHEVSRFRREDGIWRYVNGDVR--------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|6666666.235531.peg.1604|430840
------------MTRPEPCPCGSGAGLAACCGRLHARFARDGALTAPTAEALMRSRYTAF
ARLGEAGPAEARAMADYLAATWVPEHRPTAAELLPTEGEQAPRFTRLAVLDVRDGGPFQD
AGTVEFVAVGTGAEGRFRLHEVSRFRREDGIWRYVDGDVR--------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1422.peg.75|594139
---MSFGSASVRPSATDACPCGEGE-FGTHCGPLL-----DGEP-APGAERLMRSRYTAF
AV-GDAA---------HLARSWHPRTRPDEIEVGDGT-----RWIGLDIVSAEEGA---D
AAVVSFRARWRHGSEAGELRERSRFVRRAGRWVYVDGDVDERGGRAARGEASSPNGRVGG
SAYGRERILGERTRMIPDAHRDLLENPNYGSLGTVRPDGTVQVNPMWFDFDGEHLLFTHT
TTRQKFRNLQQNPSMSLMVFDPAQPYRYIEVRGRLVEAEPDPTGAFYVHLGKRYGNAEQE
APPDSADRVILKMSIEKVGGQ
>fig|2.1421.peg.2136|594133
MTRLSPDAPWSTPDDDAWCPCTSGDPYGACCGPLH-----RGDSRAPTAERLMRSRFAAY
AR-GDAA---------YLARSWHPSTRPAELDLDPSI-----RWFRLTIVRTAQGGPDDA
TGVVEFEAAYRHKGGRGSQHEASRFARYAGSWVYVDAM----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|33013.181.peg.1213|614141
----------------------------------------------------MRSRFAAY
AR-GDAA---------YLARSWHASSRPEEIDLDPSV-----RWFRLPIHRTSLGGPDDA
TGVVDFEASFRHDGERGSQREASRFVRHAGPGVYLDAF----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|6666666.374469.peg.2591|645144
MTRLSPDAPWSTPDDDAWCPCTSGDAYGACCGPLH-----RGDTAAPTAERLMRSRFAAY
AR-GDAA---------YLARSWHASSRPEEIDLDPSV-----RWFRLTIHRTSLGGPDDA
TGVVDFEASFRHDGERGSQREASRFVRHAESWVYLDAF----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1418.peg.1813|594099
MTRLSPDAPWSTPDDDAWCPCTSGDAYGACCGPLH-----RGDTAAPTAERLMRSRFAAY
AR-GDAA---------YLARSWHASSRPEEIDLDPSV-----RWFRLTIHRTSLGGPDDA
TGVVDFEASFRHDGERGSQREASRFVRHAGSWVYLDAF----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|6666666.68540.peg.960|151744
----------------------------------------------------MRSRFAAY
AR-GDAA---------YLARSWHASSRPEEIDLDPSV-----RWFRLTIHRTSLGGPDDA
TGVVDFEASFRHDGERGSQREASRFVRHAGSWVYLDAL----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1425.peg.2463|594242
----------------------------------------------------MRSRFAAY
AR-GDAA---------YLARSWHASSRPEEIDLDPSV-----RWFRLTIHRTSLGGPDDA
TGVVDFEASFRHDGERGSQREASRFVRHAGSWVYLDAF----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|33013.175.peg.573|614133
----------------------------------------------------MRSRFAAY
AR-GDAA---------YLARSWHASSRPEEIDLDPSV-----RWFRLTIHRTSLGGPDDA
TGVVDFEASFRHDGERGSQREASRFVRHAGSWVYLDAF----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
