>fig|6666666.155597.peg.30|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAKVLDGKATAAAIKEELRGRVAALAERGHTPGLGTLLVGEDAGSQKYV
AGKHRDCAEVGIESIQRELPADATEEQILDVVRELNEDPACTGYIVQLPLPKHVDTQKVL
EAIDPDKDADGLHPMNLGRLVASVGGELDSPLPCTPAGCVELLRHHGVELAGKHVLVIGR
GVTIGRPAGLVLTRREVNATVTLAHTGTTNLDELLASADVVIAAAGSAHMVKPDQVKEGV
IVLDVGVSRVTG-EDGKSRVLGDVDPAVKEKAAWMAPNPGGVGPMTRVMLLANVVEAAER
AAEDDGRAGERVGA
>fig|6666666.235531.peg.1667|430840
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAKVLDGKATAAAIKEELRGRVAALAERGHTPGLGTLLVGEDAGSQKYV
AGKHRDCAEVGIESIQRELPADATEEQILDVVRELNEDPACTGYIVQLPLPKHVDTQKVL
EAIDPDKDADGLHPMNLGRLVASVGGELDSPLPCAPAGCVELLRHHGVGLAGKHVLVIGR
GVTIGRPAGLVFTRREVNATVTLAHTGTTNLDELLASADVVIAAAGSAHMVKPEQVKEGV
IVLDVGVSRVTG-EDGTSRVLGDVDPAVKEKAAWMAPNPGGVGPMTRVMLLANVVEAAER
AADGEDWAGERAGA
>fig|2.1422.peg.1091|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTATILDGKAASAAIKAELSERVAALRAKGIVPGIATVLVGADPASQLYV
GMKHKQSEAIGMNSIQVELPAEATQQEVEAVIDRLNADPECHGYIVQLPLPKHIDTDAIL
ERIDPAKDADGLHPTNLGRLVLNVNAPIHTPLPCTPRGVIELLLRNDYDLKGKEVVVVGR
GVTIGRSIGLLLTRREINATVTLTHTGTADLAKHLREADVIVAAAGVKHIVRAADVKPGA
AVLDVGVTRETDPETGKSRVYGDVHPDVAEVAGFVSPNPGGVGPMTVALLMTNVVEAAER
AA----------SA
>fig|33013.181.peg.1283|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLT---TRARATSSRR------SAG-----RTSWSRP--
-----WVSRTSSSRSGSSRA-----PRCSTSASRVSWIPRPGRRASRATWIRPSPRSPAT
CR----RTRAGSGR
>fig|2.1421.peg.1003|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRQAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLERYDVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLQQEVRRADIVVAAVGVAHLIEPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLVNVVLAAER
DA----RLAAELRG
>fig|6666666.68540.peg.1612|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRAYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DA----RLAAELRG
>fig|6666666.374469.peg.1874|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DA----RLAAELRG
>fig|2.1418.peg.908|594099
MLKESHARRPVLQRPPLRGRPGDRGRPRAGARASARHPRDDRERELRAARGAAVAGIRAH
QQVRGGLPGPPLLRRLRVRRRGRAARHRPREEPLRRRVRERPAALGRHRQRRRPRRHRAA
RRHDPRPRARARRPPHARHEAQLLRQALRRGGVRRRSRHLPHRHGRRAREGARAPPAGHH
RGLVGVPPPPRLRRVPVDRRRGRREALGRHGALRGPRGRGRAPLARPVRGRRLLHRAQDP
RGPPVRRDPQPRHRARQEAQLGRVPGPAGRPAHARHRGQGHGVQDRGHRGVRGPPAPHHP
GRADPRRAPRRGRLHRGRRLGPHGRHGRAPRARGSAELAHRRQAGGGRAARGRHHGQPQL
GAVRPAPADGHLRRPHRHVRARDPRLRRDRVHGGGGHHRRDPEARQRPRRPACARAHAHR
RLPALRGPHPVTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DA----RLAAELRG
>fig|33013.175.peg.2499|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DA----RLAAELRG
>fig|2.1425.peg.1294|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------ML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DA----RLAAELRG
