---
output: pdf_document
---
<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." -->

# Background {.unnumbered}

Enzymes catalice chemical reactions transforming substrates into producs. During 20th century enzymes were percived as highly specific catalizer, nevertheless this percepcion changed with the discovery that they can . This abilty to catalice several chemical functions its known as enzyme promscuity. Escherichia coli contains at least 404 promiscuous enzymes. La relevancia de la promiscuidad radica tanto en su papel como mecanismo de evolucion de la funcion enzimatica, asi como en la necesidad de su deteccion para la correccion de modelos de flujo metabolico y la determinacion de efectos secundarios en drogas farmacologicas. A pesar de su frecuencia e importancia aun se esta en el proceso de entender las causas y las caracteristicas observables de la promiscuidad enzimatica.
  
Para estudiar la promiscuidad esta propuesta discierne entre dos problemas. El primero es el de ubicar cuales familias tienen enzimas promiscuas, al que llamaremos problema de las familias. El segundo es el de los miembros: una vez identificada una familia promiscua, como distinguir entre sus miembros enzimas con distinto nivel de promiscuidad. Se ha intentado identificar enzimas promiscuas, a nivel de secuencia, sin pasar por experimentacion mediante aprendizaje maquina. Estos enfoques son incapaces de identificar una familia promiscua si no se conoce previamente al menos un miembro promiscuo de ella. Por otra parte, en el problema de los miembros se presentan dificultades cuando la identidad de secuencia es alta, e.g. en la familia PriA-HisA se sabe que la enzima HisA de E. coli no es promiscua, pero PriA de Streptomyces coelicolor si lo es. 
  
Para mejorar nuestro entendimiento del fenomeno, ademas de la comparacion de secuencias es necesario integrar otros elementos de analisis. Se debe notar que es practicamente imposible decir que una enzima no es promiscua ya que para ello se deberian haber descartado todos los posibles sustratos. Sin embargo, para el estudio de cambios en promiscuidad se han detectado como elementos relevantes a los cambios en vecindad genomica, los cambios en flexibilidad durante la dinamica molecular, la perdida de genes centrales, y finalmente a las expansiones genicas dentro de un grupo taxonomico. Estos elementos tienen en comun que reflejan un cambio en alguna propiedad genomica o biofisica, de lo que se deriva que el buscar cambios en la promiscuidad de una enzima resulta mas factible que la busqueda intrinseca de promiscuidad, a lo que aspiran los metodos basados en comparaciones de secuencias. 
  
Evomining es una plataforma bioinformatica pensada para la busqueda de expansiones de familias genicas de metabolismo central. Desarrollarla en combinacion con algoritmos de busqueda de cambios en la vecindad genomica la haran una plataforma ideal para abordar el problema de las familias, proporcionando una solucion a la dificultad de no tener conocimiento previo de un miembro promiscuo en la familia investigada. Respecto al problema de los miembros, se propone explorar variaciones en vecindad genomica, flujo genico y dinamica molecular, como candidatos a reflejar la variacion en promiscuidad. Finalmente, he detectado que a pesar de que pruebas in vivo son mas sensibles a niveles bajos de promiscuidad que mediciones in vitro, esta ultima suele ser la unica estudiada. In vivo, la metabolomica aplicada en genes biosinteticos de productos naturales ha ayudado en la identificacion de sustratos, por lo que esta tecnica podria ayudar a revelar el nuevo sustrato de una enzima en la que se sospecha ganancia de promiscuidad. En resumen, el objetivo de mi trabajo sera abordar los dos problemas de promiscuidad considerando la diferenciacion in vitro e in vivo tomando como modelo biologico el phylum Actinobacteria, un grupo de bacterias reconocido por su diversidad metabolica donde se ha probado la existencia de promiscuidad enzimatica. 
    
## Introduction  
  
Para estudiar la promiscuidad es necesario contar con una definicion, algunos autores emplean el termino promiscuidad para describir actividades enzimaticas distintas a la funcion principal [@khersonsky_enzyme_2010] otros lo ven como una actividad secundaria fortuita [@copley_enzymes_2003] que pudo aparecer de forma accidental o inducida artificialmente [@hult_enzyme_2007]. Otros mas, cuando una enzima puede operar sobre un amplio rango de sustratos, prefieren llamarla multiespecifica [@khersonsky_enzyme_2010]. A la accion de realizar distintas funciones cataliticas, ya sea al catalizar varias reacciones quimicas o bien una misma reaccion en sustratos diferentes se le conoce como promiscuidad enzimatica [@obrien_catalytic_1999]. Existen varios tipos de promiscuidad enzimatica.    

Por sustrato cuando la reaccion es la misma pero se lleva a cabo en distintos sustratos ejemplo la familia PriA [@baronagomez_occurrence_2003] y la familia de betalactamasas [@risso_phenotypic_2014]  

Catalitica cuando la enzima utiliza diferentes mecanismos de reaccion y/o residuos cataliticos, e.g. la quimotripsina puede catalizar reacciones de amidasa y fosfotriesterasa en un mismo sitio activo. [@obrien_catalytic_1999] 
Por condiciones del entorno, cuando la enzima cambia su conformacion dependiendo de las condiciones quimicas y fisicas presentes como pH, temperatura, solventes organicos y salinidad e.g. algunas lipasas pueden actuar como sintetizadoras de esteres en lugar de hidrolasas en presencia de solventes organicos [@hult_enzyme_2007,@kumari_preparation_2007].  
  
 Este trabajo se enfocara a la promiscuidad por sustrato, entendiendo asi que la enzima es capaz de catalizar la misma reaccion quimica en al menos dos sustratos. La promiscuidad por sustrato es importante en terminos evolutivos, por ejemplo la enzyme commission number (EC) separa las enzimas en clases, a cada enzima se asignan 4 digitos, los tres primeros corresponden a la reaccion y el ultimo al sustrato; el mayor numero de sustratos (4306 clases) que de reacciones quimicas (234 en el tercer nivel) sugiere que la mayor variacion evolutiva se da a nivel de sustrato y no de reaccion [@li_computational_2004]. Otra evidencia de la importancia de la multiespecificidad por sustrato esta en el descubrimiento de las superfamilias, enzimas mecanistica y estructuralmente relacionadas que divergen en su afinidad por sustrato [@glasner_evolution_2006, @baier_evolution_2016]  
  
Si bien existen familias de enzimas con alta especificidad por sustrato, otras familias como el citocromo P450 [@bloom_neutral_2007, @nath_quantitative_2008] y las beta lactamasas [@zou_evolution_2015] son promiscuas. Es posible que la vision previa de alta especificidad se deba a que las primeras rutas metabolicas estudiadas pertenecen al metabolismo central, donde la especificidad puede haber sido favorecida por presiones de seleccion [@firn_darwinian_2009]. Esta vision ha cambiado debido al conocimiento de mas enzimas con multifuncionalidad [@jia_multifunctional_2013], sin afectar la eficiencia catalitica por la funcion primaria [@aharoni_evolvability_2005]. En 1976 el interes por la promiscuidad comenzo por su influencia en la evolucion de la funcion enzimatica[@jensen_enzyme_1976, @pandya_enzyme_2014], las aproximaciones variaron desde la aparicion de la sintesis funcional [@dean_mechanistic_2007], cuando la disponibilidad de genomas permitio la combinacion de analisis filogeneticos con tecnicas de biologia molecular, bioquimica y biofisica (Fig 1). En 2003 la biofisica de las proteinas entra en escena al postularse que la diversidad conformacional durante la dinamica molecular debe incidir en la aceptacion de distintos sustratos. Recientemente se ha investigado su papel en efectos secundarios en drogas farmacologicas  [@nobeli_protein_2009,@hopkins_drug_2009,@nath_quantifying_2010,@von_eichborn_promiscuous:_2011, @zhang_multidimensional_2012, @zou_evolution_2015]. Entre 2005 y 2010 se avanza del estudio de una sola familia enzimatica hacia el interes por propiedades globales, por ejemplo dado un genoma se investiga la distribucion de familias promiscuas en subsistemas metabolicos. En estos años, surge el desarrollo de indices que reflejen las caracteristicas bioquimicas de enzimas promiscuas. En 2010, comienzan los intentos por desarrollar un metodo computacional de prediccion de promiscuidad. Desde 2012 a la fecha, a la par que las aproximaciones bioinformaticas se multiplican, se desarrollan investigaciones de aspectos biofisicos, bioquimicos y evolutivos de enzimas promiscuas reafirmando que todos estos aspectos estan relacionados al fenomeno. En las siguientes secciones se describiran trabajos importantes sobre la relacion que guarda la promiscuidad con expansiones genomicas y flexibilidad molecular. Ademas se hablara sobre analisis bioquimicos y metabolicos para la descripcion del fenomeno.
  
\TeX\ or \LaTeX\   
### Funcion biologica de la promiscuidad enzimatica  
¿Por que existe la promiscuidad enzimatica? Se tiene evidencia de dos papeles biologicos: el primero proporcionar robustez a la red metabolica de un organismo mediante redundancia de reacciones de otras enzimas; el segundo permitir plasticidad evolutiva, es decir materia prima para la adaptacion a variaciones ambientales [@aharoni_evolvability_2005,@sanchez-ruiz_promiscuity_2012, @martinez-nunez_lifestyle_2015] mediante la adquisicion de nuevas funciones quimicas. Respecto a la robustez, se probo que sobreexpresar enzimas promiscuas puede rescatar perdidas genicas [@patrick_multicopy_2007]. De 104 knockout sencillos de genes esenciales para  E. coli K-12, 20% de las auxotrofias pudieron ser suprimidas por la sobreexpresion de plasmidos que contenian enzimas promiscuas. Otro ejemplo que aporta a la robustez es PriA, enzima de la ruta de histidina que realiza en la ruta del triptofano la reaccion E.C. 5.3.1.24 [@baronagomez_occurrence_2003]. En cuanto a la plasticidad se propone que para que la promiscuidad pueda dar origen a la aparicion de nuevas funciones la actividad promiscua debe proveer una ventaja fisiologica inmediata para poder ser seleccionada positivamente, ademas una vez que una funcion promiscua se vuelva relevante se debe poder mejorar mediante pocas mutaciones derivando en el intercambio entre la actividad promiscua y la principal[@khersonsky_enzyme_2010].  

Aun cuando el producto de la promiscuidad genera metabolitos que no se integran al metabolismo central de la celula, su efecto es positivo ya que estos metabolitos podrian colaborar a la adaptacion al entorno participando por ejemplo en una relacion de simbiosis o de competencia con otros organismos. Este tipo de metabolitos, por lo general, no son dañinos [@notebaart_network-level_2014, @linster_metabolite_2013, @khanal_differential_2015] y pueden servir como bloques de construccion para vias metabolicas nuevas [@ma_unconventional_2013, @adams_promiscuous_2014, @soskine_mutational_2010]. La respuesta inmediata de adaptacion de un organismo podria ser una consecuencia de su grado de promiscuidad.    
    
###Relacion del pangenoma con la promiscuidad enzimatica  
El core genome de un grupo taxonomico es el conjunto de secuencias codificantes presentes en todos los organismos del grupo. En el Dominio Bacteria el core esta estimado entre 200 y 300 secuencias [@halachev_calculating_2011].  Dada su conservacion el core genome puede utilizarse para trazar mejores relaciones filogeneticas que las obtenidas con el uso exclusivo de marcadores como la subunidad 16s del RNA ribosomal o el gen rpoB. El pangenoma es el conjunto complemento del core genome, es decir todas aquellas secuencias que estan ausentes de uno o mas organismos del grupo y por lo tanto no son necesarias para todos, sino solo posiblemente para el organismo que las posee. Como en el pangenoma la presion de seleccion esta relajada respecto al core-genome [@firn_darwinian_2009] es el conjunto donde la plasticidad genomica tiene facilidades para desarrollarse. 
  
Esta idea puede restringirse a subsistemas metabolicos para identificar genes cuyas enzimas estan en proceso de cambio de funcion quimica, por ejemplo, en este trabajo se encontro que el gen trpF esta presente en solo 49 de 290 genomas analizados del genero Streptomyces por lo que se encuentra en el pangenoma de triptofano de este genero taxonomico, posiblemente adquiriendo una nueva funcion [@ma_unconventional_2013]. Para evitar problemas tecnicos del calculo del pangenoma existen otros modelos de medicion de variabilidad del genomica entre especies bacterianas [@kislyuk_genomic_2011]. 
  
### Expansion y contextos genomicos como herramienta de anotacion funcional  
La diversidad enzimatica existente es el resultado de un proceso de expansion, mutacion y seleccion que se ha desarrollado durante el transcurso de la historia evolutiva [@khersonsky_enzyme_2010, @pearson_prehistoric_2012]. Existe evidencia de que cierto grado de promiscuidad o divergencia funcional precede a la duplicacion genica [@hughes_evolution_1994]. Por este motivo detectar expansiones ya sea duplicaciones o transferencias horizontales [@treangen_horizontal_2011], puede ser un buen punto de partida para determinar divergencia funcional y promiscuidad. No todas las expansiones denotan cambio de funcion enzimatica, algunas pueden ser meros accidentes, sin embargo dado que la funcion de una enzima suele estar relacionada con sus vecinos [@overbeek_use_1999,@zhao_prediction_2014,@zhao_discovery_2013, @verdel-aranda_molecular_2015],  una expansion en una vecindad genomica diferente de la tradicional sera un referente de adquisicion de una nueva funcion y entonces un indicador de existencia previa de promiscuidad.  
  
La funcion de una enzima es un concepto jerarquico, dependiente de la filogenia de un organismo [@szklarczyk_string_2015,@szklarczyk_string_2015]. Para sistematizar el estudio de contextos y vecindades genomicas se desarrollo Search Tool for the Retrieval of Interacting Genes/Proteins STRING [@snel_string:_2000], que cuenta con una anotacion de ortologia jerarquica y consistente, realizada en 2000 organismos en cuyo marco interacciones de proteinas con implicaciones funcionales son predichas tanto de novo por informacion genomica de co-ocurrencia como por mineria de datos en articulos publicados. STRING es una base de datos, y como tal no permite agregar nuevos genomas para su analisis. Sus 2000 organismos incluyen especies tanto bacterianas como eucariotas. Al existir tanta diversidad, los genomas disponibles para un genero o clase especificos son escasos, p. g. de los mas de 300 genomas disponibles de Streptomyces solo 24 estan incluidos. 
  
Para resolver la baja cobertura de STRING hacia ciertos grupos taxonomicos se pueden desarrollar scripts de vecindad genomica utilizando RAST (Rapid Annotation using Subsystem Technology); un servicio interactivo de anotacion automatica de genomas de bacterias y arqueas [@aziz_rast_2008,@overbeek_seed_2014] donde la funcion de cada gen se asigna de acuerdo a conocimiento previo de subsecuencias de organismos cercanos filogeneticamente, cuando es posible se incluye en un subsistema metabolico. Estamos en una era de explosion de datos genomicos, proximamente se espera contar con millones de genomas bacterianos incluso provenientes de bacterias no cultivables, por ello los algoritmos deben ser constantemente optimizados a los nuevos volumenes de datos [@medema_computational_2015]. Ante esta expectativa seria muy util desarrollar algoritmos de analisis genomico que sean de codigo libre o al menos interactivos para que cada laboratorio pueda personalizarlos para sus propios genomas.
  
Finalmente, no solo la vecindad genomica inmediata puede ser utilizada como distintivo en la busqueda de promiscuidad, diferencias en el contexto genomico en genes relacionados con una enzima promiscua, sin importar su ubicacion dentro del genoma tambien pueden ser relevantes para la perdida o ganancia de funcion quimica [@noda-garcia_evolution_2013], (Juarez Vazquez et al 2015). 
  
### Modelos bioinformaticos de promiscuidad  
Con el fin de reducir la inversion en el proceso de experimentacion, se han implementado en los ultimos años algoritmos computacionales para predecir promiscuidad enzimatica [@carbonell_molecular_2010, @cheng_global_2012, @nagao_prediction_2014, @noda-garcia_insights_2015,@garcia-seisdedos_probing_2012]. Estos procedimientos cuentan con un conjunto de aprendizaje, unos descriptores del conjunto, una fase de ajuste de parametros y finalmente una prediccion. En 2010, Carbonell propone un algoritmo de soporte vectorial basado en subsecuencias de distinto tamaño que llama huellas moleculares. En este trabajo aplicado sobre 500,000 proteinas reportadas en la enciclopedia de Kyoto de genes y genomas (KEGG) se reporta 85% de exito en deteccion de enzimas promiscuas anotadas en KEGG. En 2012, Cheng compara los metodos de random forest y soporte vectorial en 6799 proteinas provenientes de la base de datos Universal Protein Resource (UniProt). Las enzimas son descritas con subsecuencias de aminoacidos incorporando ademas caracteristicas biofisicas como polaridad. Se utiliza como  grupo de control a familias de enzimas donde nunca se ha reportado una enzima promiscua.  
  
Un aspecto no considerado en estos metodos es que hay familias de enzimas con alta identidad de secuencia entre sus miembros, con cambios bruscos en promiscuidad, debidos por ejemplo a la dinamica genomica [@noda-garcia_evolution_2013,@verdel-aranda_molecular_2015], lo que dificulta que considerar solo la secuencia conlleve a buenos predictores de promiscuidad. Cuando se obtiene una prediccion positiva utilizando los modelos existentes, lo que significa es que dada esa secuencia, en su familia se conoce previamente un elemento promiscuo y que ademas sus subsecuencias de cierto tamaño son suficientemente similares. Estos enfoques no pueden predecir de novo, en familias donde la promiscuidad no ha sido previamente detectada experimentalmente, pues no consideran aspectos evolutivos ni mecanisticos de las enzimas.
  
Otra limitante a los enfoques descritos es que mezclan en su conjunto de entrenamiento fenomenos distintos de promiscuidad. Cheng p. g. incluye enzimas moonlight que si bien poseen funciones adicionales a la catalizacion, son distantes a las enzimas promiscuas [@copley_enzymes_2003]. Ademas en ambos casos mezclan en el mismo conjunto enzimas bacterianas y eucariotas, con lo que si existia una huella basada en secuencia entonces esta puede diluirse por la gran distancia taxonomica entre estos grupos (Tabla 1).
  
###Promiscuidad in vitro y promiscuidad in vivo  
La ganancia de promiscuidad no solo puede entenderse como la capacidad de convertir mas sustratos [@carbonell_molecular_2010], sino tambien como la mejora de la capacidad catalitica respecto a ellos. El I-index [@nath_quantitative_2008], esta definido como un rango de valores entre 0 y 1 que tiende a 1 entre mas parecida sea la actividad de la enzima sobre distintos sustratos, la capacidad catalitica es medida en terminos del cociente de Michaelis - Menten $\frac{K_{cat}}{K_m}$. El indice ha sido utilizado para predecir la afinidad por sustrato del citocromo P450 [@nath_quantifying_2010]. Una limitante del indice $I$ es que se deben conocer los sustratos a los que la enzima es afin; sin embargo se puede sospechar que una enzima ha ganado promiscuidad aun sin conocer sus potenciales sustratos. Otro punto a señalar es que las variables Kcat,Kmson mediciones realizadas in vitro y no se consideran todos los sustratos presentes in vivo. Para solventar esta dificultad e investigar variaciones de sustratos nativos se pueden buscar productos similares a los ya conocidos por medio de analisis metabolicos [@nesvizhskii_analysis_2007] como los empleados en la deteccion de rutas no conservadas en la biosintesis de productos naturales [@medema_computational_2015]. En particular para este fin se ha utilizado espectrometria de masas MS/MS, [@nesvizhskii_analysis_2007,@campbell_biophysical_2012] combinada con molecular networking para identificar productos similares [@yang_molecular_2013,@kocher_mass_2007]
  
### El papel de la dinamica molecular en la promiscuidad  
La estructura tridimensional de una proteina es obtenida mediante previa purificacion y cristalizacion. Aunque mucho se ha hablado de la relacion estructura funcion, al cristalizar se obtienen estados conformacionales homogeneos, que bien pueden no ser la unica conformacion que adopta la proteina en solucion. [@james_conformational_2003]. En particular en el problema de promiscuidad, se ha observado que la variacion funcional no queda obviamente reflejada en la variacion estructural, lo que sugiere un rol significativo para la dinamica molecular [@parisi_conformational_2015,@noda-garcia_evolution_2013,@zou_evolution_2015]. Se postula que un aspecto de la dinamica molecular relevante para la diversificacion de especificidad por sustrato es el numero de conformeros [@javier_zea_protein_2013]. Por ejemplo, en la actinobacteria Corynebacterium diphtheriae parece que el contexto genomico correlaciona con perdida de promiscuidad de PriA ya que al poseer el genoma una copia de trpF, la enzima perdio esta funcion quimica conservando solo la funcion EC 5.3.1.16 correspondiente a la ruta de histidina. Esta sub-funcionalizacion se refleja en la perdida de estados conformacionales cambiando desde 1 estado en C. diphtheriae hasta 4 presentes en la dinamica de PriA de M. tuberculosis [@noda-garcia_evolution_2013].  
  
Las regiones rigidas de una enzima proporcionan orientacion adecuada con respecto a los grupos cataliticos, mientras que las regiones flexibles permiten al sitio activo adaptarse a los sustratos con diferentes formas y tamaños [@copley_enzymes_2003]. Esta consideracion sugiere que la flexibilidad del sitio activo es otra caracteristica de la dinamica molecular a considerar para obtener informacion de la capacidad de ligacion de una enzima a distintos sustratos [@gatti-lafranconi_flexibility_2013]. Recientemente el indice de flexibilidad dinamica (dfi) se utilizo como una medida cuantitativa basado en la respuesta a perturbaciones de aminoacidos (PRS). Este indice se incremento en regiones cercanas al sitio activo de beta lactamasas promiscuas respecto al correspondiente dfi de $\noindent\beta$ -lactamasas especialistas existentes [@zou_evolution_2015]. 
  
### Modelo biologico diversidad de Actinobacteria  
Al escoger un conjunto acotado para investigar familias de enzimas promiscuas se debe recordar que la funcionalidad es jerarquica por lo que para mejorar la anotacion, es deseable reflejar el proceso evolutivo y restringirse a un grupo de organismos taxonomicamente relacionados [@cruz-morales_phylogenomic_2016]. Actinobacteria es un phylum que posee promiscuidad tanto en el metabolismo periferico como en el core metabolico. Entre datos publicos (NCBI) y privados estan disponibles alrededor de 1200 genomas no redundantes de especies de Actinobacteria. Como punto de partida, se han estudiado las relaciones filogeneticas y grupos de ortologia [@li_orthomcl_2003,@waterhouse_orthodb_2013], en particular en Actinobacteria para identificar relaciones entre las familias del phylum, se obtuvieron arboles multilocus de entre 100 y 157 genomas [@gao_phylogenetic_2012,@sen_phylogeny_2014]. Estos estudios sugieren como separar los genomas disponibles para hacer el calculo de grupos de ortologia. Finalmente, se han realizado estudios de plasticidad genomica en Streptomyces considerando 5 y 17 organismos de los 300 genomas disponibles en la actualidad [@zhou_genome_2012,@kim_comparative_2015] donde reportan 2,018 familias en el core genome y 32,574 en el pangenoma.  

###Modelo metabolico biosintesis de aminoacidos.  
Al hacer el calculo vemos que Streptomyces, un genero del phylum Actinobacteria cuenta en su genoma con un promedio de 8316 secuencias codificantes segun la especie. Gran parte de estas secuencias pueden ser agrupadas en subsistemas metabolicos como metabolismo de carbohidratos o de lipidos; de estos subsistemas uno de los mas amplios es el metabolismo de aminoacidos con entre 429 y 910 secuencias segun el organismo.  La sintesis de aminoacidos es un subsistema presente en todas las especies pero con suficientes variaciones que permiten hacer observaciones evolutivas. En un gran numero de Actinobacterias las rutas de histidina y triptofano de 7 y 11 pasos respectivamente convergen en una enzima bifuncional llamada PriA, que realiza tanto la funcion de HisA como la de TrpF [@baronagomez_occurrence_2003]. La cantidad de familias en el subsistema de metabolismo de aminoacidos, su variabilidad, su conservacion entre distintos grupos taxonomicos  y la existencia de estos ejemplos en Actinobacteria lo posicionan como un buen punto de partida para la busqueda de promiscuidad tanto de familias promiscuas como de miembros promiscuos de las mismas.  
  
## Antecedentes   
En las cuatro decadas de estudio de la promiscuidad enzimatica, hemos aprendido que es un fenomeno distribuido en distintos subsistemas metabolicos [@nam_network_2012] y que su existencia puede deberse tanto al desarrollo de nuevas funciones para fines adaptativos [@jensen_enzyme_1976,@obrien_catalytic_1999,@firn_darwinian_2009,@copley_evolutionary_2015], como al rescate de una funcion perdida [@patrick_multicopy_2007,@baronagomez_occurrence_2003]. Por ello la dinamica de perdida y ganancia de genes asociada al contexto genomico en bacterias se relaciona con cambio en la funcion enzimatica [@zhao_discovery_2013,@zhao_prediction_2014, @copley_evolutionary_2015]. Precisando, respecto a la ganancia de genes, se postula que la bifuncionalidad precede la duplicacion [@hughes_evolution_1994,@obrien_catalytic_1999]. Lo que implica que dada una duplicacion muy posiblemente previamente la promiscuidad estuvo presente [@gerlt_divergent_2001,@huang_enzyme_2012,@noda-garcia_evolution_2013,@risso_phenotypic_2014]. 
  
Se han desarrollado tecnicas bioquimicas y metabolicas de medicion [@nath_quantitative_2008], asi como algoritmos computacionales de prediccion de promiscuidad [@carbonell_molecular_2010,@cheng_global_2012,@noda-garcia_insights_2015]. Un aspecto a mejorar dentro del modelado es la restriccion del conjunto de estudio a un grupo taxonomico tan reducido que exista congruencia en las familias de ortologia y a la vez tan amplio que permita observar efectos evolutivos; el phylum Actinobacteria ha probado tener ejemplos de promiscuidad. Si bien la secuencia no ha sido suficiente para la correcta prediccion de promiscuidad [@verdel-aranda_molecular_2015,@copley_evolutionary_2015], es posible que dentro de las tecnicas computacionales la flexibilidad durante la dinamica molecular este correlacionada con la promiscuidad de los miembros de una familia [@james_conformational_2003,@javier_zea_protein_2013,@noda-garcia_evolution_2013,@zou_evolution_2015]. 
  
### Modelo biologico   
De los mas de mil genomas actualmente disponibles de Actinobacterias, se seleccionaron 888 (correspondientes a 49 familias), que no estan excesivamente fragmentados; es decir con un estimado de al menos 5 genes por contig (Tabla 2). Estos genomas fueron divididos en tres grupos (http://pubseed.theseed.org/wc.cgi?request=show_otus&base=/homes/nselem/Data/CS), uno de ellos correspondiente a Streptomycetaceae, la familia con la mayor cantidad de genomas disponibles; los otros dos grupos siguieron la taxonomia propuesta por Gao & Gupta en 2012. En el grupo de 290 genomas de Streptomycetaceae 2,126,832 ORFS fueron clasificados en 288,390 familias; de las 919,292 ORF del grupo I de Actinobacteria resultaron 269,406 familias. Las relaciones taxonomicas fueron corroboradas con algoritmos propios basados en  best bidirectional hits (BBH). 
  
### Subsistemas metabolicos  
Los operones his y trp de histidina [@fondi_evolution_2009] y triptofano [@merino_evolution_2008] respectivamente, participantes del metabolismo de aminoacidos estan ampliamente distribuidos en los organismos bacterianos. En Actinobacteria la familia promiscua PriA participa en ambas rutas biosinteticas, para su estudio se han generado datos bioquimicos, genomicos y estructurales(Tabla 3). En bacterias gram negativas estan presentes los operones his y trp y en lugar de PriA su familia homologa HisA. PriA comprende un conjunto de subfamilias en Actinobacteria.  En Streptomyces, el gen trpF se desplaza de la vecindad genomica de trp, con lo que el homologo de hisA gana promiscuidad aunque con baja actividad de TrpF, a esta subfamilia se le llama PriB [@verduzco-castro_co-occurrence_2016]. En otras Actinobacterias trpF se pierde totalmente y la familia homologa de HisA, se vuelve promiscua [@baronagomez_occurrence_2003] realizando tanto la funcion quimica correspondiente a HisA como la de TrpF. Finalmente en la familia subHisA se pierde la funcion TrpF debido posiblemente a la ganancia del operon trp completo [@noda-garcia_evolution_2013] y en  la familia subtrpF  se conserva solo a la funcion TrpF debido a la perdida del operon his [Juarez vazquez et al 2015 in prep]. Existen al menos 43 familias de Actinobacteria sin explorar respecto a la funcionalidad de PriA.
   
###Contexto y vecindades genomicas  
En 2012 fueron analizados 102 genomas de 29 familias de Actinobacteria [@noda_estudio_2012]. sugiriendo que al menos en Corynebacteria el contexto y la vecindad genomica incidian en la sub-funcionalizacion de PriA en subHisA [@noda-garcia_evolution_2013]. Respecto a IlvC, otra familia involucrada en la sintesis de aminoacidos fue estudiada y caracterizada bioquimicamente en 1 Corynebacterium y 8 Streptomyces [@verdel-aranda_molecular_2015]. Para ampliar estos resultados, utilizando la anotacion de RAST y una generalizacion de la definicion de vecindad de STRING, se diseño un algoritmo para identificar vecindades similares asi como uno de visualizacion de contexto, ambos disponibles como software libre en github [nselem/perlas](https://github.com/nselem/perlas) .  
  
El algoritmo de clasificacion de vecindades permite agruparlas en clusters y calificar estos clusters segun su conservacion dado un grupo de bacterias. La definicion de vecindad y similitud de vecindad esta descrita posteriormente en los metodos. El algoritmo fue aplicado a la familia IlvC en 290 Streptomyces resultando 9 clusters [Datos](http://148.247.230.43/nselem/CONTEXTS/REL_St275/ilvC/Contextos.php) entre los mas poblados el primero cuenta con 279 elementos, otro con 9 elemento y dos mas con 7 miembros (Fig 3), resultados experimentals son congruentes con que existe divergencia funcional entre miembros de clusters distintos [@verdel-aranda_molecular_2015]

### Metodos bioinformaticos  
Al evaluar PROMISE [@carbonell_molecular_2010] en un set de datos de la familia HisA/PriA [@noda-garcia_insights_2015] obtuve que su mejor desempeño es con huella molecular de tamaño 6, donde clasifica correctamente casi todas las no promiscuas, (HisA) pero no sucede lo mismo con la familia PriA donde tiene exito en 16 de 45 casos. Al aplicar el mismo tamaño de huella a 9 miembros promiscuos de la familia IlvC no consigue predecir correctamente ninguno de ellos. Por lo menos para estas familias el conjunto de entrenamiento o los descriptores no son suficientes para la anotacion de promiscuidad.
  
### Evomining   
Evomining es una plataforma bioinformatica pensada para la identificacion de productos naturales que tiene entre sus exitos la identificacion de la biosintesis de arsenolipidos [@cruz-morales_phylogenomic_2016]. La busqueda de productos naturales cuenta entre sus premisas que estos se producen en vecindades genomicas llamadas clusters y que ademas clusters cercanos (ya sea en contenido genico o en la secuencia de sus componentes), exploran variaciones metabolicas, es decir sus enzimas catalizan reacciones sobre sustratos parecidos aunque no identicos [@cruz-morales_phylogenomic_2016,@medema_computational_2015]. La base de evomining es que las enzimas de metabolismo secundario son expansiones distantes de enzimas de rutas centrales, lo que da idea de la quimica que realizan dichas expansiones dejando por identificar el sustrato sobre el que trabajan. La primera version de evomining cuenta con 200 genomas de Actinobacteria, una base de datos de secuencias de enzimas de productos naturales y otra base de datos de secuencias de enzimas de rutas centrales curada a mano. Evomining esta ligada con el problema de la promiscuidad porque en estas familias expandidas ya sea por duplicacion o por transferencia horizontal, las expansiones pueden retener la funcion quimica de las rutas centrales y viceversa, la funcion quimica expandida suele estar presente antes de la duplicacion. 
  
Si se combinara evomining con la premisa de que vecindades distintas son marcadoras de funciones quimicas distintas, al encontrar una familia expandida con vecindades genomicas diferentes se podria solventar la deficiencia de otros metodos bioinformaticos consistente en que para identificar familias promiscuas se debe conocer previamente un miembro promiscuo de la misma. (Fig 4) Asi pues al combinar evomining con herramientas de vecindad genomica tanto de comparacion como de visualizacion estaremos mejorando su funcionalidad en la identificacion de familias promiscuas.
  
### Caracterizacion in vivo  
 Algunas enzimas PriA no han mostrado promiscuidad in vitro pero si in vivo ya que sobreviven en un medio sin triptofano, es decir in vivo complementan la funcion trpF.  Para la construccion de cepas de Streptomyces con variantes no nativas de priA minimizando la modificacion genomica y el efecto de sobreexpresion, se planea utilizar E. coli como intermediario para realizar seleccion por auxotrofia. Se cuenta con un conjunto de plasmidos para transformar a E. coli asi como con las mutantes sencillas de E. coli para trpF y hisA que permiten realizar seleccion por auxotrofias. Ademas tenemos una coleccion de cepas nativas de Streptomyces asi como un mutante de PriA de S. coelicolor. Se optimizo una reaccion de PCR para la amplificacion de un segmento de DNA de S. coelicolor que contiene a priA.
  
### Caracterizacion bioquimica in vitro.  
De la familia PriA y sus subfamilias se han caracterizado bioquimicamente miembros selectos de Actinomycetaceae, Bifidobacteriaceae, Micrococcaceae, Acidimicrobiaceae, Corynebacterium, Mycobacteriaceae, Streptomycetaceae, Camera (provenientes de metagenoma), reconstrucciones ancestrales, 80 mutantes de Corynebacterium, y 2 mutantes de Camera mediante cineticas enzimaticas para calcular las constantes Kcat,Km. El genero Streptomyces, el que cuenta con mayor cantidad de genomas disponibles representa una oportunidad muy poco explotada de explorar la influencia del contexto y la vecindad genomicas en secuencias de PriA (Tabla 3, Figura 5).
  
### Modelado de dinamica molecular  
La dinamica es un metodo que permite hacer simulaciones de particulas que sirve para obtener informacion de propiedades macroscopicas de un conjunto de atomos [@petrenko_molecular_2001,@kukol_molecular_2008]. Es util en el marco de mi proyecto porque permite la exploracion del espacio conformacional, y se ha visto que este esta relacionado con la actividad de la enzima [@sikosek_biophysics_2014], ademas dado un conformero permite verificar su estabilidad. Resuelve la ecuacion de movimiento de Newton con base a una configuracion inicial, las fuerzas interatomicas como los enlaces covalentes, las fuerzas de Van der Waals  y la carga de las particulas[@campbell_biophysical_2012]. Entonces para generar una simulacion de dinamica molecular, debe contarse con una estructura como punto de partida, ya sea esta cristalografica o modelada de novo o por homologia. El laboratorio de bioinformatica y biofisica computacional ha desarrollado un protocolo de generacion de modelos homologos estructurales y dinamicas moleculares (Carrillo-Tripp et al 2015 in prep); con este pipeline se han generado dos estructuras de Camera [@noda-garcia_insights_2015], 30 estructuras y dinamicas de miembros de Actinobacteriaceae y Bifidobacteriaceae (Vazquez-Juarez et al in prep.) y finalmente una estructura de subHisA de Corynebacterium diphteriae. En la familia Streptomyces, interesante debido a su variacion en contexto genomico y en mediciones in vitro aun no se modelan dinamicas moleculares aunque 40 estructuras por homologia estan en proceso. 
  
En un estudio de subHisA [@noda_estudio_2012] se utilizo el metodo de dinamica molecular y se comparo el numero de conformeros entre miembros de subHisA y PriA, resultando mayor el de PriA como corresponde a una enzima promiscua. El estudio sobre la relacion dinamica-flexibilidad de $\noindent\beta$-lactamasas  utiliza replica exchange, una variacion de dinamica molecular que corre replicas en paralelo a distintas temperaturas [@bai_replica_2006]. Una desventaja de este metodo es que por el costo computacional de las replicas agregar explicitamente otras moleculas a la simulacion como el solvente no es posible en tiempo razonable. Una vez generadas las dinamicas moleculares se procedera a calcular tanto el numero de conformeros como el indice de flexibilidad dsi [@zou_evolution_2015]. Se esta desarrollando PEDB, promiscuous enzyme database, una base datos genomicos, evolutivos, bioquimicos y estructurales y de metabolismo de PriA en Actinobacteria donde se procedera al analisis de los mismos (http://148.247.230.43/nselem/PHP/queries.html).
  
En conclusion la promiscuidad enzimatica es un fenomeno complejo debido a multiples causas. Existe una gran variedad de estudios con enfoques puntuales sobre aspectos estructurales, dinamicos y evolutivos de familias de enzimas promiscuas, sin embargo hasta ahora no se han reportado trabajos multidisciplinarios que involucren a todas las partes involucradas (Fig 6)
  
## Objetivo General   
  
Estudiar el fenomeno de promiscuidad enzimatica tanto desarrollando estrategias para identificar familias promiscuas dentro de un grupo taxonomico, como comparando variaciones de promiscuidad in vitro e in vivo  con variaciones en contexto genomico y flexibilidad en miembros de una familia. (Figura 7)

## Objetivos particulares  
Mejorar evomining como metodo de identificacion de familias enzimaticas promiscuas aprovechando los cambios en vecindades genomicas como caracteristicas informativas provenientes de datos filogenomicos. 
Estudiar la relacion entre historias filogenomicas y procesos biofisicos con la promiscuidad in vitro, a traves de mediciones de ciertas caracteristicas de la familia PriA.
Caracterizar cambios de promiscuidad enzimatica in vivo mediante perfiles metabolomicos de actividades de PriA y enzimas asociadas.

## Estrategias  
### La promiscuidad en familias enzimaticas.  
  
Mejorar Evomining mediante la  identificacion de cambios de vecindad genomica en familias selectas de metabolismo central convirtiendola en una plataforma de codigo libre disponible para otros investigadores.  

#### Obtener informacion genomica del phylum Actinobacteria.  
  
Colectar genomas de Actinobacteria de NCBI y de colecciones privadas.  
   
### Anotar consistentemente las secuencias codificantes de estos genomas.    
  
Utilizar un anotador automatizado y desarrollar los scripts necesarios para anotar los genomas.  

#### Establecer las relaciones filogeneticas de los genomas colectados.  

Mediante el uso del core genome construir un arbol filogenomico que permita establecer un marco sobre el cual hablar de cambio y que facilite reclasificar los genomas mal nombrados.  

##### Identificar cambios en la vecindad genomica en familias selectas de enzimas de metabolismo central.
Clasificar sistematicamente las secuencias de familias codificantes segun su similitud en familias enzimaticas.   
Desarrollar las herramientas bioinformaticas necesarias para separar clusters de vecindades genomicas.  

#### Sistematizar Evomining para convertirla una plataforma descargable y utilizable en cualquier set de datos bacterianos relacionados taxonomicamente proporcionados por el usuario.  
Ampliar el contenido de Evomining al integrar los genomas colectados de Actinobacteria.
Sistematizar la base de datos de metabolismo central.  
Desarrollar la visualizacion e integrar la clasificacion de vecindades genomicas como una herramienta adicional en la busqueda de promiscuidad.  

#### Promiscuidad in vitro dentro de miembros de una familia promiscua de enzimas. 
Dados los sustratos conocidos de PriA investigar las posibles correlaciones entre mediciones de constantes cataliticas, contexto genomico, vecindad genomica, numero de conformeros e indice de flexibilidad.  

#### Seleccionar miembros homologos de la familia de enzimas.   
Se escogieron 41 Streptomyces repartidos en un arbol de rpoB de 400 Streptomyces con genoma disponible. Esta seleccion incluye los seis Streptomyces de los que se cuenta con cinetica enzimatica de PriA, tres de ellos con estructura cristalografica.  
#### Medir cineticas enzimaticas, contexto genomico, vecindad genomica, flexibilidad y numero de conformeros.  
Determinar la pertenencia a uno de cuatro posibles contextos genomicos respecto al gen trpF. Estudiar la existencia de distintas vecindades genomicas. Determinar la cinetica enzimatica de 9 enzimas mas buscando variabilidad en contexto genomico (sugeridas en la tabla 4). Obtener mediante una colaboracion 37 modelos estructurales por homologia y modelar dinamica molecular.  
   
La siguiente tabla contiene la diversidad de contextos y vecindades genomicas de 41 Streptomyces respecto al gen trpF.  

#### Determinar posibles correlaciones entre los datos producidos.  
Numero de conformeros e indice de promiscuidad.   
indice de flexibilidad y numero de conformeros.  
Numero de conformeros y contexto genomico.  
indice de flexibilidad y contexto genomico.  
Contexto genomico e indice de promiscuidad I.  
Analizar las vecindades genomicas e indice de promiscuidad I.  

### Desarrollar una metodologia para la deteccion in vivo de promiscuidad enzimatica.  
Debido a cambios en flexibilidad o cambios de contexto genomico, se puede sospechar de diferencias en la funcion quimica de dos miembros de una familia de enzimas, sin conocer las diferencias a nivel de sustratos. Para investigar estos cambio in vivo  se propone estudiar diferencias en perfiles metabolomicos de una coleccion de cepas en condiciones diversas.  

####Crear cepas geneticamente modificadas con variantes funcionales no nativas de PriA y enzimas asociadas.  
Dado un organismo modelo sustituir su homologo nativo de priA por una variante no nativa ya sea de priA o trpF de Actinobacterias selectas de las que se sospecha cambio en promiscuidad.  
####Separar posibles productos y minimizar los falsos positivos debidos a perturbaciones metabolicas no relacionadas a PriA.    
Separar los metabolitos mediante cromatografia dirigida por tamaño. Obtener un espectro de masas antes y despues de  la sustitucion de la variante y sobre las diferencias en el espectro realizar espectrometria de masas en tandem (MS/MS) es decir refragmentar  y analizar que los fragmentos contengan partes parecidas a los sustratos conocidos.
  

##Metodologia
A continuacion describire la metodologia para cada una de las estrategias expuestas previamente. Todos los scripts desarrollados fueron escritos en perl y estan disponibles en github https://github.com/nselem/perlas.
  
###La promiscuidad en familias enzimaticas.  

####Actinobacteria genomic  
Para obtener informacion genomica del phylum Actinobacteria mediante la coleccion de genomas de NCBI se revisaron todas las familias de Actinobacteria de la base genoma de NCBI y se seleccionaron los genomas con minimo 5 genes por contig. Se crearon scripts para utilizar la interfaz e-utils de NCBI y descargar estos genomas desde la terminal a partir de una lista de identificadores.
   
####Annotation  
Para anotar consistentemente las secuencias codificantes de estos genomas se utilizo el anotador automatizado RAST y se desarrollaron los scripts necesarios para anotar los genomas desde la terminal, conectado asi NCBI y RAST.

####Genomic DB phylogeny  
Establecer las relaciones filogeneticas de los genomas colectados.
Mediante el uso del core genome para construir un arbol filogenomico, para reclasificar los genomas mal nombrados.   
Para obtener el core genome y en base a el reclasificar los genomas se diseño el algoritmo estrellas basado en Best Bidirectional Hits (blast all vs all). 
    
Estrellas. Se realiza un blast all vs all de genomas deseados. Para cada secuencia, centrado en cada genoma se realiza una lista (estrella) de sus mejores hits bidireccionales. Si las listas de todos los genomas coinciden es un BBH multiple y se agrega la lista al core genome. (Fig 9) Una vez con el core genome completo se puede reconstruir la filogenia. Este metodo fue exitoso en la deteccion de una familia marcadora de Clavibacter michiganensis (2014 Rodriguez-Orduña in prep). 
   
###Identificar cambios en la vecindad genomica en familias selectas de enzimas de metabolismo central.  
Clasificar sistematicamente las secuencias de familias codificantes segun su similitud en familias enzimaticas.  

Como se menciono en los antecedentes, se han separado 888 genomas de Actinobacteria en 3 grupos taxonomicos utilizando para la anotacion la tecnologia de subsistemas de RAST. Para la separacion en familias iso funcionales (ortologos, paralogos y expansiones) n se utilizo RAST, especificamente el script What Changed (WC) que asigna un numero a cada familia, esta herramienta esta basada en k-mers,  su codigo esta disponible en github: (https://github.com/kbase/kbseed/blob/master/service-scripts/svr_CS.pl). Ademas de en los tres grupos ya mencionados, tambien se realizara una clasificacion para trescientos genomas de Actinobacteria distribuidos en todas sus familias taxonomicas.
   
Para desarrollar las herramientas bioinformaticas necesarias para separar clusters de vecindades genomicas a continuacion se describe detalladamente como se definicio vecindad genomica y la relacion implementada de similitud.
  
1.  Un conjunto expandido es un conjunto que contiene secuencias homologas asi como sus expansiones: paralogos y transferencias horizontales. Dado un conjunto de genomas, se pueden calcular y enumerar todos sus contextos extendidos utilizando WC. 
    
2.  Un PEG es un elemento de un conjunto expandido. Dado un PEG p, se define CE(p) el numero del conjunto expandido de p, como el numero asignado por WC al conjunto expandido a que p pertenece.
  
3.  La vecindad de un PEG es el conjunto de PEGs cercanos a el. Dado un umbral en terminos de distancia de pares de bases entre puntos medios para precisar la definicion de cercano, se pueden calcular todos los contextos de un genoma. 
    
4. Una vecindad Aes n-similar a otra vecindad B si C={aA |  b B ,CE(b)=CE(a)} tiene al menos cardinalidad n. Es decir si existen al menos n elementos de A que pertenecen al mismo conjunto expandido que algun elemento de B.
  
5.  Un conjunto de vecindades es un conjunto de PEGs clusterizado segun la relacion n-similaridad.  Si A es n-similar a B y B esn-similar a C entonces, aun si A no fuese n-similar a C, los PEGs generadores de A,B,C son agrupados dentro del mismoconjunto de vecindades.
  
6. Un cluster es un conjunto de conjunto de vecindades.
  
7. Los clusters son evaluados segun el numero y la cardinalidad de sus conjuntos de vecindades.
       
Sea Cl un cluster, donde CCi es un conjunto de contextos y ni es la cardinalidad de CCi
Cl={CC1,CC2,...,CCk} 
   
Sean M la cardinalidad maxima de un conjunto de contextos y m la cardinalidad maxima sin considerar M.  
```{r}

#$$   M\eq\max_{ni} i\eq{1,2,..,k}         m\eq\max_ni i\eq {1,2,...,k}  ni\ne{M}  $$

```
$$\sum_{j=1}^n (\delta\theta_j)^2 \leq {{\beta_i^2}\over{\delta_i^2 + \rho_i^2}}
\left[ 2\rho_i^2 + {\delta_i^2\beta_i^2\over{\delta_i^2 + \rho_i^2}} \right] \equiv \omega_i^2
$$


M representa el contexto mas difundido de  la enzima, dentro del grupo taxonomico considerado; mes relevante porque si m es grande significa que hay un segundo contexto genomico conservado en dicho grupo taxonomico, y entonces posiblemente una ganancia de funcion.  
  
La evaluacion de Cl esta dada por una combinacion lineal de k,m y M  
S(Cl)=f(k,m,M)=c1k+c2m+c3M  
  
Este algoritmo se puede mejorar considerando la orientacion de los genes del cluster asi como clusters de los vecinos.
  
####Organizar y presentar los datos en una plataforma.  
Para contribuir al desarrollo de la plataforma Evomining se desarrollaran scripts de visualizacion de arboles filogeneticos y contextos genomicos.  
  
Para facilitar el analisis visual de una vecindad genomica ya la vez generar imagenes de alta calidad facilmente exportables para su uso en publicaciones, se desarrollaran scripts de visualizacion que utilizaran el formato Scalable Vector Graphics (SVG), dicho formato es basicamente un archivo de texto XML que contiene instrucciones para que el navegador realice un dibujo (W3school/SVG 2015). Al ser vectores, las imagenes generadas en SVG no pierden resolucion al ser escaladas y justamente por ser escalables permiten explorar con detalle grandes cantidades de datos organizados por ejemplo en arboles filogeneticos. Los scripts a desarrollar extraeran para cada gen informacion necesaria como coordenadas, direccion, funcion quimica, etc, proveniente de la anotacion de RAST y de los scripts de comparacion de vecindades genomicas. La primera version de evomining fue desarrollada en el lenguaje perl; este lenguaje cuenta con un modulo para facilitar la elaboracion de SVG (perlmaven/SVG 2015) por lo que al utilizar SVG no se agregan nuevos requerimientos a su desarrollo y se facilita su portabilidad.
   
Se amplificara Evomining de los 200 genomas con que contaba su version inicial a los 880 colectados mudando la curacion manual de su base de datos de rutas centrales a la anotacion por subsistemas de RAST. Finalmente se presentara la variacion en vecindades genomicos como una herramienta adicional que ayude en la busqueda de promiscuidad en familias de enzimas pertenecientes al metabolismo central.
   


###Promiscuidad in vitro  
####Datos cineticos:  
En todos los ensayos enzimaticos se busca medir una señal que permita una distincion clara entre sustrato y producto [@bisswanger_general_2011]. La cinetica enzimatica de PriA proveniente del genero Streptomyces sera determinada como ya se ha reportado previamente, mediante el monitoreo de cambios en fluorescencia (isomerizacion del sustrato PRA) o en absorbancia (isomerizacion del sustrato PROFAR). En el caso de la isomerizacion de PRA, debido a que contiene un anillo de antranilato, la fluorescencia del sustrato PRA es 50 veces mayor que la del producto 1-(2-carboxyphenylamino)-1-deoxy-D-ribulose 5-phosphate (CdRP) por lo que se utiliza la disminucion en fluorescencia como medida de la conversion del sustrato en producto [@hommel_phosphoribosyl_1995]. Se mandaran sintetizar estas variantes para posteriormente sobre expresarlas en E. coli. Se creceran cepas modificadas de E. coli (W-, H-) en medio minimo M9 enriquecido con una mezcla de aminoacidos excepto L-histidina y L-triptofano y se seleccionaran por rescate de auxotrofia. Para obtener la enzima necesaria para los ensayos enzimaticos se utilizaran plasmidos disponibles para construcciones de sobreexpresion de proteina, despues de la produccion la enzima se purificara utilizando cromatografia por afinidad a niquel [@verduzco-castro_co-occurrence_2016].
  
Finalmente se recopilaran datos cineticos de PriA tanto privados como los publicos reportados a la fecha en la BRaunschweig ENzyme DAtabase BRENDA [@scheer_brenda_2011]. Una vez colectados los datos se anotaran en PEDB, nuestra base de datos ad hoc, y se tomara como medida de promiscuidad el I-index [@nath_quantitative_2008] que se define como:
 I=1ln Ni=1Npi( pi) donde pi=Kicat Kim   / i=1NKicatKim   
    
####Dinamica molecular    
Para generar dinamicas moleculares primer lugar se recolectaran las estructuras tridimensionales de miembros de PriA de Actinobacteria. Despues se procedera a modelar por homologia las estructuras tridimensionales faltantes utilizando el pipeline del laboratorio de bioinformatica y biofisica computacional. Este pipeline utiliza el software Rosetta para el modelado para las estructuras y GROMACS Groningen Machine for Chemical Simulation, [@van_der_spoel_gromacs_2005] para el modelado de la dinamica molecular. Esta parte del trabajo se realizara en colaboracion con el laboratorio de bioinformatica y biofisica computacional.
  
###Promiscuidad in vivo  
Se realizaran construcciones con variantes no nativas de priA y/o trpF en Streptomyces coelicolor. Para las construcciones se amplificara mediante PCR un fragmento alrededor de PriA que se insertara en un vector. Este vector recombinara en E. coli con un casete provisto de un gen marcador de resistencia a antibiotico y este gen recombinado se pasara por conjugacion a S. coelicolor donde se espera que realice una doble recombinacion. El paso por E. coli es llevado a cabo porque Streptomyces no se puede transformar por electroporacion. Se seleccionaran las cepas de Streptomyces resistentes al antibiotico como prueba de que ya no poseen su priA nativa. Posteriormente, mediante un procedimiento analogo se sustituira el gen marcador, por variantes no nativas de priA/trpF.
   
La cromatografia se refiere a un conjunto de metodos que separan y analizan mezclas de moleculas. Basicamente estos metodos se basan en diferencias en el tamaño, intercambio de iones y afinidad. [@campbell_biophysical_2012] Posteriormente se combinan con espectrometria de masas que  es una tecnica que mide el radio masa-carga de las particulas fragmentadas en iones. [@campbell_biophysical_2012]. Los datos obtenidos de espectrometria de masas se procesaran utilizando redes moleculares, que consiste en agrupar los productos segun la similitud de sus partes. Plan: 3 replicas tecnicas, 2 replicas biologicas de 5 cepas.  
    
###Consideraciones   
Falsos negativos respecto a promiscuidad estan muy extendidos en la literatura y en las bases de datos, en parte porque la mayoria de las funciones son asignadas por similitud de secuencia y dado un falso negativo el error se propaga en secuencias similares. Por otro lado es muy dificil demostrar un verdadero negativo a menos que se prueben todas las posibilidades de sustrato para la enzima. Sin embargo el espacio de sustratos puede acotarse gracias a tecnicas como el docking que esta intimamente relacionado con la dinamica molecular [@campbell_biophysical_2012,@kukol_molecular_2008]. Limitar el espacio de sustratos puede retroalimentarse con el estudio de la promiscuidad in vivo y viceversa. 
   
Con los metodos propuestos en este trabajo solo se podra detectar perdida o ganancia de promiscuidad entre enzimas de organismos respecto a otros miembros dentro un grupo taxonomico, no asi el estado de promiscuidad intrinseco a la enzima. Si dada una enzima no se detectan variaciones en contexto, vecindad genomica o flexibilidad dentro de un grupo taxonomico cercano, entonces no podemos decir en principio nada acerca de la promiscuidad de la variante, posiblemente es promiscua pero al mantenerse constante en todos los parametros descritos, con estos metodos no se puede sugerir promiscuidad. Es posible que al mirar en un grupo taxonomico mas amplio se detecte una neofuncionalizacion de la familia aunque tambien es posible que exista una variable z como la flexibilidad de sustrato [@nobeli_protein_2009,@odokonyero_loss_2014] que no se este considerando y que explique o sea el mejor indicador para esta familia de promiscuidad enzimatica.
  
Se debe considerar que si existe una correlacion vecindad genomica-promiscuidad, esta no indica causa efecto, mas bien, es plausible que la vecindad sea un amplificacion de diferencias en secuencia,  a un numero igual de variaciones en secuencia la existencia de un cambio de vecindad indica un proceso mas largo y mas cambios, es una amplificacion de las marcas dejadas por transformaciones funcionales.
  
Si bien no se resuelve el problema de anotar promiscuidad automaticamente, este trabajo pretende aprovechar que los contextos genomicos ayudan a la identificacion de familias promiscuas para mejorar una plataforma de productos naturales, pretende tambien una confirmacion de que los cambios en la dinamica molecular ayudan a identificar los miembros mas promiscuos hacia actividades recien adquiridas, asi como tambien ser pionero en la investigacion de promiscuidad in vivo.  
  
Gene cluster plants[@osbourn_gene_2010]  
Archaeal core  [@makarova_comparative_1999]  
Natural products genomic era[@harvey_re-emergence_2015]   
Methanosarcina reconstruction [@benedict_genome-scale_2012]  
Archaea phylum[@seitz_genomic_2016]  
Prediction for possible products of promiscuous enzymes[@jeffryes_mines_2015]  
Saxitoxin [@moustafa_origin_2009]  
Plants clusters [@medema_computational_2016]  
MiBIG [@medema_minimum_2015]  
Metagenomics on Streptomyces [@iqbal_natural_2016]  
Sulfolobus reconsruction [@ulas_genome-scale_2012]  
Archaeal Natural products[@charlesworth_untapped_2015]    
Computational Pangenomics [@computational_pan-genomics_consortium_computational_2016]  
Cuántos genes "obtenidos por EvoMining" son core/ cloud/stand alone  
Qué porcentaje de genes únicos recupera EvoMining  
Eucarya paralogs reshape gene clusters [@chan_remodelling_2015]  
Microbial dark mater [@rinke_insights_2013]  
Archaea anaerobica carbon [@castelle_genomic_2015]
Archaea Eucarya gap loki[@spang_complex_2015]  
Archaea and eucarya[@koonin_archaeal_2015]  
BPGA [@chaudhari_bpga-_2016]
genes esenciales bacteria minima[@glass_essential_2006]  
Radical [@narechania_random_2012]  
RaxML large philogenies [@stamatakis_raxml_2014]  
R phylogenies [@phyloseq_powerful_2016]  
Streptomyces exploradores [@zacharia_exploring_2017]  
LUCA [@woese_universal_1998]
Luchando por el reconocimiento de Archaea[@woese_are_1981],[@woese_towards_1990]
The primary kingdoms [@woese_phylogenetic_1977]  
Predicccion aRchaeas [@woese_there_1994]  
RASt archaea [@graham_archaeal_2000]
Book Archaea [@howland_surprising_2000]   
Computational methods for bacterial and archaeal genomes [@xu_computational_2008]   
Archaeas boook [@garrett_archaea_2008]  
Bacterial /archaeal genome [@koonin_comparison_1997]  
Bacteria Archaea genome [@koonin_genomics_2008]  
Tree of life and HGC [@koonin_turbulent_2015]  
Genomas retrospectiva 20 años [@land_insights_2015]  
GC content plasmido genoma [@nishida_evolution_2012]
Genoma minimo[@coyle_mysteries_2016]  
Phylogeny R [@omeara_cran_2016]  
Cyanobacteria fluctuacion genomica y adaptacion [@larsson_genome_2011]  
Ecology of cyanobacterua [@whitton_ecology_2012]  
Histdine biosynthesis[@cohen_biosynthesis_2004]  
PriA reconstruction [@plach_long-term_2016]  
Escala temporl bacterias [@battistuzzi_genomic_2004]  
Pangenome size [@lapierre_estimating_2009]  
variabilidad del 16s [@vetrovsky_variability_2013]  