---
header-includes:
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{chemarr}
- \usepackage[caption=false]{subfig}
output: pdf_document
---

```{r include_reedtemplates_2, include = FALSE}
# This chunk ensures that the reedtemplates package is installed and loaded
# This reedtemplates package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```

```{r load_pkgs_chapter2, message = FALSE,echo=FALSE}
# List of packages required for this analysis
pkg <- c("dplyr", "ggplot2", "knitr", "devtools","RColorBrewer")
# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]
# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
# Load packages
library(dplyr)
library(plyr)
library(reshape)
library(ggplot2)
library(knitr)
library(RColorBrewer)
hm.palette <- colorRampPalette(rev(brewer.pal(11, 'Spectral')), space='Lab')  
#library(genstats) ## Next libraries are for coursera
library(devtools)
library(Biobase)
library(scales) # 
#library(xlsx) # For save data on excel

```

```{r load_data_docking, echo=FALSE}
docking <- read.csv("chapter2/table05", header=TRUE, sep="\t")
genomeOrder=factor(docking$genome,levels=unique(docking$genome))
names(docking)

docking.m <- melt(dockingS,id = "genome")
docking.m <- ddply(docking.m, .(variable), transform,rescale = rescale(value))
docking.m$genome <- factor(docking.m$genome, levels = rev(docking.m$genome[order(genomeOrder)]))
docking.m$variable <- factor(docking.m$variable, levels = names(rev(sort(apply(docking[,-1],2,sum)))))

docking.m$variable
#d <- dist(docking, method = "euclidean")
#fit <- hclust(d, method="ward") 
#plot(fit) # display dendogram
#names(docking)[order(fit$order)]
#docking.m$variable <- factor(docking.m$variable, levels = names(docking)[order(fit$order)])


ggplot(docking.m, aes(x=variable, y=genome)) + labs(x = "Substrates", y = "genome",text = element_text(size=12))+ geom_raster(aes(fill=value))+theme_bw()+theme(plot.title = element_text(size = 14, face = "bold"), text = element_text(size = 12), axis.title = element_text(face="bold"), axis.text.x=element_text(angle = 90,size = 6))+scale_fill_gradient(low = "white", high = "black",na.value = "orange")
  #scale_fill_gradientn(colours = hm.palette(100),na.value = "gray")

colorHeatPlot<-ggplot(docking.m, aes(x=variable, y=genome)) + labs(x = "Gene cluster Families", y = "genome",text = element_text(size=12))+geom_raster(aes(fill=value))+theme_bw()+theme(legend.position="none",plot.title = element_text(size = 14, face = "bold"), text = element_text(size = 12), axis.title = element_text(face="bold"), axis.text.x=element_text(angle = 90,size = 6))+ scale_fill_gradientn(colours = hm.palette(100),na.value = "gray")
ggsave(file="chapter2/BigSCAPEheatplot05.svg", plot=colorHeatPlot, width=10, height=15)

#gcolor$data[[1]]["fill"]
#gcolor$data[[1]]


```


```{r endsession}
#sessionInfo()

```