---
header-includes:
- \usepackage{graphicx,latexsym}
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{longtable,booktabs,setspace}
output: pdf_document
---
```{r include_packages_Objetivos, include = FALSE}
# This chunk ensures that the reedtemplates package is
# installed and loaded. This reedtemplates package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(plyr))
    install.packages("plyr", repos = "http://cran.rstudio.com") ## this shoul always go before dplyr
if(!require(dplyr))
    install.packages("dplyr", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("ggplot2", repos = "http://cran.rstudio.com")
if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```
  
# Objetivos  {.unnumbered}

## Objetivo General   
Estudiar el fenomeno de promiscuidad tanto desarrollando estrategias para identificar familias promiscuas, miembros promiscuos en dichas familias o clusters biosintéticos promiscuos dentro de un grupo taxonómico, como comparando variaciones de promiscuidad _in vitro_ con variaciones en contexto genómico y en propiedades relacionadas a la estructura tridimensional en miembros de una familia.  

## Objetivos particulares  
1. Desarrollar Orthocore un método para entendercuáles son los genes más conservados en el _core genome_ en un linaje taxonómico y aplicar este conocimiento.  

2. Mejorar EvoMining como método de identificación de familias enzimáticas promiscuas aprovechando los cambios en vecindades genómicas como características informativas provenientes de datos filogenómicos.  

3. Desarrollar CORASON una herramienta Optimizar el entendimiento de la evolución de clusters biosintéticos y vecindades genómicas diversas, para poder organizarlas jerárquicamente tal y como se pueden organizar las secuencias de enzimas. Con este conocimiento proponer y verificar mediante BGC promiscuo y verificar la hipótesis   

4. Estudiar la relacion entre historias filogenómicas y procesos biofísicos con la promiscuidad _in vitro_, a través de mediciones de ciertas características de la familia PriA.  

\clearpage  
  
# Estrategias   {.unnumbered}
#### Obtener informacion genomica de diversos linajes genómicos.  
Colectar genomas de Actinobacteria, Cyanobacteria, _Pseudomonas_ y Archaea de NCBI y de colecciones privadas.  

### Anotar consistentemente las secuencias codificantes de estos genomas.    
Utilizar un anotador automatizado y desarrollar los scripts necesarios para automatizar la anotación de los genomas.  

#### Establecer las relaciones filogenéticas de los genomas colectados.  
Mediante el uso del _core genome_ construir un arbol filogenomico que permita establecer un marco sobre el cual hablar de cambio.  

### La promiscuidad en familias enzimaticas.  
Desarrollar Evomining hasta el punto de convertirla en una distribución funcional de código libre disponible para otros investigadores. Agregar características que faciliten la investigación como la visualización de la vecindad genomica de los miembros de una familia y otros metadatos como el número de copias por organismo.   

##### Identificar cambios en la vecindad genomica en familias selectas de enzimas de metabolismo central.
Identificar familias de metabolismo central en los linajes genómicos seleccionados.  

Identificar mediante EvoMining las familias de metabolismo central con expansiones y reclutamientos que pueden presentar promiscuidad enzimática.  

Desarrollar las herramientas bioinformáticas necesarias para entender la conservación y evolución de BGCs u otras vecindades genomicas a las que pertenecen las expansiones de las familias centrales previamente seleccionadas.    

#### Promiscuidad in vitro dentro de miembros de una familia promiscua de enzimas. 
Dados los sustratos conocidos de PriA investigar las posibles correlaciones entre mediciones de constantes cataliticas, contexto genomico, vecindad genómica, estructura tridimensional y cambio en el número de copias en diversos linajes.  

#### Sistematizar Evomining para convertirla una plataforma descargable y utilizable en cualquier set de datos bacterianos relacionados taxonomicamente proporcionados por el usuario.  
-Ampliar el contenido de Evomining para poder analizar nuevas bases de datos genómicas, agregando por ejemplo los nuevos genomas colectados de Actinobacteria, así como los genomas de Cyanbacteria, $Pseudomonas$ y Archaea.  
Sistematizar la base de datos de metabolismo central.  

-Desarrollar la visualizacion e integrar la clasificacion de vecindades genomicas como una herramienta adicional en la busqueda de promiscuidad.  

 
#### Seleccionar miembros homologos de la familia de enzimas para modelado molecular.   
Se escogieron 41 _Streptomyces_ repartidos en un arbol de rpoB de 400 Streptomyces con genoma disponible. Esta selección incluye los seis _Streptomyces_ de los que se cuenta con cinética enzimatica de PriA, tres de ellos con estructura cristalográfica.  

#### Medir cinéticas enzimaticas, contexto genómico y vecindad genómica
Estudiar la existencia de distintas vecindades genomicas. Determinar la cinetica enzimatica de PriA respecto a sustratos atípicos sugeridos por los estudios estructurales. Obtener mediante una colaboración 37 modelos estructurales por homología y modelar docking molecular.  
   
\clearpage  
  
#Metodologia  {.unnumbered}
A continuacion describiré la metodologia para cada una de las estrategias expuestas previamente. Todos los scripts desarrollados fueron escritos en perl y estan disponibles en github https://github.com/nselem/perlas y empacados como un contenedor de docker.
  
###La promiscuidad en familias enzimaticas.  

#### Actinobacteria genomica  
Para obtener información genómica del phylum Actinobacteria mediante la coleccion de genomas de NCBI se revisaron todas las familias de Actinobacteria de la base genoma de NCBI y se seleccionaron los genomas con mínimo 5 genes por contig. Se crearon scripts para utilizar la interfaz e-utils de NCBI y descargar estos genomas desde la terminal a partir de una lista de identificadores. El mismo procedimiento se aplico a Cyanobacteria, _Pseudomonas_ y Archaea.  
   
#### Annotación
Para anotar consistentemente las secuencias codificantes de estos genomas se utilizó el anotador automatizado RAST y se desarrollaron los scripts necesarios para anotar los genomas desde la terminal, conectado asi NCBI y RAST. Se empacaron estos scripts en una distribución docker de myrast.  

#### Filogenia de la base de datos genómica  
Establecer las relaciones filogeneticas de los genomas colectados mediante el uso del _core genome_ para construir un arbol filogenómico, y para encontrar genes marcadores de un linaje taxonómico. Para obtener el _core genome_ y en base a el reclasificar los genomas se diseño el algoritmo Orthocore que generaliza el concepto de Best Bidirectional Hits (blast all vs all). 
    
Orthocore. Se realiza un blast all vs all de genomas deseados. Para cada secuencia, centrado en cada genoma se realiza una lista (estrella) de sus mejores hits bidireccionales. Si las listas de todos los genomas coinciden es un BBH multiple y se agrega la lista al core genome. Una vez con el _core genome_ completo se puede reconstruir la filogenia. Este metodo fue exitoso en la deteccion de una familia marcadora de _Clavibacter michiganensis_.
   
#### Organización y presentación de familias extendidas mediante el desarrollo una plataforma bioinformática.  
Se desarrolló EvoMining como una plataforma interactiva de consulta, se complementó con programas de visualización de árboles filogenéticos y contextos genómicos.   

#### Algoritmo de reconstrucción filogenética y visualización
Las secuencias de las familias enzimáticas expandidas fueron alineadas con muscle v3.2[@edgar_muscle_2004] y curadas con Gblocks v0.91b[@castresana_selection_2000]. Los parámetros de Gblocks fueron fijados en incluir 5 posiciones como el mínimo tamaño de un bloque y diez posiciones como el máximo de posiciones contiguas no conservadas. 
La selección de color de las hojas del árbol fue automatizada utilizando Newick Utilities una serie de programas llamados desde la terminal para manipular árboles en formato Newick[@junier_newick_2010].  La anotación funcional de RAST en su versión clásica[@aziz_rast_2008,@overbeek_seed_2014] fue agregada al SVG. 

#### Algoritmo de visualización  
Para facilitar el análisis visual de una vecindad genómica y a la vez generar imagenes de alta calidad exportables para su uso en publicaciones, se desarrolló código cuya salida es el formato _Scalable Vector Graphics_ (SVG). Este formato es básicamente un archivo de texto XML que contiene instrucciones para que navegadores como Chrome o firefox realicen un dibujo. Al ser vectores, las imágenes generadas en SVG no pierden resolucion al ser escaladas y justamente por ser escalables permiten explorar con detalle grandes cantidades de datos organizados por ejemplo en árboles filogenéticos. Los scripts estraen para cada gen información necesaria como coordenadas, dirección, función química. La anotación de función proviene de la anotacion de RAST, la visualización de vecindades genomicas fue desarrollada _de novo_. Los primeros análisis de EvoMining, antes de la existencia de esta plataforma fueron desarrollados en el lenguaje perl; este lenguaje cuenta con un modulo para facilitar la elaboracion de SVG (perlmaven/SVG 2015) por lo que se decidió utilizarlo y continuar el desarrollo en Perl para no agregar nuevos requerimientos y facilitar su portabilidad.
   
Se amplificara Evomining de los 200 genomas con que contaba su version inicial a los 880 colectados mudando la curacion manual de su base de datos de rutas centrales a la anotacion por subsistemas de RAST. Finalmente se presentara la variacion en vecindades genomicos como una herramienta adicional que ayude en la busqueda de promiscuidad en familias de enzimas pertenecientes al metabolismo central.
   
### Identificar cambios en la vecindad genomica en familias selectas de enzimas de metabolismo central.  
####Dinamica molecular    
Para generar dinamicas moleculares primer lugar se recolectaran las estructuras tridimensionales de miembros de PriA de Actinobacteria. Despues se procedera a modelar por homologia las estructuras tridimensionales faltantes utilizando el pipeline del laboratorio de bioinformatica y biofisica computacional. Este pipeline utiliza el software Rosetta para el modelado para las estructuras y GROMACS Groningen Machine for Chemical Simulation, [@van_der_spoel_gromacs_2005] para el modelado de la dinamica molecular. Esta parte del trabajo se realizara en colaboracion con el laboratorio de bioinformatica y biofisica computacional.
    
###Consideraciones   
Falsos negativos respecto a promiscuidad estan muy extendidos en la literatura y en las bases de datos, en parte porque la mayoria de las funciones son asignadas por similitud de secuencia y dado un falso negativo el error se propaga en secuencias similares. Por otro lado es muy dificil demostrar un verdadero negativo a menos que se prueben todas las posibilidades de sustrato para la enzima. Sin embargo el espacio de sustratos puede acotarse gracias a tecnicas como el docking que esta intimamente relacionado con la dinamica molecular [@campbell_biophysical_2012,@kukol_molecular_2008]. Limitar el espacio de sustratos puede retroalimentarse con el estudio de la promiscuidad in vivo y viceversa. 
   
Con los metodos propuestos en este trabajo solo se podra detectar perdida o ganancia de promiscuidad entre enzimas de organismos respecto a otros miembros dentro un grupo taxonomico, no asi el estado de promiscuidad intrinseco a la enzima. Si dada una enzima no se detectan variaciones en contexto, vecindad genomica o flexibilidad dentro de un grupo taxonomico cercano, entonces no podemos decir en principio nada acerca de la promiscuidad de la variante, posiblemente es promiscua pero al mantenerse constante en todos los parametros descritos, con estos metodos no se puede sugerir promiscuidad. Es posible que al mirar en un grupo taxonomico mas amplio se detecte una neofuncionalizacion de la familia aunque tambien es posible que exista una variable z como la flexibilidad de sustrato [@nobeli_protein_2009,@odokonyero_loss_2014] que no se este considerando y que explique o sea el mejor indicador para esta familia de promiscuidad enzimatica.
  
Se debe considerar que si existe una correlacion vecindad genomica-promiscuidad, esta no indica causa efecto, mas bien, es plausible que la vecindad sea un amplificacion de diferencias en secuencia,  a un numero igual de variaciones en secuencia la existencia de un cambio de vecindad indica un proceso mas largo y mas cambios, es una amplificacion de las marcas dejadas por transformaciones funcionales.
  
Si bien no se resuelve el problema de anotar promiscuidad automaticamente, este trabajo pretende aprovechar que los contextos genomicos ayudan a la identificacion de familias promiscuas para mejorar una plataforma de productos naturales, pretende tambien una confirmacion de que los cambios en la dinamica molecular ayudan a identificar los miembros mas promiscuos hacia actividades recien adquiridas, asi como tambien ser pionero en la investigacion de promiscuidad in vivo. 