---
author: 'Nelly Selem'
date: 'Enero 2019'
advisor: 'Francisco Barona Gomez'
#altadvisor: 'Your Other Advisor'
# Delete line 6 if you only have one advisor
department: 'Evolución de la diversidad metabólica'
title: 'La ocurrencia y variación de la promiscuidad en rutas del metabolismo especializado son reveladas por herramientas bioinformáticas evolutivas.'
abstract: >
  `r paste(readLines('abstract.Rmd'), collapse = ' ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the >.
acknowledgements: >
  Quiero agradecer por todas las enseñanzas a mis compañeros de trabajo César Aguilar, Pablo Cruz, Christian Eduardo, Hilda Ramos, Karina Verdel, Ernesto Verduzco, Alan, Daniel, Lianet Noda, Adriana Espinosa y Abraham Avelar. A Manu por su interés en emprender proyectos. A Dany mi veranito, a Ernesto de keri, Langebio, Secretaría inovación, CONABIO, BetterLab, Strain y DNAbits.
 
  A Abraham Avelar por su impaciencia, sus enseñanzas, revisión, esfuerzo y aportaciones a la vida.  
  
  A mi familia, papás  por el largo camino recorrido juntos.  
  
dedication: >
  A mis seres queridos. 
  
preface: >
  La promiscuidad ha redefinido cómo entendemos la función enzimática. Se ha transitado de considerar a todas las enzimas como altamente especialistas a entender que muchas de ellas pueden llevar a cabo más de una función metabólica. La promiscuidad parece parte del proceso evolutivo, provee material para que una posterior duplicación conlleve a la formación de nuevas familias enzimáticas. Esta tesis aborda el problema de promiscuidad distinguiendo entre familias de enzimas promiscuas y miembros promiscuos de una familia. A continuación generaliza el concepto de promiscuidad en una enzima a promiscuidad de un cluster biosintético (BGC). Para sugerir promiscuidad se desarrollan una serie de herramientas para estudiar el pangenoma de linajes taxonómicos. La primera herramienta Orthocore busca entender los genes conservados y sin expansiones entre organismos de un linaje. La segunda herramienta se ocupa al contrario de familias que sí tienen copias extra y propone como organizar esta variación en posibles destinos metabólicos. La tercera herramienta sube un nivel en la complejidad organizacional y busca entender la variación de grupos de genes (clusters biosintéticos) señalando una familia que presenta promiscuidad de producto. Finalmente estudiamos diversos aspectos de la familia PriA, una familia promiscua en Actinobacteria que no pasó por un proceso de duplicación reciente en Actinobacteria.  
  
bibliography: bib/Nelly.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/vancouver-brackets.csl #apa.csl
# Download your specific csl file and refer to it in the line above.
output: 
  reedtemplates::reed_thesis:
    toc: true
    toc_depth: 4
# Delete the # in line 28 to specify the depth of your table of contents
# Default is set to 3 (chapter, section, subsection)
lot: true
lof: true
space_between_paragraphs: true
link-citations: true
#figureTitle: "Figura"
#tableTitle: "Tabla"
#figPrefix: "fig."
#eqnPrefix: "ec."
#tblPrefix: "tbl."
#loftitle: "# Lista de figuras"
#lotTitle: "# Lista de tablas"

# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
header-includes:
# - \usepackage{tikz}
- \usepackage[spanish]{babel}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting PDF file enclose it in a block like this.
-->

```{r include_packages, include=FALSE}
# This chunk ensures that the reedtemplates package is
# installed and loaded. This reedtemplates package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
}
library(reedtemplates)
library(kableExtra)

```

<!--
This is the way to split your thesis into chapters and then include each of the chapters seperately.  You can Knit the Rmd files corresponding to each chapter individually and then put them all back together by Knit-ing this document.

This is an R chunk and chap0.Rmd refers to the Introductory chapter.  Feel free to name this file as something else, but don't forget to change the argument to in `child = ` below!
-->

```{r intro, child = 'chap0.Rmd'}
```

```{r Antecedentes, child = 'Antecedentes.Rmd'}
```

```{r Objetivos, child = 'Objetivos.Rmd'}
```
<!--- Genome Mining-->
```{r capitulo1, child = 'chap1.Rmd'}
```
<!--
Immediately below is the chunk for Chapter 2.
--> 
<!--- EvoMining -->
```{r chapter2, child = 'chap2.Rmd'}
```
<!--- CORASON -->
```{r chapter3, child = 'chap3.Rmd'}
```

<!--- PriA family-->
```{r chapter4, child = 'chap4.Rmd'}
```

<!--- Conclusion -->
```{r chapter5, child = 'chap5.Rmd'}
```
<!--
Add other chunks here for other chapters in your thesis.  Note that if you use the `child =` parameter, you can't include anything else in your chunk.
-->

```{r conclusion, child = 'conclusion.Rmd'}
```

<!--
The bib chunk below must go last in this document according to how R Markdown renders.  More info is at http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
-->

```{r bib, child = 'bibliography.Rmd'}
```

