>fig|2.1421.peg.1252|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPAEVAASAVLCVLVTASLVLALLAMRSPRTGLVAASAGALAAALVLGLALA----GPAS
----RL----VVGYL-----------GLVMVVLAVLGGGSAST---------VVLALATR
GSVPAGAYGGILVPPRGREDD-------------PSAIRRPTREVLRGGATIGMLERLAV
VAVILAGYPEALAVVIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAAVVLV
DR--------
>fig|33013.181.peg.2522|614141
MFVITADQKGSRTDVDRAGTGRDDLASRFEGRLVLPVDRTSGDELQALVADADTALDMAL
VLTRAGHWSVGLGIGTVRTPLPRATREANRPGLHRRARRGRRGEAQRDEVRARGGSACSP
ETRWSGIRPPGLRTPRPRRGRGAHHAAAPGAGPPHLPGLGRRRPHGRREHAAGGRRRARR
HAPGREHAAARQRVARRAGRDPGARRAARPPRRAGDPRCGHRGIRTAIHRRGDALVIPVG
TPGEITAWIALCVLVTAALVLALLTVRAPRTGRVVAAAGTLACALALGLALS----GPAS
----PL----VVGFT-----------GLVAVVLAVLGGGSAST---------VVLALATR
GSVPPGAFGGILVAPRGHEDD-------------ASASRRPTREVLRGGATIGLLERLAV
VAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIFGTLVSWLWAATCAAVVLV
VR--------
>fig|6666666.68540.peg.1115|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------MLVTAALVLALLTVRAPRTGRVVAAAGTLACALALGLALS----GPAS
----PL----VVGFT-----------GLVAVVLAVLGGGSAST---------VVLALATR
GSVPPGAFGGILVAPRGHEDD-------------ASASRRPTREVLRGGATIGMLERLAV
VAVTLAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAAVVLV
VR--------
>fig|2.1425.peg.2772|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----M----VVGFT-----------GLVAVVLAVLGGGSAST---------VVLALATR
GSVPPGAFGGILVAPRGHEDD-------------ASASRRPTREVLRGGATIGMLERLAV
VAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAAVVLV
VR--------
>fig|33013.175.peg.542|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPGEITAWIALCVLVTAALVLALLTVRAPRTGRVVAAAGTLACALALGLALS----GPAS
----PL----VVGFT-----------GLVAVVLAVLGGGSAST---------VVLALATR
GSVPPGAFGGILVAPRGHEDD-------------ASASRRPTREVLRGGATIGMLERLAV
VAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAAVVQV
VR--------
>fig|2.1418.peg.685|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPGEITAWIALCVLVTAALVLALLTVRAPRTGRVVAAAGTLACALALGLALS----GPAS
----PL----VVGFT-----------GLVAVVLAVLGGGSAST---------VVLALATR
GSVPPGAFGGILVAPRGHEDD-------------ASASRRPTREVLRGGATIGMLERLAV
VAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAAVVLV
VR--------
>fig|6666666.374469.peg.2419|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPGEITAWIALCVLVTAALVLALLTVRAPRTGRVVAAAGTLACALALGLALS----GPAS
----PL----VVGFT-----------GLVAVVLAVLGGGSAST---------VVLALATR
GSVPPGAFGGILVAPRGHEDD-------------ASASRRPTREVLRGGATIGMLERLAV
VAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAAVVLV
VR--------
>fig|2.1422.peg.218|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MIAAGLLLVAVG
AVDLLRQMVRSRRWIAFAAAAVALVLVSAALDAVI--AGLLAVAVASIWTWVVPEDGPAR
AGLWPVALLALAAAACVVIAPGRARPGLLGAAWATYSPGNAVSIDVVVLVIGCLVFLLES
GNAVVRIALRSEMGGRVELNTRPVASGTAPVGVDAAAPVAP-APGLKGGRLIGPLERILV
FVLTLTGAYTLLAAVLAAKGIVRFPEISRDRDDGDRAEYFLIGSLVSWVTALAAAFLVWW
GV-----RAG
>fig|6666666.155597.peg.2040|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MAAVLAAVLVAVLAPTALSVAVGGGLVALGLLMGWTWL----HPDR
----PLGVVAVVATV-----------GLVAVLESTLAPAGLRSAPPALTLLAVALALTET
GNRVTRAVLALAGRPADGGDEEAEEPAAEPATVPSAAPTDPTADGLRGGRYIGPMERLLM
VVLGLAQAYPVIAALMAAKGIVRFPEISADRGAGSRAEEFLIGSLASWGLAAAGAVVVWL
ALGLTAPGAA
