>fig|6666666.155597.peg.581|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MSFTIPSIGAGSDLMRLLLRDDGSLAVPPAEPG
SPAAWYANSPSPGQLGPAVLLGHVNATDGSAGVFAHLTDLAPGDTIEVEREDGAVAVFAV
DRGVTYGKDEFPTDEVYGDTEAPELRLITCDG-YNAFTREFEENHIVYATLVDVY
>fig|2.1422.peg.887|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------MLALVGVLACAGCTAASPAAAPASPASIVPPA
SPAPPASTPEAAAAAPAAPAP---PAPSRVVIPALSLDEELIDLGIAADGSMEVPADY--
DEVGWFTSGGRPGGTGPTVIAAHVDSPTGPA-VFVDLENVVVGDVIEVYDDGGTAHAYRV
TETADYPKSAFPTARVFGATAKDELRLITCGGVFDRDAGSYVDNRVVYAERA---
>fig|2.1421.peg.1503|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MGPA-AFARLAELGVGDEVAVQDVDGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGVFDRSVGHYEDNRVVFAEPVG--
>fig|6666666.374469.peg.1208|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------MHHGPADASPARRARRAAVLAGALIPLAALAGCAPAEPETAPAVPPAAVSTE
PSAPSTAAPSARPTTSPTVVQGLGAVPTRVAIPAIDLDQPLIDLGIAADGRMEVPVDF--
DDVGWFTGGGRPGGRGPTVIAAHVDSRVGPA-AFARLAELGVGDEVSVQDVGGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGIFDRSVGHYEDNRVVFAEPVG--
>fig|2.1418.peg.52|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------MHHGPADASPARRARRAAVLAGALIPLAVLAGCAPADPGPAPAAPPAAATAA
PSAPPTTAPSDPPTSAPTVVQGLGAVPTRVAIPAIDLDQPLIDLGIAADGRMEVPVDF--
DDVGWFTGGGRPSGRGPTVIAAHVDSRVGPA-AFARLAELGVGDEVSVQDVGGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGIFDRSVGHYEDNRVVFAEPVG--
>fig|6666666.68540.peg.2215|151744
MRAEGAERVEDARAQGGDGHARGGGELLVAEPGEVHRDDGLAVRVAEAREALDDTQPVER
IRLPRRLLGRLVLGDDARGAGPGAMHVEDHPPLDREQPGAGAAALAVEGGAGAPGAEERL
LHAVLGELAILQGVDREAEQRAPVLRERLAHVEAGRGRAHRAPLGCRGRTRQDERHRDPL
QPRRRVRALTGGYVGRGPGVHRSGGEGPRIAATRVLDGSPRPMNARRPPCVCPVRSGARP
GAPPREAARDDAHETRPEHDHRGRRRGRPRPPRRDARVRRDHRPRAGPLHERVHRDGDAR
PGAQRRRRRDSRRARRDRPLRPPPRLRVEHHLLRHHPHGRDRRVPEPREDGHAHPPGRRR
QGRPAPHRVPEPGGRRERHAHELRLHAGALHHGDHERAGPGHGHGLHGRADRGRPGLVRG
GHPHRVVHGRCRARPADPGAGRRRRHGRRRIRDHDLGPPGRRGRRCRRAGRGRRRADAPP
PGAGVLIPVHHGPADASPARRARRAAVLAGALIPLAVLAGCAPADPGPAPAAPPAAATAA
PSAPPTTAPSDPPTTSPTVVQGLGAVPTRVAIPAIDLDQPLIDLGIAADGRMEVPVDF--
DDVGWFTGGGRPSGRGPTVIAAHVDSRVGPA-AFARLAELGVGDEVSVQDVGGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGIFDRSVGHYEDNRVVFAEPVG--
>fig|2.1425.peg.1469|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MQGLGAVPTRVAIPAIDLDQPLIDLGIAADGRMEVPVDF--
DDVGWFTGGGRPSGRGPTVIAAHVDSRVGPA-AFARLAELGVGDEVSVQDVGGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGIFDRSVGHYEDNRVVFAEPVG--
>fig|33013.175.peg.2780|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------MEVPVDF--
DDVGWFTGGGRPSGRGPTVIAAHVDSRVGPA-AFARLAELGVGDEVSVQAVGGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGIFDRSVGHYEDNRVVFAEPVG--
>fig|33013.181.peg.2455|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------MEVPVDF--
DDVGWFTGGGRPSGRGPTVIAAHVDSRVGPA-AFARLAELGVGDEVSVQDVGGGSTRYAV
TEVADFAKADFPTARVFGAQPTDQLRLITCGGIFDRSVGHYEDNRVVFAEPVG--
