>fig|6666666.155597.peg.464|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------MSTTLQPARTD
VVVPETPAD--ARTVETHPAWLRLKAAATALQPLQVKDGSIPDPADHAAAREHVETIVAA
VEELAPLFPHDAAYLAALPRDFARWADGGFGVPDFLDSLVAFQPQAHRVDGVRHLVVFPM
YTQNGSPDRHVEALVVETIWPEFIAELEAGDYGNRLFVSLRLIDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFQDREAARFRRVVTAAAEVTQLELPAELAELLSSQELAEGTFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYTLEEMRCDMTAFRECVAIERRLTARAAAGEQL
TGLEEQTRRHAGLVQHAVLFDRVFRFALTGSRVRNYDGLGGQLLFAWLHRKDVIQWRDVE
LSVDWDRLADAVVELGDAIDTLYWESIDRPKTVHWLQAYELVASVVTPHPASVWAQGLPR
EVLAGPPKGYTDLVLDDEFPLSMFFEALEKKMSGVIKSTAGIRGTDA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1422.peg.3415|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MTIATPTRA-
--GHELLDGHTVDTVERTPAWTRLKTAATALQALQAKDGSIEDT---AAASPLIDEVIQS
LDALAPLFPHDEAYLAASVVDFRRWRDEGLGVPDFLDSLVAFQPQEHRVDGIRHLVVFPM
YTQNGSSDRHVEALIVEAIWPEFIARLET-EYTNRLFVSLRLVDFTSGYDTNSAVLFPET
VAMREIPTFTWGAIFQDREAARYRRVTRAAADITKLELPAAAARMLDDQALTEQTFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSLEELRCDLTAFRECVSLQARLSLRQTEGAEL
DATEKTMLEHAELVQYAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHRVLHWTDTS
LAFDWDEVPAAVIALADAIDELYWRSIDRPKVAHWLAAYDLVRGVVTPHPASVWARGLSD
EVLAGLPKGYTDAVLDDEFPLSMFFEALEKKMRPVIASTEGIRGTD--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1421.peg.798|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MSSAAAPAAV
IGEPEVVED--VTRVASSPAWLALKDAAVALQPMQAKDGSVPDAAHHAEAARLIAVIRDS
VRALAPLFPHDAAYLAALDVDFARWVDQGLGVPDFLDSLSAFQPQRDRVDGIRHLVVFPM
TTQNGSSSRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREVPTFTWGAIFADREAARFRRVVRHAAEVTKLELPEDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVRIQRRLAAVDPA--ER
TPADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPDA
LPLDGPPKGLTDLVLDDEFPLSMFFEALERKMRDVIGSTAGITGQTA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|33013.181.peg.352|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MEAPHATRTIGGRSMSSAAPTAAV
IGEPEVDED--VATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLLQTIRDA
VRTLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPM
TTQNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPA--ER
TAADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGA
LPLDGPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQARERRRPRGRGRGRV
ERRGSRGLRGADGGGRARRRGRHRRGPARGGRLRAPRGLRPRRPRGRRGAGRPDPRRPRR
RRRPDPPGRRLARRQRARGPDRRRLGLPARAARHHAAQHHARLRRRPAGVRRRPSRHRLV
HGRAAPVPGRRELLDREDRGGDVGARGRPRVLEGRLPRPHDDLRGQGARRPRARARTSGR
EAVDGRAARAGPDRGLTRPLL
>fig|6666666.68540.peg.2539|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MLRGRADPRADPARGTRSRADPADTVEAPHATRTIGGRSMSSAAPTAAV
IGEPEVVED--VATVASSPAWLALKDAAVALQPMQVKDGSIPDAAHHAEAARLIQTIRDA
VRTLAPLFPHDAAYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPM
TTQNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPA--ER
TAADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGA
LPLDGPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1418.peg.1702|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MEAPHATRTIGGRSMSSAAPTAAV
IGEPEVVED--VATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLIQTIRDA
VRTLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPM
TTQNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPA--ER
TAADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGA
LPLDGPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|33013.175.peg.4|614133
MPREMASAQLIFTQNGTDSVSVQPPAAMSASVMTPMVFCASFVPCASETREALPIWPMRK
VRSRPRPARLPMMRHTSQVPTAATAPARIGDMSAGRITLPTTPSSLDPSPAQFTPFSPRP
ASVEPMRPPNSACEELDGRPSSQVSRFQTMPPMRPASTMSSSADPPPWSSAGSGAPDLSW
IFTTAFVTVSATSMLRNAPTRLSTAESVTATLGFNAPVAMDVAIAFAVSWKPLVKSKASA
VMTTSTRRMNGSTAMILRPARVSPLRGTVGFTGCSPAPVEKPAPAAVARTDPEDPHARHP
ARIPGRRADPRRRRARPRRAPGVPDLERVPVPRAVGADGRGRRGAHRRRRLRRPRARGPV
GRGRGIRSRGPRRARRPRGSGRAVRPAPRGGRARSRARRARRAGAHGRRVRLVPARDARR
GADPRRQPGDAPRARARGLREGGALPRRLARGGRRAARVRRLRGAAPRPRVGDHDAGSDG
RRGVALPARARMLRGRADPRADPARGTRSRADPADTVEAPHATRTIGGRSMSSAAPTAAV
IGEPEVVED--VATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLIQTIRDA
VRTLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPM
TTQNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPA--ER
TAADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGA
LPLDGPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|6666666.374469.peg.861|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MSSAAPTAAV
IGEPEVVED--VATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLIQTIRDA
VRTLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPM
TTQNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPA--ER
TAADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGA
LPLDGPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>fig|2.1425.peg.903|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPM
TTQNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPET
VAMREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWD
LIHDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPA--ER
TAADDALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTR
LTIDWDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGA
LPLDGPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
