>fig|2.1422.peg.2253|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MATGGAGFSDEERAAMKQRAEELK-ATK
GLKGAAKLEKENEACLEAIDKLEGVDRAMAERLHVIVLEEAAHLTPKTYYGFPAYAK-DG
KVVVFYQPASKFKTRYGTVSFDDTAQLDDGPMWPVSFAIAEVTAEVEKRIRDAVRRAAPA
A
>fig|6666666.155597.peg.1631|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSESTGFSAAEKAAMAERAEELR----
AQRGGRKKADALQDLLSKIEEMPEPDRALAVTVHRIVTEVAPELAPRTWYGMPAYARGTD
VLV-FLQVSSKFGVRYTTLGFNEGAKLDDGVMWPTSFALTALDDDVRARIADLVRRAVG-
-
>fig|2.1421.peg.1473|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MTDDGGFTKDERAAMKQRAKELREEAK
AQKAADRQAAALQGVLDAHAAMPPEERAIAEWLHGIVLEQAPGLSPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWATSYALTAVDPANEERVAELVRRSVGG
-
>fig|6666666.374469.peg.45|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------MVVGDLLREPGALLVRGGLAGAVHDRLVLLVGAHG
PTVRRPTGVRIRAALVGSPAACHAPGTPPREGADMTDSGFSKDERDAMKQRARELREEAK
LQKAADKQAASLQGVLDAFAAMPPEERAIAEWLHGIVLEHAPDLAPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWPTSYALTAVDPANEERVAELVRRAVGG
-
>fig|6666666.68540.peg.380|151744
MHRPREALALRRREELVLLRVVEVRGLEALLLLVEGGVGHVALPVRLERAEVVLEAGDER
GVLDGRAVEGREEVAHHAAVDVDVLLLGGLARPRREEHVRGLLAGERAAEVVGGAEVGAD
PADARAVGAGAAAEGEHVPALGGELVDQRGSADAGRADHQGRAAGSVGAGGRGGGGRAGG
GHSVLGHPLPQRRGAARAFRAAPRGRVGGSGGVRPVHLGVGLAVDAVAAGGCGLRRRRVG
GLLGEAGVPGAAVEVGGHGLGSAVPVVVGDLLREPGALLVRGGLAGAVHDRLVLLVGAHG
PTVRRPTGVRIRAALVGSPGACHAPGTPPREGADMTDSGFSKDERDAMKQRARELREEAK
LQKAADKQAAALQGVLDAFAAMPPEERAIAEWLHGIVLEHAPDLAPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWPTSYALTAVDPANEERVAELVRRAVGG
-
>fig|33013.181.peg.1894|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------MVVGDLLGEPGALLVRGGLAGAVHDRLVLLVGAHG
PTVRRPTGVRIRAALVGSPAACHAPGTPPREGADMTDSGFSKDERDAMKQRARELREEAK
LQKAADKQAAALQGVLDAFAAMPPEERAIAEWLHGIVLEHAPDLAPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWPTSYALTAVDPANEERVAELVRRAVGG
-
>fig|33013.175.peg.27|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------MRIRAALVGSPAACHAPGTPPREGADMTDSGFSKDERDAMKQRARELREEAK
LQKAADKQAAALQGVLDAFAAMPPEERAIAEWLHGIVLEHAPDLAPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWPTSYALTAVDPANEERVAELVRRAVGG
-
>fig|2.1418.peg.2391|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MTDSGFSKDERDAMKQRARELREEAK
LQKAADKQAAALQGVLDAFAAMPPEERAIAEWLHGIVLEHAPDLAPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWPTSYALTAVDPANEERVAELVRRAVGG
-
>fig|2.1425.peg.875|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MTDSGFSKDERDAMKQRARELREEAK
LQKAADKQAAALQGVLDAFAAMPPEERAIAEWLHGIVLEHAPDLAPKTWYGFPAYADADG
KPVVFFQPGSKFGTRYSTLGFQDPAQLDEGTMWPTSYALTAVDPANEERVAELVRRAVGG
-
