>fig|6666666.155597.peg.246|300756
MKHTFSLRTEWTGDRGSGTSGVRDYDRSVVIQDAAVGEIQASAARPFRGDDSKWNPETLL
LGALAECHVLSYLHVAATSGVVVTGMTCGVEGELEVDGDGAGRFTAITLRPEVTLQDEAD
RERAEALHAEAHRLCFIANSLSAPVAVEPARPDAPPTGTPTLPDHSARLGAPLAVLRPRV
AKRPSRVTGLAQRPTEVEPVMQQEGTPAPVEQVRARDAAAGPAGAAPGTPAAPGQATSFY
DAVGGRPTFDRLTAEFYARVREDEILAPMYPQDDFEGAQRRLLMFLEQYWGGPRTYSEER
GHPRLRMRHAPYRIDPAARDAWLRHMRAAVDTLELSPLHEAELWDYLERAAHSLQNSA--
---------------------
>fig|2.1422.peg.3439|594139
------------------------------------------------------------
------------------------------------------------------------
--MTEPV-----------------------------------------------------
---------------------------------------------------------SFY
EQVGGMDTFRRLVDAFYRGVASDEVLKPMYPEEDPGPAAERLTLFLAQYWGGPTTYGETR
GHPRLRMRHMPFHVDPDARDRWLQHMRVAVDEIALPPAFEAPLWDYLERAAYAMVNTFEP
RGIGPQQDGRPDTGLPVRASD
>fig|33013.181.peg.1864|614141
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ASSFY
DDVGGRPTFERLVREFYRGVADDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVTPTPAT---AGSRTCASPSTRST-----------------------
---------------------
>fig|2.1421.peg.1778|594133
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ANSFY
DDVGGRPTFEKLVREFYRGVAEDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVNPDARDRWLAHMRVAVDSLDLSPLHEAQLWDYLERAAHAMVNTFDE
S--------------------
>fig|2.1418.peg.2176|594099
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ASSFY
DDVGGRPTFERLVREFYRGVADDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVNPDARDRWLAHMRVAVDSLDLAPMHEAQLWDYLERAAHAMVNTFDE
S--------------------
>fig|2.1425.peg.2486|594242
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ASSFY
DDVGGRPTFERLVREFYRGVADDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVNPDARDRWLAHMRVAVDSLDLAPMHEAQLWDYLERAAHAMVNTFDE
S--------------------
>fig|33013.175.peg.1230|614133
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ASSFY
DDVGGRPTFERLVREFYRGVADDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVNPDARDRWLAHMRVAVDSLDLAPMHEAQLWDYLERAAHAMVNTFDE
S--------------------
>fig|6666666.374469.peg.2976|645144
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ASSFY
DDVGGRPTFERLVREFYRGVADDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVNPDARDRWLAHMRVAFDSLDLPPMHEAQLWDYLERAAHAMVNTFDE
S--------------------
>fig|6666666.68540.peg.594|151744
------------------------------------------------------------
------------------------------------------------------------
--MADLL-----------------------------------------------------
-------------------------------------------------------ASSFY
DDVGGRPTFERLVREFYRGVADDPVLVAMYPEEDLEGAIQRLTGFLEQYWGGPTTYSDER
GHPRLRMRHMPFRVNPDARDRWLAHMRVAVDSLDLPPMHEAQLWDYLERAAHAMVNTFDE
S--------------------
