>fig|2.1422.peg.3506|594139
-MAILIDDPQWPAHGRLWAHLVSDSDLAELHAFASAAGIPRRAFDLDHYDVPDERHADLV
AAGAEHVGGKELVRRLRASGLRITARER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RP-GA---------------------------
-----------
>fig|6666666.155597.peg.1781|300756
-MTVLIDPPAWPAHGTVFSHLVSDTSLEELHAFARAAGLSERAFDRDHYDVPAHRRAELV
ARGAVPVTGRELVRRLAASGLRVPARSRAEKRDVVLARRWARLFEGTAASPDAVTTAGRD
LLARWAEPHRHYHDPAHLLAVLESVDLLERAGAETGPDPRAVRLAAWFHDAVYAGDPTAP
AGQDEADSAALAREVLTDPRLAVPADVVDEVARLVLLTAAHDPAPHDAAGAVLSDADLEV
LGRSPEAYARYVAAVRRDYAHVSDADWARGRGAVLDALLDAGRLYRTAPGRARWEAAARR
NLAAERAALSA
>fig|2.1421.peg.893|594133
-MAVLLDRPAWPAHGTLWSHLVSDASLEELHAFARAAGIPERGFDRDHYDVPAARYEELV
ARGAVPVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGG---------------------------
-----------
>fig|33013.175.peg.1022|614133
MMSVLLDRPAWPAHGRLWAHLVSDVSLEELHAFARAADIPERAFDRDHYDVPEERHAELV
ARGAVAVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGS---------------------------
-----------
>fig|33013.181.peg.2856|614141
MMSVLLDRPAWPAHGRLWAHLVSDVSLEELHAFARAADIPERAFDRDHYDVPEERHAELV
ARGAVAVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGS---------------------------
-----------
>fig|6666666.374469.peg.2941|645144
MMSVLLDRPAWPAHGRLWAHLVSDVSLEELHAFARAADIPERAFDRDHYDVPEERHAELV
ARGAVAVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGS---------------------------
-----------
>fig|6666666.68540.peg.627|151744
---------------------MSDVSLEELHAFARAAGIPERAFDRDHYDVPEERHAELV
ARGAVAVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGS---------------------------
-----------
>fig|2.1418.peg.2143|594099
---------------------MSDVSLEELHAFARAADIPERAFDRDHYDVPEERHAELV
ARGAVAVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGS---------------------------
-----------
>fig|2.1425.peg.1769|594242
---------------------MSDVSLEELHAFARAADIPERAFDRDHYDVPEERHAELV
ARGAVAVSNRDLVRRLQASGLRVTQRER--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RGLGS---------------------------
-----------
