>fig|6666666.155597.peg.2042|300756
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--MIPHDDGAAGPGAGLRLVLGSASPGRAEVLTRARVPFRVVVSGVDEAAVGAAA----G
DPSPAE-LAGLLAEAKGRDVAARVAAAGVEAPTLVLGCDSVFEFEGRAHGKPYEPEVAVE
RWRAQAGREGVLHSGHWLGLVLPEPGAGSGVAAEAGVVSAVVRFGA-VTEAEIQAYVATG
EPLHCAGAFTVDGAGAALVDGVDGDPNAVIGLSVAWLRRATAALGQDFTRLWEPSNAQR-
---
>fig|2.1422.peg.1019|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MRVCLASTSPARLMLLRQAGIEPEARSPQVDEEAVIAEVEATEA
RRLPAPEHVLLLARRKAADVAHRLRAEEPDFDGFVIGGDSMFALGDEILGKPYTPDAATA
RWRGMRGRTGVLHSGHS----VFRLSPGSEPREAHAVAEAAVTFAGDVDDAEIAAYVATG
EPLLVAGAFTVDSLGGAFIERVDGDPSTVVGMSLSTVRRLVRELGGSWTELWNRS-----
---
>fig|2.1421.peg.2044|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MVRVREQVERPDGAELVAALGEQGHVA
GERDGVARHVDDLRGTQLGERVDDGLLGTGARRVEDDGRALQPAALRGARLAHEVLEVAV
DAGGQRRGPHPLRQVVAGELGGDLVALHARDAHGVAEAVAHGGRQQPDAPVEVEVRGARV
EEGLVDRGLDGVVQRLGRAAVHLPEAAGLQLELPVAHALGDGVATLRLAVDEEHAHVAVR
RGDQVDPLDAGEALAEGRRAVDARGGEGQRLDGDHAVRARGVRTHAAVAVDVQADARAPA
EAVRLVVAGERPDLDLAVDARHAGQGVDDDPALELALVRQVDVAELGAADPVLGRAVDRG
LGPHVRTAVRGGVQHLDRVGAPEGLLGVLRDARAHPLAGDRVRDEDHPAVVPGDGDSPVR
DVGHVHLDLAAHLLTHAATLTHAGTPGRRSRS----------------------------
--RRHLGRACHDDPMTTRLHLASTSPARLALLRSAGVEPVVLHSDVDEPAAVAAAEAAHG
-PLAPEEMVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDGVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADIDDDEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGVAWPDLWNRPGAVAA
RLV
>fig|33013.175.peg.2130|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------MVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAA
RLL
>fig|33013.181.peg.1987|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------MVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAA
RLL
>fig|2.1418.peg.1237|594099
MEHVALAPAELGLREVAVRVDGGRPLQVVEHVAACDGGDGRHDGLRGRRLGDHPGGTGGQ
RLADARDAVGDAVDEHRGTRALRGLDVVGDGGSVPQREVEDDHVALPADQALDELAGVRG
REDELEPGVEARGLEAEPHRLVVVDDGDADGRTAFGHLIGSLRGLGHPDPPRRVVPSSSD
DRLAHCIARLPRPLGGGCPRSGGGGHQHGHALDVVGVREEVERTHRAELVAALGEQRHVA
GQRDGIARHVDDLSRAQLGERVDDGLLGAGARRVEHDGRRLQATALGGARLADEVLQVAV
DARRERRGAHPLRQVVAGELGRDLVALHARDPHGVAEAVAHGGGQQADTAVEVEVRGARV
EEGLVDGGLHGVVERLGRAAVHLPEAARLELELAVVDALGDGVAALRLAVDEEHAHVAVG
GGDEVDPLDAGEALPEGRRAVDAGGGERQRLDGDHPVRARGVRADQAVVGHVQADARAPA
EPVGLIVAGERLHLDVHVDVRHAGERVDHDLPLELALVGEADVAELGAADAVLGGAVDGG
LGPDVRAAVRRRVEHLDRVGAPERLLGVLGDARPHPLAGDRVRDEDHPAVVPGHGDPSVR
HVRHVHLDLAAHLLTHPATLTHAGAARTHTRQRTAPLTHAGAARTHTRQRTAPLTHTGVS
PGRADAARACHHVGVTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAA
RLL
>fig|2.1425.peg.1839|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAA
RLL
>fig|6666666.374469.peg.292|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAA
RLL
>fig|6666666.68540.peg.140|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVA-GAPLTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHW----LIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATG
EPLLVAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAG
RLL
