---
title: "ProteinGel"
author: "NellySelem"
date: "May 18, 2017"
output: pdf_document
---
## Protein Gel   

grosor del gel.75  
fijarse concentracion acrilamida
pero la mayoría eluyen al 60% de imidazol 500mM
Se pone primero el gel separador, y se le agrega el alcohol  isobutanol  
Despues de media hora se tira el alcohol, se lava con abundante agua se tira el agua volteando el gel, y finalmente sin tocar el gel se seca con una sanita,   
Se agrega el gel cargador, se coloca el peine sin dejar burbujas.  

18ul vol final de pozo  
16 $\mu l$ muestra por $4 \mu l$ buffer carga morado  
heat at 95C by 5 min  
10 $m ul$ marcador de peso molecular
Note it is useful to take a picture of the hole content , to keep track of the muestra.    
  
### COOMASSIE COLOIDAL  
Todos los reactivos deben agregarse poco a poco al agua en el orden indicado  y esperar a que se disuelvan antes de agregar el siguiente.
- 650ml  de H2O  
- 100g de sulfato de amonio  
- .4g Coomassie G  
- 30ml de Ácido Fosfórico (en el cuarto de quimica, mucho cuidado con este ácido es muy fuerte, si se tira un acido echarle cal)  
- 200ml de Etanol  
- Ajustar con H2O a 1 L  
Nota: El Etanol debe agregarse poco a poco para evitar precipitación de sales  
tubos amicon de 10000 kDa    
