---
title: "ProteinExpression"
author: "NellySelem"
date: "May 18, 2017"
output: pdf_document
---
## Expression of assay enzymes yTrpD, tmTrpC, ScoePria, D11PriA  
### Expression of plasmid on cell cultures  
1. Cell preparation. Prepare chemically competent (Calcium)  
-Rosseta 2 (for TrpD)  
-C41 pGROEL/ES  or V69 (for TrpC)  
-V69(for Scoe PriA and D11A)  
  
2. Transformation  
use plasmids   
-pET28_ytrpD (kanamycin resistant) on Rosseta 2   
-pQEI_tmtrpC (Ampiciline resistant) on PGROEL/ES,  
-Scoe and D11 v68 transformed cells V69 are available.    
  
3. Incubation. Incubate 1Lt culture at $37^{\circ}C$ with correspondent antibiotic (Bacteria previously streaking on petri dish, and an over night pre-inoculation $37^{\circ}C$)  
Note: Addition L-Arabinose to pGROEL/ES_ pQEI_ tmtrpC 

4. Induction. Once $0.6-0.8 OD$ at $600nm$ is reached, induce culture with IPTG $.5 mM$  and incubate overnight at  
-$-20^{\circ}C$  (Rosseta 2 and C41 pGROEL/ES)  
-$-16^{\circ}C$ degrees  (V68 cells)  
IPTG cold $1M$ $500\mu l$ p/flask $1L$   

IPTG stock: Calculate IPTG grams at $1M$ on a final volume of $10 ml$  
```{r IPTG}
  IPTG_con_fin=1 ## M
  IPTG_vol_fin=10 ## ml H_2O Filtrado con filtro .22
  IPTG_mw=238.3 ##g/mol
```
` r $C_F= IPTG_con_fin M$ `
$V_F= ml$ = $V_F=0.2 L$ , $mw=121.14\frac{g}{mol}$  
  
$Molaridad\times Volumen$ = $\frac{gramos}{peso molecular}$  
x gramos = (`r IPTG_con_fin `M)(`r round(IPTG_vol_fin/1000,digits=2)` L) `r IPTG_mw` $\frac{g}{mol}$=`r IPTG_mw*IPTG_con_fin*IPTG_vol_fin/1000` g = `r IPTG_mw*IPTG_con_fin*IPTG_vol_fin` mg   

