---
title: "ProteinPurification"
author: "NellySelem"
date: "May 18, 2017"
output: pdf_document
---

## Purification 
TrpC and TrpD will be purified by Nickel chromatography using AKTA-FPLC while ScoePriA and D11A purification will be done by Nickel chromatography using vivapure columns  

### Centrifugation
1. Centrifuge on $.5L$ cans  (Cans as big as possible)  
rotor that suits for cans (On $.5L$ cans rotor code is 03)  
Karina: velocity $6000 rpm$  Time $10 min$
Ana: $7000rpm$ for $10 min$
At this point experiment may be interrupted and pellet can be stored at $-80^{\circ}$ on Falcon tubes or better run the essay the same day.  

To restart this protocol re suspend pellet on $25 ml$ lysis buffer keeping on ice all the following steps.  
  
### Sonication
We sonicate pellet to disrupt cells and get the proteins. All reactives must be cooled previously and kept on ice.  The sonicator must touch the falcon tube. Falcon must be kept on ice.
  
Add fresh components to Lysis buffer:  
-Add proteasas inhibitor mix $2\mu l$ (Protein Box)  
-Add DTT $.1 25\mu l$  
-Karina: Add Lysozyme $\frac{2mg}{ml}$  $100\mu l$  
-Ana: Add Lysozyme $\frac{10mg}{ml}$($1000X$)  $100\mu l$ 
  
2. Resuspension. Add lysis Buffer $25ml$ to resuspend pellet and put test tubes on an small glass ware with ice  

3. Sonication. After buffer addition sonicate:       
$7$ times sonication $20s$ with $1min$ rest between every sonication cycle.    
Only total time of sonication must be entered on sonicaction device ($140s$).  

4. Centrifugation. After sonication centrifuge on refrigerated centrifuge at 4°C  $25 min$ at $8000 rpm$  
 


5. Inject into AKTA-FPL previously balanced with Buffer A   (or vivapure balanced with bufferA)  
When vivapure is being used, the supernatant must be filtered on .45 $\mu l$ filters to avoid column damage.  

6. Wash with 5% Buffer B and subsequently with an imidazol gradient (Buffer B) from 5% to 60% on 16 vol of the column with a flux of 1ml/min. Conserve each elution tube properly labeled.  2000rpm 5 min  
What we did to purificate Scoe PriA  was an imidazol gradient:  
  
Flask each one with a 100ml were prepared. columns were washed with 20ml of this tubes at 2000rpm 5 min  
Imidazol concentration=x  
v: (x=)100ml/500mM    

\label{my-label enzyme}
\begin{tabular}{ l l c c l}
\hline \\ [-1.5ex]
Flask & BufferB (mM)   & BufferB (ml)  & Buffer A ml & Buffer B  \\  [1ex]
\hline \\ [-1.5ex]
1 & 50& 10&  90& 10 \\  [1ex]
2 & 100& 20& 80& 20 \\  [1ex]
3 & 150& 30& 70 & 30 \\  [1ex]
4 & 300& 60& 40 & 60 \\  [1ex]
5 & 500& 100& 0& 100 \\  [1ex]
\hline
\end{tabular}

Flask must be ketp cold.  

7. Recover the fractions that contains the protein that elutes approximately at 150-200 mM imidazol. (TrpC, TrpD) or 300mM imidazol (must PriA). Collect the relevant fractions. At this point a protein gel can be run to check protein elution.

8. Concentrate the protein using AMICON tubes 10kDa (all molecules below this weight will be discarded, molecules with weight above 10kDa such as PriA will be kept inside the tube) until an approximate concentration of $90 \frac{\mu g}{\mu l}$ ($1ml$ vol approx). Because imidazol>200mM reacts with Bradford, protein on amicon must be washed with 10 ml of buffer A to eliminate imidazol (4ml each time on amicon tube). Finally, after protein concentration, 100 ul sample must be recovered with 900 ul Buffer A (free of imidazol) 
(8000 rpm 10 min)
when AMICON are stored for long periods leave on ethanol at 20%, to reuse them throw ethanol out and wash many times with miliQ water.


9. Check purity by SDS-PAGE gel    
on _S coelicolor_ PriA molecular weight is around 25.7 kDa (length 240 aminoacids), 
on _T maritima_ TrpC molecular weight is around 27.5 kDa (length 242 aminoacids)

10. Add glycerol at a final concentration of 15% and quantify using Bradford. Store at -80C


_TrpC important before step 5_  
After centrifuge step 4 :    
Heat supernatant by 15 min at 65C  
Centrifuge at 10000rpm by 20min. Recover the supernatant.  

Continue with steps 5-10 as in trpD purification.  

On protein activity is more important to be pure than to have protein abundance.  
