---
output: pdf_document
---
  ---
title: "TrpF_kinetics"
author: "NellySelem"
date: "May 18, 2017"
output: pdf_document
---


## Process data
```{r include_reedtemplates_TrpFkinetics, include = FALSE}
# This chunk ensures that the reedtemplates package is installed and loaded
# This reedtemplates package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```

```{r load_pkgs_TrpFkinetics, message = FALSE,echo=FALSE}
# List of packages required for this analysis
pkg <- c("dplyr", "ggplot2", "knitr", "devtools","RColorBrewer")
# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]
# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
# Load packages
library(dplyr)
library(plyr)
library(reshape) ## melt
library(ggplot2)
library(knitr)
library(RColorBrewer)
hm.palette <- colorRampPalette(rev(brewer.pal(11, 'Spectral')), space='Lab')  
library(genstats) ## Next libraries are for coursera
library(devtools)
library(Biobase)
library(scales) # 
library(xlsx) # For save data on excel
library(knitr)
library(drc) # for fitting Michaelis Menten model
library(ggplot2) # for drawing
```


```{r Cinetics}
#First I saved file as scv tablar separated    
#perl -p -i -e 's/,/\t/g' Pra_scoe1.csv   
#An cut it to obtain just data  
#tail -n +39 Pra_scoe1.csv | head -n-3 > Pra_scoe1.data  
#perl -p -i -e 's/\sNr\.|\s\[\w*\]|\.\s\[.*\]//g' Pra_scoe1.data
#tablePRA <- read.table("chapter2/cineticas/Pra_scoe1.data",header=TRUE, sep="\t") 
tablePRA <- read.table("cineticas/05062017_Pra.data",header=TRUE, sep="\t") 

## visualising full data
tablePRA$Temp<-NULL
tablePRA$Cycle<-NULL

PRAassay.m <- melt(tablePRA,id="Time")
plot(PRAassay.m$Time, PRAassay.m$value, col=PRAassay.m$variable,  xlab="Time [s]",ylab="Fluorescence", pch=19,bty='L')
par(xpd = TRUE)
legend("right", legend = rev(unique(PRAassay.m$variable)), col = rev(unique(PRAassay.m$variable)),pch=19,bg="white")

```

```{r FluorescenceRelhgfativeUnits}
## getting Units of relative fluorescence before adding PriA
AA_Con<-rev(c(1.25,2.5,3.75,6.25,10,20,37,62))
#AA_Con<-rep(c(0,1,5,10,50,100,150,200))

## at time 196.2, when all AA is converted fluorescence data where
Fluor<-c(15062,5047,2839,1723,1115,766,579,401)

## the next function calculate the mean fluorescence on n columns, when every n consecutive entries of this vector have the same AA concentration  
meanVector <- function(argument1,n){
  m=n-1  ## n is the number of adjacent same concentration (numebr of columns)
  resul=rep(0,8) ##repite 0 8 times
  for (i in 1:8) {
    for (j in 0:m) {
      #print(c(i,j))
      resul[i]=resul[i]+argument1[n*i-j]/n
      }
    }
    return(resul)
  }

AA_mean<-meanVector(AA_Con,1)
Fluor_mean<-meanVector(Fluor,1)

## remove last element it was too divergent
#AA_mean=AA_mean[-length(AA_mean)]
#Fluor_mean=Fluor_mean[-length(Fluor_mean)]
## remove firste element
AA_mean=AA_mean[-1]
Fluor_mean=Fluor_mean[-1]
#AA_mean

UFR.lm = lm( Fluor_mean ~ AA_mean) 
coeffs = coefficients(UFR.lm); coeffs 

b=coeffs[1]
m=coeffs[2]

UAR_interpol = function(x){x*m+b}
## since all AA is converted to PRA we set x axis as PRA uM
plot(AA_mean, Fluor_mean, ylab="URF",xlab="PRA uM", pch=19)
par(new=TRUE)
plot(UAR_interpol,yaxt="n",xaxt="n",xlab="",ylab="", 1,200)

AAcon = function(y){(y-b)/m}
AAcon(30000)

PRAassay2<- AAcon(tablePRA)
PRAassay2["Time"]<- tablePRA["Time"]

### End selection of columns
PRAassay2$Cycle <- NULL
PRAassay2$Temp <- NULL


PRAassay2<-PRAassay2[, !(colnames(PRAassay2) %in% c("C62uM"))]
PRAassay2.m <- melt(PRAassay2,id="Time")
plot(PRAassay2.m$Time, PRAassay2.m$value, col=PRAassay2.m$variable, xlab="Time", ylab="URF PRA uM",pch=19)
par(new=TRUE)
legend("right", legend = unique(PRAassay2.m$variable), col = unique(PRAassay2.m$variable), pch=19,box.lwd=0, bg="white")
##

```

```{r slopes}
 ##pendientes (slopes) of linear part of the curve
# time when TrpF is added
cuttime<-344.2
maxtime=620

PRAassay2Time<-PRAassay2[which(PRAassay2$Time >= cuttime & PRAassay2$Time <= maxtime),]

## removi columnas que se salian del margen de medicion
PRAassay2Time<-PRAassay2Time[, !(colnames(PRAassay2Time) %in% c("C62uM"))]

# vector with slopes for each dataset
V0 <- apply(PRAassay2Time, 2, function(x) coefficients(lm(x ~ PRAassay2Time$Time,na.action=na.omit))[2])

PRAassay2Time.m <- melt(PRAassay2Time,id="Time")
plot(PRAassay2Time.m$Time, PRAassay2Time.m$value, col=PRAassay2Time.m$variable,xlab="Time", ylab="URF PRA uM", pch=19, xlim=c(cuttime-50,maxtime+50),bty='L')

V1 <- apply(PRAassay2Time[,2:ncol(PRAassay2Time)], 2, function(x) coefficients(lm(x ~ PRAassay2Time$Time,na.action=na.omit)))
apply(V1, 2, function(x) {abline(x, col = PRAassay2Time.m$variable)  })
par(xpd = TRUE)
slopeText2="m ="
slopeText<-paste(slopeText2,rev(round(V0[-1],digits=6)),rev(names(V0[-1])))
legend(450,100, legend = slopeText, col = rev(unique(PRAassay2Time.m$variable)), pch=19,box.lwd=0, bg="white")

## get relevant velocities and get correspondent concentrations
## V0 or slopes are on [PRA]uM/s 
# slopes stores the slope, with TRUE , FALSE the desired enzyme can be selected, One more than one is tested on a plate always check if it is the desired one.
slopes=(round(V0[-1],digits=6))[c(TRUE)]
concentration<-as.matrix(PRAassay2Time[1,names(slopes)])
#slopes
#concentration
slopes=as.matrix((round(V0[-1],digits=6))[c(TRUE)])
row.names(slopes) <- NULL 
slopes<-c(slopes)## plot on r base

slopes
# in concentration I stored the inital substrate concentration  
row.names(concentration) <- NULL 
concentration<-c(concentration)
slopes
concentration
```

```{r interpolar michaelis-menden}
## interpolar michaelis-menden

#https://rpubs.com/RomanL/6752
#https://davetang.org/muse/2013/05/17/fitting-a-michaelis-mentens-curve-using/
#S <-concentration
## from highest to lower concentration
S <-AA_Con
#S<-S[-length(S)]
S<-S[-1]
v<-slopes
#v<-slopes[-length(slopes)]
#v <-slopes[c(TRUE,FALSE)]
v<--1*v
S
v
mm <- data.frame(S,v)                                                                                 
model.drm <- drm(v ~ S, data = mm, fct = MM.2())
summary(model.drm)
## first value equal km
## second value = vm
Km=coefficients(model.drm)[1]
Vmax=2*coefficients(model.drm)[2]
Enzyme=2.5 #2.5uM
Kcat=Vmax*Enzyme  
Km
Vmax
Kcat
mml <- data.frame(S = seq(0, max(mm$S), length.out = 100))
mml$v <- predict(model.drm, newdata = mml)


## plot on r base
plot(mm,log='',xlim=c(0,max(mm$S)), ylim=c(0,max(mm$v)), xlab="Reads", ylab="Transcripts")

##plot on ggplot
ggplot(mm, aes(x = S, y = v)) + theme_bw() + xlab("Concentration [uM]") + ylab("Speed [d[PRA]uM/s]") + ggtitle("Michaelis-Menten kinetics") +  geom_point(alpha = 0.5) + geom_line(data = mml, aes(x = S, y = v), colour = "red")

ggsave("mm.pdf", width = 6, height = 4)
```

