>fig|33013.175.peg.2795|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MTETDTAPAS--------------------
---------------RERRSGPGRRIARPLAVATALALGLSALVASPAEAATVAIADVQG
TGSATPFAGRVVTVEGV------------VTADYRGASGYAGIVIQTPGSG---------
------------------------------------------------------------
-----------------GATDQTPGASDGIF---VYLASADPAVAIGDLVRVTGTASERQ
GQTQLAATATDLVRAGVGVPAATPLPDTLRGADRESLESMLVTPTGDYRVGSAHQLDTFG
TLWLSAGADLPVKATDVVRPG--AEADPLDDAAWSRLVRNTARAAEITRAAGFEPTFHHH
AGTFVESPEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAEL
GRVLAAGGGMREVWSSGAFVAFGLGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIR
GFRAERTEDQRVNREALRTWA
>fig|2.1425.peg.312|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------MFQFGW------GASLI------------------------------
--------GLE--------------------------------------------SSGPI
LSFLP----------------------------------------EITRAAGFEPTFHHH
AGTFVESPEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAEL
GRVLAAGGGMREVWSSGAFVAFGLGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIR
GFRAERTEDQRVNREALRTWA
>fig|6666666.374469.peg.500|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPL----------SDDDAFQASLPELAASLRVFQEAAESGPT
RLPLPTLADAG-SATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITRAAGFEPTFHHH
AGTFVESPAEIDRFLDAVDVGLTLDTGHLVIAGGDPLAAISRWGARITHLHLKDVDAAEL
RRVLAAGGGMREVWSSGAFVAFGRGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIR
GFRAERTEDQRVNREALRTWA
>fig|6666666.68540.peg.2866|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MRGSDAVVARGRHEHALERLAVGAAERVGQRGGGGHADAGPHEVR
RGRGELGLALALGRGARDADEVADRDGRVGAREVDEDPVGGAGRLVGRAAGARGLDHDAG
IPARPAVVGGDDALDRDDATGERGRAAGALHVGDGDGRGLGGRRDERGQAERQGGRDGER
AGDAAPRAGSALSGCGCGVGLGHGVVPLGVAVPPRGGSPVERRPGATPGGGPPPDRHRLV
TRSSRHAGAGRPARWRGTAATYYRQDKHPPYGPRSSATPHGPDPHHPRIPRRLDGPPEPT
RGIRRVRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPL----------SDDDAFQASLPELAASLRVFQEAAESGPT
RLPLPTLADAG-SATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITRAAGFEPTFHHH
AGTFVESPEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAEL
GRVLAAGGGMREVWSSGAFVAFGRGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIR
GFRAERTEDQRVNREALRAWA
>fig|33013.181.peg.1941|614141
MACAASAAACSLRAATSTARTSSMSDSSAGAGSAPAWLKISVWSLKIISVGMAEMFACCA
RNCCDSVSTLPWTMSACFSLDLSKTGANCLQGPHQSAQKSTTTMPLESTMLSKFSAVSSV
VAMVRPLLVLGSCGLGVQPGARPAHSASGRRLPDEDDRRPDGARPLRLVVARVARGEQVD
PAGQARQRHGRAAGVGRRDVDGGDRAAPVEDLHAAGRSRRAGGELHRVPHRLPAADEQAV
GVPDEGRRVADRVEADLHGVVVARAEGAGSVRRGPAVLARGPLRCVDVPDADARDRGGAR
AGGEHVVERSDLAVERVRALAGRLRGHEVDEAGVTEDLDRVLLRVGVEVAEEVDEVGSAR
RLELAREARDGLRLRDAVGVEEPLAVGRLRSGPGLRLEVVRDHREGPVAAAEGLRDGLAR
VAPDRLVDLRGRLAHGRHGVRAVDDRVLDLVGRRRLQLGGRAHVVPHGLPRGVVEAAHEV
GRRGVRRLAEARRVLDLHQRHDLRVEAGDGRDDLRALLPELLRGGGAALPERREVVEDVE
PGDADVAAHLGRGRRTRVPAREGRHAAGRVERRERRRGLEAPVVEAVGEHVRDGREDRDV
AVADHAVGRVVGLRRARGIGRVRELDVVAVVEQEPARAVVGGDPVGLGARPHDVGGLDGQ
IRAGAQPERAEGVELVRGSDAVVARGRHEHALERLVVGAAERVGQRGGGGHADAGPHEVR
RGRGELGLALALGRGARDADEVADRDGRVGAREVDEDPVGGAGRLVGRAAGARGLDHDAG
IPARPAVVGGDDALDRDDATGERGRAAGALHVGDGDGRGLGGRRDERGQAERQGGRDGER
AGDAAPRAGSALSGCGCGVGLGHGVVPLGVAVPPRGGSPVERRPGATPGGGPPPDRHRLV
TRSSRHAGAGRPARWRGTAATYYRQDKHPPYGPRSSATPHGPDPHHPRIPRRLDGPPEPT
RGIRRVRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPL----------SDDDAFQASLPELAASLRVFQEAAESGPT
RLPLPTLADAG-SATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITRAAGFEPTFHHH
AGTFVESPEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAEL
GRVLAAGGGMREVWYSGAFVAFGLGDVDLASVMTAIEAQGSDGWVVVEQDVLNAPDADIR
GFRAERTEDQRVKREALRTWA
>fig|2.1418.peg.1435|594099
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------MD
PAGQARQRHGRAAGVGRRDVDGGDRAAPVEDLHAAGRSRRAGGELHRVPHRLPAADEQAV
GVPDEGRRVADRVEADLHGVVVARAEGAGSVRRGPAVLARGPLRCVDVPDADARDRGGAR
AGGEHVVERSDLAVERVRALAGRLRGHEVDEAGVTEDLDRVLLRVGVEVAEEVDEVGSAR
RLELAREARDGLRLRDAVGVEEPLAVGRLRSGPGLRLEVVRDHREGPVAAAEGLRDGLAR
VAPDRLVDLRGRLAHGRHGVRAVDDRVLDLVGRRRLQLGGRAHVVPHGLPRGVVEAAHEV
GRRGVRRLAEARRVLDLHQRHDLRVEAGDGRDDLRALLPELLRGGGAALPERREVVEDVE
PGDADVAAHLGRGRRTRVPAREGRHAAGRVERRERRRGLEAPVVEAVGEHVRDGREDRDV
AVADHAVGRVVGLRRARGIGRVRELDVVAVVEQEPARAVVGGDPVGLGARPHDVGGLDGQ
IRAGAQPERAEGVELVRGSDAVVARGRHEHALERLAVGAAERVGQRGGGGHADAGPHEVR
RGRGELGLALALGRGARDADEVADRDGRVGAREVDEDPVGGAGRLVGRAAGARGLDHDAG
IPARPAVVGGDDALDRDDATGERGRAAGALHVGDGDGRGLGGRRDERGQAERQGGRDGER
AGDAAPRAGSALSGCGCGVGLGHGVVPLGVAVPPRGGSPVERRPGATPGGGPPPDRHRLV
TRSSRHAGAGRPARWRGTAATYYRQDKHPPYGPRSSATPHGPDPHHPRIPRRLDGPPEPT
RGIRRVRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPL----------SDDDAFQASLPELAASLRVFQEAAESGPT
RLPLPTLADAG-SATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITRAAGFEPTFHHH
AGTFVESPEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAEL
GRVLAAGGGMREVWSSGAFVAFGLGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIR
GFRAERTEDQRVNREALRTWA
