>fig|33013.175.peg.1302|614133
MDLTLIVVLVIALALFFDFTNGFHDTANAMATPIATGALKPRVAVAIAAVLNLVGAFLST
EVAKTVSGGIIREGDGGVQITPTMIFAGLMGAIVWEPRDLAPRPPVELEPRAVRRPHRRG
RRGRGPRLGRLRRRAVEGDPPGAARPRDRRPHRVHDHQARLLDHAPLERPERARRLPLRP
DLHVVAR-GPRARHQRRAEDHGHHHPHAHRGRLPGGRLRP--------------RVLGHR
RVRGRHRARHVHGRLADHPHDGIRPHRGQARAGLQRGGLHRGHDPGVQPPRLRALDHAGR
LGISHRLGPRPPRRVRALEHGGQDRARLAADAAVGRHRGRGRGVHREHRHGRLRHRRGRR
RRGHRLDLLALAPERGRRPQRHRRGRRRRIRGARTQGHQGRPEGQGGRMIDWSAFLVVAV
AALVGAVAVVCLFSLGVRLLAVGTEYDDEGDKVSVTGIRPQAATVGGYVCFALSGLAVLY
GVYLIVPALHS
>fig|33013.181.peg.1316|614141
-----------------------------MATPIATGALKPRVAVAIAAVLNLVGAFLST
EVAKTVSGGIIREGDGGVQITPTMIFAGLMGAIVWNLVTWLRGLPSSSSHALFGGLIGAA
VVGAG----------LGSVDFGVVLSKVILPALLAPAIAGLIAYTTTKLAYSITRRSSGP
NERGGFRYGQIFTSSLVALAHGTNDAQKTMGIITLTLIAGGFQAAGSGPAFWVIAVCAVA
IALGTYMGGWRIIRTMGSGLTEVKPAQGFSAEASTAATILASSHLGFA---LSTTQVASG
SVIGSGLG---RRGACALEHGGQDRARLAADAAVGRHRGRGRGVHREHRHGRLRHRRGRR
RRGHRLDLLALAPERGRRPQRHRRGRRRRIRGARTQGHQGRPEGQGGRMIDWSAFLVVAV
AALVGAVAVVCLFSLGVRLLAVGTEYDDEGDKVSVTGIRPQAATVGGYVCFALSGLAVLY
GVYLIVPALHS
>fig|6666666.68540.peg.1205|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MIDWSAFLVVAV
AALVGAVAVVCLFSLGVRLLAVGTEYDDEGDKVSVTGIRPQAATVGGYVCFALSGLAVLY
GVYLIVPALHS
>fig|2.1418.peg.596|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MIDWSAFLVVAV
AALVGAVAVVCLFSLGVRLLAVGTEYDDEGDKVSVTGIRPQAATVGGYVCFALSGLAVLY
GVYLIVPALHS
>fig|2.1425.peg.1080|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MIDWSAFLVVAV
AALVGAVAVVCLFSLGVRLLAVGTEYDDEGDKVSVTGIRPQAATVGGYVCFALSGLAVLY
GVYLIVPALHS
>fig|6666666.374469.peg.2324|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MIDWSAFLVVAV
AALVGAVAVVCLFSLGVRLLAVGTEYDDEGDKVSVTGIRPQAATVGGYVCFALSGLAVLY
GVYLIVPALHS
