>fig|6666666.68540.peg.778|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------MTDNVAVKIVPRTERSRGEAEILALQAVTSDHVVELRDVATLSDGSL
CIVQSLGTRGTAAALLGRRGTLTPGETVTLVASVLRGLGDLHDVGIAHGAVDLTHVVIDA
TGRPLLGGLGSSRLVAGEAGEEGIRGVDPVDQDLGRVARIVQALRDPGDAHGRASNDRWL
AWLALLDGTIHGESDLSAHDLADRLLDVADAAPLADAGAARHEEDADRALSHGAIPLDAR
PDTVSGRAEHATGPRRAPRPFSRSHGSAHRRHRAARAAWAHDVDARLTSVRSELVSVRPR
IWALGASALLLLIAGVVAVPLLTGPDRGATEVRTSTPSTAAPADAGFDVDASPAPDGDAS
PGPDADAARSPDPDIAAPALLRLRAACLHNADAACVSDVDEAGSAVDDADRSTIASGGSA
SPEGAALHVDDALGPARRLGDTALFELRPGSDTPAARAAESAPERRPASLLIVRGEAGWR
IRDLMDDR
>fig|33013.181.peg.2664|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------MTDNVAVKIVPRTERSRGEAEILALQAVTSDHVVELRDVATLSDGSL
RIVQSLGTRGTAAALLGRRGSLTPGETVTLVASVLRGLGDLHDVGIAHGAVDLTHVVIDA
TGRPLLGGLGSSRLVAGEAGEEGIRGVDPVDQDLGRVARIVQALRDPGDAHGRASNDRWL
AWLALLDGTIHGESDLSAHDLADRLLDVADAAPLADAGAARHEEDADRALSHGAIPLDAR
PDTVSGRAEHATGPRRAPRPFSRSRGSAHRRHRAARAAWAHDVDARLTSVRSELVSVRPR
IWALGASALLLLIAGVVAVPLLTGPARGATEVRTSTPSTAAPADAGFDVDASAAPDGDAS
PGPDADAARSPDPDIAAPALLRLRAACLHHADAACVSDVDEAGSAVDDADRSTIASGGSA
SPDGAALQVDDALGPARRLGDTALFELRPGSDTPAARAAESAPERRPASLLIVRGEAGWR
IRDLMDDR
>fig|2.1425.peg.2867|594242
MARGGRPGVIAARALSEEEHVPREGQLHEALVGCAQPLRRRAGEEVGMRPTRLPEVGAAD
GRPVGVDVDAEQRRSGGRIHGLSLRRARGPRKRPASAGSACPGRTDLERVDALGDGHAVL
PQRGEAVVDRQDLGLGDRAGEPLQATGQLVQLDGVRVGPDEHEVHGHVGEHAGDLASLVL
EHARGAALGTLADEGDAGTPHGAVHGVLRLAVDGDRHLAADPPALQGAAQDHADRARLAL
DLQVRRALGLASQDDEEGEDAREHARDHEEYGGEPVATGREDREQDADDDGAQQREQHPP
DRALVVPPGHLEDLPHLLDAAGFLGCLRRGCLAGHGAQDTGAREAAGTADGDRASSCPSQ
ARVTAVILRGIARSPSLPASPHTPGTGTRSSTTHVHGAGPRRGRDAMPDGSAQPHVGPLR
GRGRGEGPRRETIDGGSGASTALTPRRTRSRAADTATAGSTVAGYRLVRLIGKGMRCEVH
LARPCRAAAASAGVTDNVAVKIVPRTERSRGEAEILALQAVTSDHVVELRDVATLSDGSL
CIVQSLGTRGTAAALLGRRGSLTPGETVTLVASVLRGLGDLHDVGIAHGAVDLTHVVIDA
TGRPLLGGLGSSRLVAGEAGEEGIRGVDPVDQDLGRVARIVQALRDPGDAHGRASNDRWL
AWLALLDGTIHGESDLSAHDLADRLLDVADAAPLADAGAARHEEDADRALSHGAIPLDAR
PDTVSGRAEHATGPRRAPRPFSRSRGSAHRRHRAARAAWAHDVDARLTSVRSELVSVRPR
IWALGASALLLLIAGVVAVPLLTGPARGATEVRTSTPSTAAPADAGFDVDASAAPDGDAS
PGPDADAARSPDPDIAAPALLRLRAACLHHADAACVSDVDEAGSAVDDADRSTIASGGSA
SPDGAALHVDDALGPARRLGDTALFELRPGSDTPAARAAESAPERRPASLLIVRGEAGWR
IRDLMDDR
>fig|6666666.374469.peg.2782|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------MRCEVH
LARPCRAAAASAGVTDNVAVKIVPRTERSRGEAEILALQAVTSDHVVELRDVATLSDGSL
CIVQSLGTRGTAAALLGRRGSLTPGETVTLVASVLRGLGDLHDVGIAHGAVDLTHVVIDA
TGRPLLGGLGSSRLVAGEAGEEGIRGVDPVDQDLGRVARIVQALRDPGDAHGRASNDRWL
AWLALLDGTIHGESDLSAHDLADRLLDVADAAPLADAGAARHEEDADRALSHGAIPLDAR
PDTVSGRAEHATGPRRAPRPFSRSRGSAHRRHRAARAAWAHDVDARLTSVRSELVSVRPR
IWALGASALLLLIAGVVAVPLLTGPARGATEVRTSTPSTAAPADAGFDVDASAAPDGDAS
PGPDADAARSPDPDIAAPALLRLRAACLHHADAACVSDVDEAGSAVDDADRSTIASGGSA
SPDGAALHVDDALGPARRLGDTALFELRPGSDTPAARAAESAPERRPASLLIVRGEAGWR
IRDLMDDR
>fig|33013.175.peg.1544|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------MQALRDPGDAHGRASNDRWL
AWLALLDGTIHGESDLSAHDLADRLLDVADAAPLADAGAARHEEDADRALSHGAIPLDAR
PDTVSGRAEHATGPRRAPRPFSRSRGSAHSRHRAARAAWAHDVDARLTSVRSELVSVRPR
IWALGASALLLLIAGVVAVPLLTGPARGATEVRTSTPSTAAPADAGFDVDASAAPDGDAS
PGPDADAARSPDPDIAAPALLRLRAACLHHADAACVSDVDEAGSAVDDADRSTIASGGSA
SPDGAALHVDDALGPARRLGDTALFELRPGSDTPAARAAESAPERRPASLLIVRGEAGWR
IRDLMDDR
>fig|2.1418.peg.1996|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------MSVRPR
IWALGASALLLLIAGVVAVPLLTGPARGATEVRTSTPSTAAPADAGFDVDASAAPDGDAS
PGPDADAARSPDPDIAAPALLRLRAACLHHADAACVSDVDEAGSAVDDADRSTIASGGSA
SPDGAALHVDDALGPARRLGDTALFELRPGSDTPAARAAESAPERRPASLLIVRGEAGWR
IRDLMDDR
