>fig|6666666.68540.peg.973|151744
MLDSITLRVAFGVTTLTLFLLFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQ
VWGNPLGNGLIVAGAACVWMGSRSLRDRATPWWLVVSPAAVIVAVSAADSPATDDWSGGA
LFLSLMAGLIGLSTREIVMLDAGLSRTRWPLILASGTLAAYYAIRLVVFLAAGPRSGIFT
SWFGTPSTTLITLVLLVVVSFSMASLSGEQAAKMFAARAATSRQELVDGGSVQRRLLPQA
RPRSARLPGRRRMRPQRGGERRLLRLAAHRGRPRGDARRRHGQGRGGGHDRGHRPCCAAG
RIDFP
>fig|2.1418.peg.1802|594099
MLDSITLRVAFGVTTLTLFLLFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQ
VWGNPLGNGLIVAGAACVWMGSRSLRDRATPW----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>fig|2.1425.peg.2873|594242
MLDSITLRVAFGVTTLTLFLLFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQ
VWGNPLGNGLIVAGAACVWMGSRSLRDRATPW----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>fig|33013.175.peg.586|614133
MLDSITLRVAFGVTTLTLFLLFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQ
VWGNPLGNGLIVAGAACVWMGSRSLRDRATPW----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>fig|33013.181.peg.1227|614141
MLDSITLRVAFGVTTLTLFLLFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQ
VWGNPLGNGLIVAGAACVWMGSRSLRDRATPW----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>fig|6666666.374469.peg.2578|645144
MLDSITLRVAFGVTTLTLFLLFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQ
VWGNPLGNGLIVAGAACVWMGSRSLRDRATPW----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
