>fig|33013.181.peg.1283|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLT---TRARATSSRR------SAG-----RTSWSRP--
-----WVSRTSSSRSGSSR-----APRCSTSASRVSWIPRPGRRASRATWIRPSPRSPAT
CRRTRAGSGR
>fig|6666666.68540.peg.1612|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRAYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DARLAAELRG
>fig|6666666.374469.peg.1874|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DARLAAELRG
>fig|2.1418.peg.908|594099
MLKESHARRPVLQRPPLRGRPGDRGRPRAGARASARHPRDDRERELRAARGAAVAGIRAH
QQVRGGLPGPPLLRRLRVRRRGRAARHRPREEPLRRRVRERPAALGRHRQRRRPRRHRAA
RRHDPRPRARARRPPHARHEAQLLRQALRRGGVRRRSRHLPHRHGRRAREGARAPPAGHH
RGLVGVPPPPRLRRVPVDRRRGRREALGRHGALRGPRGRGRAPLARPVRGRRLLHRAQDP
RGPPVRRDPQPRHRARQEAQLGRVPGPAGRPAHARHRGQGHGVQDRGHRGVRGPPAPHHP
GRADPRRAPRRGRLHRGRRLGPHGRHGRAPRARGSAELAHRRQAGGGRAARGRHHGQPQL
GAVRPAPADGHLRRPHRHVRARDPRLRRDRVHGGGGHHRRDPEARQRPRRPACARAHAHR
RLPALRGPHPVTAVVLDGVATASAVKSELAVRIRALREQGLVPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DARLAAELRG
>fig|33013.175.peg.2499|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MPGLGTLLVGDDPGSRSYV
AGKHRDCAEVGIESIRVDLPADATEADVRLAIERLNSDPAVTGYIVQLPLPAGIDENAML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DARLAAELRG
>fig|2.1425.peg.1294|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------ML
ELIDPSKDADGLHPTNLGRLVLGVQGELTSPLPCTPAGIVEMLQRYEVPIAGQHVVVVGR
GLTVGRPLGLLLTRKGLDATVTLTHSRTRDLEQEVRRADIVVAAVGVAHLIKPEWVKPGA
AVLDVGITRVVDPETGKARLTGDVDPAVAEVAGHLSPNPRGVGPMTRAMLLANVVQAAER
DARLAAELRG
