>fig|33013.181.peg.1128|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------MRPAAAMREGETHG
GHRALRSRELHRIVGDGRSIRSILRPLAEEDRMPTKELRAPEPLDAVDRKLVALLRADAR
TPNSRLAEQAGIAPSTCVTRVRGLVERGVITGFTATIDAAAVGVGLQALISIAIRAGARH
EMAAFASEMRELADVVQLFYLGGSEDFIVHIAVRDSDHLRDFVLQHLSAHPAVASTRTSV
VFDHHYSGPAVGDPGA
>fig|2.1418.peg.183|594099
MRADPAVTGSRSRDGRAPRRSGRASGGEHVRDRRQRHLERRRDVRVRDVPVVHVEAEGER
GILREGPLPALLGEGDHVRQRRVRQRARRGLRHRAGHVGDAVVDAVVHVEGGVVVRGRVG
SLEAAALVDGDVDEHGSLLHRRDHRIGHELRGLRARDEDRADDEVGVLQLRGDLVGRGDA
RLHLPAEADLELAEARDGEVDDRDVGAHAERVRRRVLARDAAADHDDARLRGAGHAAEED
PAPAGRAHQVVRADLGGEPAGDLAHRLEERELAVRELHRLVGDGRGAGGDERVRAGPRRR
EVQVGEEGLARTHARVLLGDGLLDLEQQVSGAPHLVSRGDDGRARLDIVGVGDAGSEPRA
LLDEHLVAAAHELVHARGRGGDPVLVVLDLGGDPDLHACSVSSPREVRPAAAMREGETHG
GHRALRTRELHRIVGDGRSIRSILRPLAEEDRMPTKELRAPEPLDAVDRKLVALLRADAR
TPNSRLAEQAGIAPSTCVTRVRGLVERGVITGFTATIDADAVGVGLQALISIAIRAGARH
EMAAFASEMRELADVVQLFFLGGSEDFIVHIAVRDSDHLRDFVLQHLSAHPAVASTRTSV
VFDHHYSGPAVGDPGA
>fig|33013.175.peg.3037|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MREGETHG
GHRALRTRELHRIVGDGRSIRSILRPLAEEDRMPTKELRAPEPLDAVDRKLVALLRADAR
TPNSRLAEQAGIAPSTCVTRVRGLVERGVITGFTATIDADAVGVGLQALISIAIRAGARH
EMAAFASEMRELADVVQLFFLGGSEDFIVHIAVRDSDHLRDFVLQHLSAHPAVASTRTSV
VFDHHYSGPAVGDPGA
>fig|2.1425.peg.1102|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MPTKELRAPEPLDAVDRKLVALLRADAR
TPNSRLAEQAGIAPSTCVTRVRGLVERGVITGFTATIDADAVGVGLQALISIAIRAGARH
EMAAFASEMRELADVVQLFFLGGSEDFIVHIAVRDSDHLRDFVLQHLSAHPAVASTRTSV
VFDHHYSGPAVGDPGA
>fig|6666666.68540.peg.1982|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MPTKELRTPEPLDAIDCKLVALLRADAR
TPNSRLAEQAGIAPSTCVTRVRGLVERGVITGFTATIDADAVGVGLQALISIAIRAGARH
EMAAFASEMRELADVVQLFFLGGSEDFIVHIAVRDSDHLRDFVLQHLSAHPAVASTRTSV
VFDHHHSGPAVGDPAS
>fig|6666666.374469.peg.1490|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MPTKEMRAPEPLDAIDRKLVALLRADAR
TPNSRLAEQAGIAPSTCVTRVRGLVERGVITGFTATIDADAVGVGLQALISIAIRAGARH
EMAAFADEMRELADVVQLFFLGGSEDFIVHIAVRDSDHLRDFVLQHLSAHPAVASTRTSV
VFDHHYSGPAVGDPAS
