>fig|33013.181.peg.352|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MEAPHATRTIGGRSMSSAAPTAAV
IGEPEVDEDVATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLLQTIRDAVR
TLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPMTT
QNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPETVA
MREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWDLI
HDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPAERTAAD
DALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTRLTID
WDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGALPLD
GPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQARERRRPRGRGRGRVERRG
SRGLRGADGGGRARRRGRHRRGPARGGRLRAPRGLRPRRPRGRRGAGRPDPRRPRRRRRP
DPPGRRLARRQRARGPDRRRLGLPARAARHHAAQHHARLRRRPAGVRRRPSRHRLVHGRA
APVPGRRELLDREDRGGDVGARGRPRVLEGRLPRPHDDLRGQGARRPRARARTSGREAVD
GRAARAGPDRGLTRPLL
>fig|6666666.68540.peg.2539|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MLRGRADPRADPARGTRSRADPADTVEAPHATRTIGGRSMSSAAPTAAV
IGEPEVVEDVATVASSPAWLALKDAAVALQPMQVKDGSIPDAAHHAEAARLIQTIRDAVR
TLAPLFPHDAAYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPMTT
QNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPETVA
MREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWDLI
HDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPAERTAAD
DALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTRLTID
WDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGALPLD
GPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>fig|2.1418.peg.1702|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MEAPHATRTIGGRSMSSAAPTAAV
IGEPEVVEDVATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLIQTIRDAVR
TLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPMTT
QNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPETVA
MREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWDLI
HDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPAERTAAD
DALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTRLTID
WDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGALPLD
GPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>fig|33013.175.peg.4|614133
MPREMASAQLIFTQNGTDSVSVQPPAAMSASVMTPMVFCASFVPCASETREALPIWPMRK
VRSRPRPARLPMMRHTSQVPTAATAPARIGDMSAGRITLPTTPSSLDPSPAQFTPFSPRP
ASVEPMRPPNSACEELDGRPSSQVSRFQTMPPMRPASTMSSSADPPPWSSAGSGAPDLSW
IFTTAFVTVSATSMLRNAPTRLSTAESVTATLGFNAPVAMDVAIAFAVSWKPLVKSKASA
VMTTSTRRMNGSTAMILRPARVSPLRGTVGFTGCSPAPVEKPAPAAVARTDPEDPHARHP
ARIPGRRADPRRRRARPRRAPGVPDLERVPVPRAVGADGRGRRGAHRRRRLRRPRARGPV
GRGRGIRSRGPRRARRPRGSGRAVRPAPRGGRARSRARRARRAGAHGRRVRLVPARDARR
GADPRRQPGDAPRARARGLREGGALPRRLARGGRRAARVRRLRGAAPRPRVGDHDAGSDG
RRGVALPARARMLRGRADPRADPARGTRSRADPADTVEAPHATRTIGGRSMSSAAPTAAV
IGEPEVVEDVATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLIQTIRDAVR
TLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPMTT
QNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPETVA
MREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWDLI
HDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPAERTAAD
DALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTRLTID
WDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGALPLD
GPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>fig|6666666.374469.peg.861|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MSSAAPTAAV
IGEPEVVEDVATVASSPAWLALKDAAVELQPMQVKDGSIPDAAHHAEAARLIQTIRDAVR
TLAPLFPHDATYLAALDVDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPMTT
QNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPETVA
MREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWDLI
HDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPAERTAAD
DALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTRLTID
WDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGALPLD
GPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>fig|2.1425.peg.903|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------MDFARWVDAGLGVPDFLDSLNEFQPQRDRVDGIRHLVVFPMTT
QNGSASRLVEAVLIEVVWPEFVAELEAGDYGNALFVPIRFVDFTPGYDTNSAVLFPETVA
MREIPTFTWGAIFADREAARFRRVVRHAAEVTKLELPDDARRLLDDQRLAEETFVMWDLI
HDRTHMRGDLPFDPFMIKQRMPFFLYSIEELRCDLTAFREAVAIQRRLAAVDPAERTAAD
DALLERAGMVQHAVIFDRIFRFAITGSRVRNYDGLGGQLLFAWLHQHHVLHWTDTRLTID
WDDVADVVVALADRVNDLYWRSIDRPKTAHWLAAYAMVTETVTPHPASTWAKGPGALPLD
GPPKGLTDLVLDDEFPLSMFFEALEKKMRDVIGSTAGITGQAA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
