>fig|2.1418.peg.1474|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MTGTAAAAAE
AEPAPRIRAVTVVIPARDEEELVGRCLASVEVAAARARADGVRVRVILVADDCRDRTAEV
ARAAGVEVIESAAGRVGAARAQGVDAARAGWDGDDAEHWIACTDADSAVPPAWITSQLEL
ADGGADVVVGTVRPELDDLSPAQVAAWRATRVPGHANGHVHGANLGVRADAYVAAGGFPA
VAEHEDVDLVTRLRGLDARITASAAGEVLTSSRREGRTPGGYAGYLHVSLLERAREREIG
RQRAVGCDSPCVPAG
>fig|33013.175.peg.218|614133
MRAALAETPPGPEWTTQRALALAVALGDGGARPGAGGTADLWEALATLAAADLGIARTVE
PHLDALAILEQERGAAGDDGARGVDTHAGGAAARTWGVFAAEGGGDPLTAVADADGPDAV
RLSGTKPWCSLAGSLTHALITAAVDDGSRGLFAVDRRQPGVEVVPGAWAARGLVEVPSGP
LRMRDVPARRVGAPGWYLERPGFHWGGIQVAACWYGGAVGLARTLLQAASREGADRLLRM
HLGAVDAALDGARASLAEAALLVARGRAEGEAGRLRGKRVRAVVARAVDDTLTHVAPALG
PAPLAQDADHAKRVADLGLYAAASRRARRRLARRGARGGGAAARGGGGRDGHEGHGDERS
HDRGRPCAGRRGGRRLRRARARHRCRRLGRGSALGRARRARPRGDGGAPRGVRARRRRVD
RGRGPHGDRGRAGRAGDPRDRDRRRRLAPRIPHSHARRARGRPPRRGPRRPRRGRARRPA
RAPRAPRRRDPRAPRGRARRPRRAPRRRRAGHVGRGSLARRRAPGPPRHGRGRRRAGGRS
ARRAWDPARRVPGVDVALGDARRPARAVGRDAGPPARRAHTGGQAGRDPRARQPGGSAVR
RPRGRRRPAARVPPARRPRPRGADRVRRRDRDAHRRRALRRRVRPRRGSVARPDPLVRAP
QAPRHPRGPARREVRPGAGDRLLHRRDDGGPRRARGRAAGRGRRADRGRAGPRPPRRRAA
RAPRGARRGRRLAGRRVRPRRDERGRLLPRRRRVRPRARRPARGTRRRRHAGRLPLAAPG
GRLPADGRRGARAARRRTRAARADAARGGRLPARGAVGGSALGRRAHGAAVTGTAAAAAE
AEPAPRIRAVTVVIPARDEEELVGRCLASVEVAAARARADGVRVRVILVADDCRDRTAEV
ARAAGVEVIESAAGRVGAARAQGVDAARAGWDGDDAEHWIACTDADSAVPPAWITSQLEL
ADGGADVVVGTVRPELDDLSPAQVAAWRATRVPGHANGHVHGANLGVRADAYVAAGGFPA
VAEHEDVDLVTRLRGLDARITASAAGEVLTSSRREGRTPGGYAGYLHVSLLERAREREIG
RQRAVGCDSPCVPAG
>fig|6666666.68540.peg.2827|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MTGTAAAAAE
VEPAPRIRAVTVVIPARDEEELVGRCLASVEVAAARAGMDGVRVRVILVADDCRDRTAEV
ARAAGVEVIESAAGRVGAARAQGVDAARAGWDGDDAEHWIACTDADSAVPPAWITSQLEL
ADGGADVVVGTVRPELDDLSPAQVAAWRATRVPGHANGHVHGANLGVRADAYVAAGGFPA
VAEHEDVDLVTRLRGLDARITASAAGEVLTSSRREGRTPGGYAGYLHVSLLERAREREIG
RQRAVGCDSPCVPAG
>fig|6666666.374469.peg.542|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MTGTAAAAAE
VEPAPRIRAVTVVIPARDEEELVGRCLASVEVAAARARMDGVRVRVILVADDCRDRTAEV
ARAAGVEVIESAAGRVGAARAQGVDAARAGWDGDDAEHWIACTDADSAVPPAWITSQLEL
ADGGADVVVGTVRPELDDLSPAQVAAWRATRVPGHANGHVHGANLGVRADAYVAAGGFPA
VAEHEDVDLVTRLRGLDARITASAAGEVLTSSRREGRTPGGYAGYLHVSLLERAREREIG
RQRAVGCDSPCVPAG
