>fig|33013.175.peg.1655|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------MTD
LVEADGHGDADHDDEHPEDVEEDAVHGGRGYLPHPGRTPPWRGSAGWPPTAGRVPPRSPG
LVWEPVTRGAPMPGERPDPLAGTLLAGRYRISGLLGRGGMATVYRAADETLGREVAVKVF
ATDSADPGEVERQEGEVRMLAGLSHPGLVTLFDVGDDVVADRVLAFIVMEIVDGSTLADR
MKEGPLPGQEVARIGGILSDALGYIHRRGVVHRDGMPANVLLARPEDDDEPAVAKLTDFG
IARLVDGTRLTSTGSIIGTVSYLSPEQALGEEVGAPTDVYALGLVLLECLTGRRTFPGRA
AESTMARVVRDPEIPARLGASWVDLLSRMTRRDPATRPTAREVAAELRTGRAPESAVDAP
TATSTRVMPAAAAAGLGAAGAGAAAAA-PFADPDARTERFAAAPTTPPARGADPTARTSP
AADADRAPAKRRGNRALSIGVVSVLIAAAAVVGVVTVNAMQTHDTSYPSVPGPLGASLEE
LQKSVEDAP
>fig|2.1418.peg.2417|594099
MLEALGDLLGERVDVDLGAAAARAGDDLELALAEVERLQDLQAHLHLLGRRRGEGDADGV
ADALGEQDPERRGALDGALEGGAGLGDAEVQRPVAALGEQAVGLHHDDRVVVLDRDLEVV
EVVLLEEAGLPDGGLDERLGRGLAVLLQQARVQGSGVDADADGDARGLGGLRDGADLVVE
LADVARVHAHRADAGVDGGEDVAGLEVDVRDDRDLALLRQDVQHVRVVLVRHRHAHDVAA
RGRELGDLLERRVDVGRLRGRHRLDADLGVPAHLHLADADLTGLAAGREDLRDLRHSEID
CWHGKSLRPIPARPVRRGRGRRRAQGGVGCAATSGQPDGVHQVGEDQQRAHGAEEDHDHE
RHRHELRDVHRPGVASTERLREEPAHALHDRAEHVPAVERQERQQVDHPERDVERCDEAD
HRGGARGDRRLVEARDLARHAADADDAHRAVRVPFAAAERGAADVDQALREVEDQVADRG
HVLAGGGERGGERLLLHRLRGAEADEAHLARHRVPLLVDLGGAAGSGDGLLREHGRDGER
LPRAAALHDDVELLPGGCLDRARDLVPRGDRRAVDADDRVAGLEAGRGTRGLGSAGGAGG
GVGRRGGSGGHDARVHLADRGGGRRDAEAAEHDGEQEDRQQEVHRRAAEHDHHALRDGQL
VEGAVLLVADALGAGLAGVLHEEVEEAAAGAVVGVRGGRRSGVGAAGVGPDELRDPRAAR
AGAGALRREHADHRDVAAERDGLHAVLGLALAAAEDRRPEADHVLRDAHAEELGGHQVTD
LVEADGHGDADHDDEHPEDVEEDAVHGGRGYLPHPGRTPPWRGSAGWPPTAGRVPPRSPG
LVWEPVTRGAPMPGERPDPLAGTLLAGRYRISGLLGRGGMATVYRAADETLGREVAVKVF
ATDSADPGEVERQEGEVRMLAGLSHPGLVTLFDVGDDVVADRVLAFIVMEIVDGSTLADR
MKEGPLPGQEVARIGGILSDALGYIHRRGVVHRDVKPANVLLARPEDDDEPAVAKLTDFG
IARLVDGTRLTSTGSIIGTVSYLSPEQALGEEVGAPTDVYALGLVLLECLTGRRTFPGTA
AESTMARVVRDPEIPARLGASWVDLLSRMTRRDPATRPTAREVAAELRTGRAPESAVDAP
TATSTRVMPAAAAAGLGAAGAGAAAAA-PFADPDARTERFAAAPTTPPARGADPTARTSP
AADADRAPAKRRGNRALSIGVVSVLIAAAAVVGVVTVNAMQTHDTSYPSVPGPLGASLEE
LQKSVEDAP
>fig|6666666.68540.peg.1278|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MRMLAGLSHPGLVTLFDVGDDVVADRVLAFIVMEIVDGSTLADR
MKEGPLPGPEVARIGGILSDALGYIHRRGVVHRDVKPANVLLARPEDDDEPAVAKLTDFG
IARLVDGTRLTSTGSIIGTVSYLSPEQALGEEVGAPTDVYALGLVLLECLTGRRTFPGTA
AESTMARVVRDPEIPARLGASWVDLLSRMTRRDPATRPTAREVAAELRTGRAPESAVDAP
TATSTRVMPAAAAAGLGAAGAGAAAAAAPFADPDARTERFAAAPTTPPARGADPTARTSP
AADADRAPAKRRGNRALSIGVVSVLIAAAAVVGVVTVNAMQTHDTSYPSVPGPLGASLEE
LQKSVEDAP
>fig|6666666.374469.peg.2241|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MPGERPDPLAGTLLAGRYRISGLLGRGGMATVYRAADETLGREVAVKVF
ATDSADPGEVERQEGEVRMLAGLSHPGLVTLFDVGDDVVADRVLAFIVMEIVDGSTLADR
MKEGPLPGPEVARIGGILSDALGYIHRRGVVHRDVKPANVLLARPEDDDEPAVAKLTDFG
IARLVDGTRLTSTGSIIGTVSYLSPEQALGEEVGAPTDVYALGLVLLECLTGRRTFPGTA
AESTMARVVRDPEIPARLGASWVDLLSRMTRRDPATRPTAREVAAELRTGRAPESAVDAP
TATSTRVMPAAAAAGLGAAGAGAAAAA-PFADPDARTERFAAAPTTPPARGADPTARTSP
AADADRAPAKRRGNRALSIGVVSVLIAAAAVVGVVTVNAMQTHDTSYPSVPGPLGASLEE
LQKSVEDAP
