>fig|6666666.374469.peg.1712|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------MTRGKDRDGSPRRER
GFGAAVERFNERLRPYLGAPPLGPYTDDPVPEPQSRLCPMCGKPMPDHDIDRSGARTQVH
CPV
>fig|6666666.68540.peg.1770|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------MRQAQRLEDRPVQR
DDGSRRQHGREAELALERQGIRARRALVCHSSSSPPAELPRTLNTMTRGKNRQDGSRRER
GFGAAVERFNERLRPYLGAPPLGPYTDDPVPEPQSRLCPMCGKPMPDHDIDRSGARTQVH
CPV
>fig|2.1418.peg.399|594099
MVARRAPADARGVDADPLHLDVGRHEHPVDAAGRALRRLVVRPRAPLGREALAGGGPRVH
ERAVLEEQPVRLRVDARVGVARDDRGHLHLGDDPEDHARRLLARAPREVVEVRVHVAQRQ
AGRAIREVGDHRDPRHHVAPAAGPGDRGRVRQRDLAPARELQSARVVEGGAALAVAVGVA
AVPDPPVVPPERVRQRAPLRGHRLLRAEERGLLTLEQLGDERLAVGPAVGAARPVAAEQA
PDVVRHHVQLGGVDRADERPSVREGAVGAEGHGSIVPLRGRVDRGWRGTVTGALGARGIR
RRVDAREELVQVVPDPAELRGSHARALGHTGGHLLGLAAELAARVGERDAHDALVLHAAR
ALQQAGRLQALQERRDGRGLEGQRAAEVGDRAAVALPEREHHEVLRMREAQRLEDRPVQR
DDRPRRQHGREAELALERQGIRARRALVCHSSSSPPAELPRTLNTMTRGKNRQDGSRRER
GFGAAVERFNERLRPYLGAPPLGPYTDDPVPEPQSRLCPMCGKPMPDHDIDRSGARTQVH
CPV
>fig|33013.175.peg.1757|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------MTRGKNRQDGSRRER
GFGAAVERFNERLRPYLGAPPLGPYTDDPVPEPQSRLCPMCGKPMPDHDIDRSGARTQVH
CPV
