>fig|2.1418.peg.252|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MSAVVA-----G
TTPVAADPYAWPYDGAIDVARTAVVCIDWQVDFCGVGGYVDRMGYDLALTRAGLAPTVRL
LERVRALGMTVIHTREGHRPDLSDLPANKRWRSERAGAEIGSVGPCGRILVRGEPGWEIV
PEVAPLPGEPVIDKPGKGAFYATDLDLVLRARGIDRLILTGITTDVCVSTTMREANDRGY
ECLVLSDCTGATDPANHDAALRMVTMQGGVFGAVAASGDVLAALAGAQVRA
>fig|33013.175.peg.1010|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MSAVGA-----G
TTPVAADPYAWPYDGAIDVARTAVVCIDWQVDFCGVGGYVDRMGYDLALTRAGLAPTVRL
LERVRALGMTVIHTREGHRPDLSDLPANKRWRSERAGAEIGSVGPCGRILVRGEPGWEIV
PEVAPLPGEPVIDKPGKGAFYATDLDLVLRARGIDRLILTGITTDVCVSTTMREANDRGY
ECLVLSDCTGATDPANHDAALRMVTMQGGVFGAVAASGDVLAALAGAQVRA
>fig|6666666.68540.peg.1911|151744
MPAREIRRPLALAPLDQRQQLAVVGERVGAPGARGGQVVEPHALRHRLDDLRQRAVVRGG
RDRDVEVVVEAREVGRIRGALLQADHALELAEVVGRAAPRGELDGPRLHERARLEQVHQL
GQHARPHRHALVRAMHDPAVRLERPQRLAHGDVARAHPLGDLIGLHAGSGSDDAAEDLLL
EQDAHALRGAETGGDEGGGGHSLIIGSAARPPPRRVSHPGNTTETPVCGRAVPIGRSRIP
RRRHPTPRSSHVAPRRPAGRASRRPRRPGSRRPPRVLRVRVGARAAPCAPPHRIGRRRVA
RLPDDPHLRRLRRPGRALARLLAGHGRDRGRHARPHGLRRGAELPGGSQRRELRAHGDAH
VRREGVRRAGGLPRHRGHRLVRLPDRAHRIHPARQPRLGPDGHHARGRPPLRRGHAARHP
RPLLDRRGRRSPLPRARRGRRRHRRDQVGRRGAADRARRGSRCAQLRRGSDPRRRALRRL
GHHDRRLHALGALGPAGRARDPGGVPVRQRDRAGGRRPRRRAGRRDRPGHRGRRLPRDPR
RAGRCPRAARRALRGREPRIRVRPLPLQRRRRLEPAHRHAHAPHHPGARRGGRRPRGRRH
LDLLRGMAEPARRDRAAHRRRAHRRPAAARPAARGDRIRRRPRCLACPRLRGLGGRRRRR
ARRPRVRRLPLHGRRRDGRRRGRPRRRGHRGAGARPAGRGRRRGGGPLVSAVGAPATVAG
TTSVAADPYAWPYDGTVDVARTAVVCIDWQVDFCGVGGYVDRMGYDLALTRAGLAPTARL
LERVRALGMTVIHTREGHRPDLSDLPANKRWRSERAGAEIGSVGPCGRILVRGEPGWEIV
PEVAPLPGEPVIDKPGKGAFYATDLDLVLRARGIDRLILTGITTDVCVSTTMREANDRGY
ECLVLSDCTGATDPANHDAALRMVTMQGGVFGAVAASGDVLAALAGAQVRA
>fig|6666666.374469.peg.1563|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MSAVGAPATVAG
TTSVAADPYAWPYDGAVDVARTAVVCIDWQVDFCGVGGYVDRMGYDLALTRAGLAPTARL
LERVRALGMTVIHTREGHRPDLSDLPANKRWRSERAGAEIGSVGPCGRILVRGEPGWEIV
PEVAPLPGEVVIDKPGKGAFYATDLDLVLRARGIDRLILTGITTDVCVSTTMREANDRGY
ECLVLSDCTGATDPANHDAALRMVTMQGGVFGAVAASGDVLAALAGAQVRA
