>fig|2.1418.peg.1168|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------MRARTLGSTRPGV
GAGAGPGPGEPERIRMWSKQSGDATGAISPVPTHPHAHPVRGAWLVRVGGGPALGWVLRH
RDDLEAPFSYEVYACGLGADGLRVWVQRRDSLNAAVAWVMQHDAELLAFGRRLRPDPAQP
STRSDEDAAAPEAGDGGVGSD
>fig|33013.175.peg.302|614133
MGHGGRRSGRRRRASGQPVLVRLVRLVRGRRQAVRALLATAAVIIVLAAVVAGAREAAFG
PDSGGGHLSADVPDGAVVRALAGAGLVRDGRIDVESARRMADAVQADGRERHPRYDRDAF
GPAWADTDGNGCDQRDDVLVRDLARVAFAPSDPGCTVVAGHLDDVYTGHGIDFARGPRTS
AAVQIDHLVPLSWAWQHGAWSWSDERRERLATDFDELQAVDGPNQPGQVGPGAGDVAAAR
RGLPVPLSHTLRLRREQVRHVDRRRGPGRHRPRPRGLLVRSPDRSASVRARTVGSTRPGV
GAGAGPGPGEPARIRMWSKQSGDATGAISPVPTHPHAHPVRGAWLVRVGGGPALGWVLRH
RDDLEAPFSYEVYACGLGADGLRVWVQRRDSLNAAVAWVMQHDAELLAFGRRLRPDPAQP
STRSDEDAAAPEAGDGGVGSD
>fig|6666666.68540.peg.212|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MWSKQSGDATGAISPVPTHPHAHPVRGAWLVRVGGGPALGWVLRH
RDDLEAPFSYEVYACGLGADGLRVWVQRRDSLNAAVAWVMQHDAELLAFGRRLRPDPAQP
STRSDEDAAAPEAGDGGVGSD
>fig|6666666.374469.peg.218|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MWSKQSGDATGAISPVPTHPHAHPVRGAWLVRVGGGPALGWVLRH
RDDLEAPFSYEVYACGLGADGLRVWVQRRDSLNAAVAWVMQHDAELLAFGRRLRPDPAQP
STRSDEDAAAPEAGDGGVGSD
