---
title: "PriA activity assays protocol"
author: "NellySelem"
date: "March 2, 2017"
output: pdf_document
advisor: 'Francisco Barona Gomez'
lot: true
lof: true
space_between_paragraphs: true
link-citations: true
---

---
header-includes:
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{chemarr}
- \usepackage[caption=false]{subfig}
output: pdf_document
---

```{r include_reedtemplates_2, include = FALSE}
# This chunk ensures that the reedtemplates package is installed and loaded
# This reedtemplates package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```

```{r load_pkgs_chapter2, message = FALSE,echo=FALSE}
# List of packages required for this analysis
pkg <- c("dplyr", "ggplot2", "knitr", "devtools","RColorBrewer")
# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]
# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
# Load packages
library(dplyr)
library(plyr)
library(reshape) ## melt
library(ggplot2)
library(knitr)
library(RColorBrewer)
hm.palette <- colorRampPalette(rev(brewer.pal(11, 'Spectral')), space='Lab')  
library(genstats) ## Next libraries are for coursera
library(devtools)
library(Biobase)
library(scales) # 
library(xlsx) # For save data on excel
library(knitr)
library(drc) # for fitting Michaelis Menten model
library(ggplot2) # for drawing

```

```{r Materials, child = 'materials.Rmd'}
```

```{r Buffers, child = 'Buffers.Rmd'}
```

```{r Enzymes and Strains, child = 'Enzymes_and_strains.Rmd'}
```

```{r Protein Expression, child = 'ProteinExpression.Rmd'}
```

```{r Protein Purification, child = 'ProteinPurification.Rmd'}
```

```{r Protein Quantification, child = 'ProteinQuantification.Rmd'}
```

```{r Protein Gel, child = 'ProteinGel.Rmd'}
```

```{r proFAR assay, child = 'ProFARassay.Rmd'}
```

```{r GTP assay, child = 'GTPassay.Rmd'}
```

```{r GTP kinetics, child = 'GTPkinetics.Rmd'}
```

```{r PRA assay, child = 'PRAassay.Rmd'}
```

```{r TrpF kinetics, child = 'TrpF_kinetics.Rmd'}
```




