---
output: pdf_document
---
  ---
title: "TrpF_kinetics"
author: "NellySelem"
date: "May 18, 2017"
output: pdf_document
---


<!-- Process data-->
```{r include_reedtemplates_TrpFkinetics, include = FALSE}
# This chunk ensures that the reedtemplates package is installed and loaded
# This reedtemplates package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```

```{r load_pkgs_TrpFkinetics, message = FALSE,echo=FALSE}
# List of packages required for this analysis
pkg <- c("dplyr", "ggplot2", "knitr", "devtools","RColorBrewer")
# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]
# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
# Load packages
library(dplyr)
library(plyr)
library(reshape) ## melt
library(ggplot2)
library(knitr)
library(RColorBrewer)
hm.palette <- colorRampPalette(rev(brewer.pal(11, 'Spectral')), space='Lab')  
#library(genstats) ## Next libraries are for coursera
library(devtools)
library(Biobase)
library(scales) # 
library(xlsx) # For save data on excel
library(knitr)
#library(drc) # for fitting Michaelis Menten model
library(ggplot2) # for drawing
```


```{r Cinetics}
#First I saved file as scv tablar separated    
#perl -p -i -e 's/,/\t/g' Pra_scoe1.csv   
#An cut it to obtain just data  
#tail -n +39 Pra_scoe1.csv | head -n-3 > Pra_scoe1.data  
#perl -p -i -e 's/\sNr\.|\s\[\w*\]|\.\s\[.*\]//g' Pra_scoe1.data
#tablePRAPRO <- read.table(s"chapter2/cineticas/Pra_scoe1.data",header=TRUE, sep="\t") 
tablePRO <- read.table("cineticas/18082017_PraProfarAbsorbanceCombined.data",header=TRUE, sep="\t") 
tablePRA <- read.table("cineticas/18082017_PraProfarFluorCombined.data",header=TRUE, sep="\t") 
#tablePRA <- read.table("15082017_praOSCURO.data",header=TRUE, sep="\t") 


## visualising full data
tablePRO$Temp<-NULL
tablePRO$Cycle<-NULL

a<-tablePRO$Time[c(TRUE,FALSE)]
b<-tablePRO$Time[c(TRUE,FALSE)]+19.15

tablePRO$Time[c(TRUE, FALSE)] <- a
tablePRO$Time[c(FALSE, TRUE)] <- b
tablePRO$Time
tablePRO<-tablePRO[grep("Pro|Time", colnames(tablePRO))]
#tablePRA<-tablePRA[grep("Pra|Time", colnames(tablePRA))]

PROassay.m <- melt(tablePRO,id="Time")

plot(PROassay.m$Time, PROassay.m$value, col=PROassay.m$variable,  xlab="Time [s]",ylab="Absorbance", pch=19,bty='L')
par(xpd = TRUE)
legend("right", legend = (unique(PROassay.m$variable)), col = (unique(PROassay.m$variable)),pch=19,bg="white")

ggplot(PROassay.m, aes(x = PROassay.m$Time, y = PROassay.m$value),color="variable") + theme_bw() 

qplot(Time,value, data = PROassay.m,colour=variable)+theme_bw()+ theme(legend.position	="bottom",legend.text=element_text(size=10),plot.title = element_text(size = 14, face = "bold"),text = element_text(size = 12),axis.title = element_text(face="bold"),axis.text.x=element_text(size = 10),axis.text.y=element_text(size = 7))+facet_grid(PROassay.m$variable~.,scales="free")

## visualising full data
tablePRA$Temp<-NULL
tablePRA$Cycle<-NULL

a<-tablePRA$Time[c(TRUE,FALSE)]
b<-tablePRA$Time[c(TRUE,FALSE)]+19.15

tablePRA$Time[c(TRUE, FALSE)] <- a
tablePRA$Time[c(FALSE, TRUE)] <- b
tablePRA$Time
tablePRA<-tablePRA[grep("Pra|Time", colnames(tablePRA))]

PRAassay.m <- melt(tablePRA,id="Time")
plot(PRAassay.m$Time, PRAassay.m$value, col=PRAassay.m$variable,  xlab="Time [s]",ylab="Fluorescence", pch=19,bty='L')
par(xpd = TRUE)
legend("right", legend = (unique(PRAassay.m$variable)), col = (unique(PRAassay.m$variable)),pch=19,bg="white")

ggplot(PRAassay.m, aes(x = PRAassay.m$Time, y = PRAassay.m$value),color="variable") + theme_bw() 

qplot(Time,value, data = PRAassay.m,colour=variable)+theme_bw()+ theme(legend.position	="bottom",legend.text=element_text(size=10),plot.title = element_text(size = 14, face = "bold"),text = element_text(size = 12),axis.title = element_text(face="bold"),axis.text.x=element_text(size = 10),axis.text.y=element_text(size = 7))+facet_grid(PRAassay.m$variable~.,scales="free")

```

```{r slopes}
 ##pendientes (slopes) of linear part of the curve
# time when TrpF is added
cuttime<-344.2
maxtime=620

PRAassay2Time<-tablePRA[which(tablePRA$Time >= cuttime & tablePRA$Time <= maxtime),]

## removi columnas que se salian del margen de medicion
#PRAassay2Time<-PRAassay2Time[, !(colnames(PRAassay2Time) %in% c("C62uM"))]

# vector with slopes for each dataset
V0 <- apply(PRAassay2Time, 2, function(x) coefficients(lm(x ~ PRAassay2Time$Time,na.action=na.omit))[2])

PRAassay2Time.m <- melt(PRAassay2Time,id="Time")
plot(PRAassay2Time.m$Time, PRAassay2Time.m$value, col=PRAassay2Time.m$variable,xlab="Time", ylab="URF PRA uM", pch=19, xlim=c(cuttime-50,maxtime+50),bty='L')

V1 <- apply(PRAassay2Time[,2:ncol(PRAassay2Time)], 2, function(x) coefficients(lm(x ~ PRAassay2Time$Time,na.action=na.omit)))
apply(V1, 2, function(x) {abline(x, col = PRAassay2Time.m$variable)  })
par(xpd = TRUE)
slopeText2="m ="
slopeText<-paste(slopeText2,rev(round(V0[-1],digits=6)),rev(names(V0[-1])))
legend(450,100, legend = slopeText, col = rev(unique(PRAassay2Time.m$variable)), pch=19,box.lwd=0, bg="white")

## get relevant velocities and get correspondent concentrations
## V0 or slopes are on [PRA]uM/s 
# slopes stores the slope, with TRUE , FALSE the desired enzyme can be selected, One more than one is tested on a plate always check if it is the desired one.
slopes=(round(V0[-1],digits=6))[c(TRUE)]
concentration<-as.matrix(PRAassay2Time[1,names(slopes)])
#slopes
#concentration
slopes=as.matrix((round(V0[-1],digits=6))[c(TRUE)])
row.names(slopes) <- NULL 
slopes<-c(slopes)## plot on r base

slopes
# in concentration I stored the inital substrate concentration  
row.names(concentration) <- NULL 
concentration<-c(concentration)
slopes
concentration
```

```{r interpolar michaelis-menden, eval=FALSE}
## interpolar michaelis-menden

#https://rpubs.com/RomanL/6752
#https://davetang.org/muse/2013/05/17/fitting-a-michaelis-mentens-curve-using/
#S <-concentration
## from highest to lower concentration
S_ProFAR <-c(0,25,50,75,100,0,50,100)
v<-slopes
#v<-slopes[-length(slopes)]
#v <-slopes[c(TRUE,FALSE)]
v<--1*v
S_ProFAR
v
mm <- data.frame(S_ProFAR,v)                                                                                 
model.drm <- drm(v ~ S, data = mm, fct = MM.2())
summary(model.drm)
## first value equal km
## second value = vm
Km=coefficients(model.drm)[1]
Vmax=2*coefficients(model.drm)[2]
Enzyme=2.5 #2.5uM
Kcat=Vmax*Enzyme  
Km
Vmax
Kcat
mml <- data.frame(S = seq(0, max(mm$S), length.out = 100))
mml$v <- predict(model.drm, newdata = mml)


## plot on r base
plot(mm,log='',xlim=c(0,max(mm$S)), ylim=c(0,max(mm$v)), xlab="Reads", ylab="Transcripts")

##plot on ggplot
ggplot(mm, aes(x = S, y = v)) + theme_bw() + xlab("Concentration [uM]") + ylab("Speed [d[PRA]uM/s]") + ggtitle("Michaelis-Menten kinetics") +  geom_point(alpha = 0.5) + geom_line(data = mml, aes(x = S, y = v), colour = "red")

ggsave("mm.pdf", width = 6, height = 4)
```

