>fig|6666666.68540.peg.365|151744
MAVPMSSGGAVTVCQDQEDAPPAGDVPTGGSMAERIPHVVFVCARNGGKSQLAAALMRQA
AGDAVAVTSAGTYPGTSLNALAVESLAELGIDVAGERPKPLTDDMVREADLVVVLGAEAH
VDGDQDVAIETWITDEPSERGIDGMERMRLVRDDIRARVEELRARLGGVEGDPAAR
>fig|6666666.374469.peg.62|645144
-------------------------------MAERIPHVVFVCARNGGKSQLAAALMRQA
AGDAVAVTSAGTDPGTSLNALAVESLAELGIDVAGERPKPLTDDMVREADLVVVLGAEAH
VDGDQDVAIETWITDEPSERGIDGMERMRLVRDDIRARVEELRARLGGVEGDPAAR
