>fig|6666666.68540.peg.5|151744
-------------------------MGAPPGR--------------------LLADPGRG
P--------ARAGVRD-TTPG-------GARGPFHLRRLRRRPNDQGQRIWIRREPSLDT
AVAWMVQHSAELIAFAARSRSRSGSRGPAETTAAEHASADVDQARELGHVERGQFG
>fig|6666666.374469.peg.1311|645144
MPPLTTYPKMVHPSVALRTLADERGRALPPDRIDGEEHPVSRVKSKLDGINSLVRSTGQH
PWAHLQAGYWRIQVEDRPVPGYVIRHRAELGDPFTFDVYADARNDQGQRIWIRREPSLDT
AVAWMVQHSAELIAFAA--RSRSGSRGPAETTAAEHASADVDQARELGHVERGQFG
