>fig|33013.175.peg.2441|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------MTVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADAPQTLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLVDARHDIPGYAAWLRAFVDATGSRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRLAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMAKTRD---PRSAGGSTTSTTASSARSATAASCWRRSARRCRRTRA
PTRPASTSPCCSS----PPSATTSRPS----------------------PR-STGCGACS
PTPGSR-
>fig|2.1421.peg.1861|594133
MEPVEALRGEREGQAAVVADGREDAAAEEVVELGSGERGRVDRDRDGVVREREDAEHVLR
AVAEVRAAALVGADEGEHALVVGREDRDGALAEHRVGLPHVDDVPHPVQQRTRLRELRLH
VDLRVVVDERLHDGEVELARVGRGEPGVAVGGPLHGRARRVAVRQPDVVAHADLVAVVEE
RAAGEREQERVDELELGARVVEQGRQTAADADVDAHARVVGVPAVHRLPVLLAHHLERQL
VVVAEEDAPGGGLGDLERLAHDPLQLVRGLRAEGVEDPRHDREVEGHVALGLLLGAEERG
DLAGPLVGLGDEDPARVLLVDHGAQALEELVRGGLALAVALLGLVEVGDRVEAQAVDAHV
QPVADDAVDGLVHLRVVEVEVGLVREEAVEEELAAHRVEGPVGLLGVDEDDADVLVLLVG
VAPDVEVAVGAVGVGPGLLEPLVLVGGVVHHEVDDDAHVALVRLRDELLEVVERAELGEH
GHVVADVVAAVAEGRLEEGREPQAVDAEPLQVVELGDEALDVARAVAVGVDEGADHDLVE
DRALVPLLVEGEAGQGDGGGEAHGSPQGRDGTSTAGREGSWATLGAPGRAGRARRARGRG
RPPIVDSSPMIVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADADRVLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLRDARHDIAGYSAWLSAFVDATGTRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRFAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMAKTRDRGLRRWINDQHDRFFSAFSDRRVVLEAFRASVSSDASTYA
PRVDVPVLLVAAERDDITPVAAQHRLQRLFADARLEVIPRVGHLIHYETPREAAGFVRAF
LDEGSAS
>fig|6666666.68540.peg.849|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------MTVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADAPQTLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLVDARHDIPGYAAWLRAFVDATGSRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRLAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMAKTRDRSLRRWINDQHDRFFSAFSDRRVVLEAFRASVSSDASTYA
PRVDVPVLLVAAERDDITPVAAQHRLRRLFADARLEVIPRVGHLIHYETPREAAGSIRAF
LDEGSAS
>fig|2.1418.peg.1926|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------MTVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADAPQTLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLVDARHDIPGYAAWLRAFVDATGSRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRLAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMAKTRDRSLRRWINDQHDRFFSAFSDRRVVLEAFRASVSSDASTYA
PRVDVPVLLVAAERDDITPVAAQHRLRRLFADARLEVIPRVGHLIHYETPREAAGSIRAF
LDEGSAS
>fig|2.1425.peg.2174|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------MTVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADAPQTLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLVDARHDIPGYAAWLRAFVDATGSRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRLAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMAKTRDRSLRRWINDQHDRFFSAFSDRRVVLEAFRASVSSDASTYA
PRVDVPVLLVAAERDDITPVAAQHRLRRLFADARLEVIPRVGHLIHYETPREAAGSIRAF
LDEGSAS
>fig|6666666.374469.peg.2706|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------MTVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADAPQTLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLVDARHDIPGYAAWLRAFVDATGSRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRLAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMAKTRDRSLRRWINDQHDRFFSAFSDRRVVLEAFRASVSSDASTYA
PRVDVPVLLVAAERDDITPVAAQHRLRRLFADARLEVIPRVGHLIHYETPREAAGSIRAF
LDEGSAS
>fig|33013.181.peg.2124|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------MTVPSPYAAQLDRIPVVRRTVDLLGSRTAWWEYGPADAPQTLVVVHGFRGD
HHGLEPVVAQLPGVRILSPDLPGFGDSTPLVDARHDIPGYAAWLRAFVDATGSRDATVLG
HSFGSIVVSAALADGLPSPRAILVNPIAAPALEGPRGILTRLAVLYYRAAAVLPERAGFG
LLRNRAIVRVMSEAMATPRDRSLRRWINDQHDRFFSAFSDRRVVLEAFRASVSSDASTYA
PRVDVPVLLVAAERDDITPVAAQHRLRRLFADARLEVIPRVGHLIHYETPREAAGSIRAF
LDEGSAS
