>fig|2.1421.peg.1287|594133
MLLSGGKRSPRHRRPRRELRSRDRRTLEGPGPADLGSRTAMLDSLTLRVAFGVTTLTLLL
LFALVTYRGTRSPFSFWWSAALALFLGGSLAYLQDGTPGQVWGNPLGNGLIVAGAASVWM
ASRSLRGRTTPWWWVVAPAALIVAVSSADSPATNDWSGGPLYLALMTTLIALSTREIALL
GAGQSRTRWPLMLTSGALACYYAARLVVFISAGQRSDLFTGWFGTPSTTLITLILLVVVS
FSMASLSGEQVARALAARAALSRQELVDGGGVQRRLLPQTVPDLPGYEVAGACVPSGDVS
GDFFDWQRTPDGLVVTLADVMGKGVGAAMIAATVRASLRVASPMHDPGRTLSVVDRIVET
DLDVNDAFVTLLHLRLDARSGRVDLIDAGHGLGIVCRADGTREPIPSLNLPLGALGTQEW
VPTSVQLEPGDLLLVCSDGVLDLFDGTLASMDRAALTAMAARPTAHAAIESLTCLAAATT
PPDDVTVVAIRRTT
>fig|6666666.68540.peg.973|151744
----------------------------------------MLDSITLRVAFGVTTLTLFL
LFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQVWGNPLGNGLIVAGAACVWM
GSRSLRDRATPWWLVVSPAAVIVAVSAADSPATDDWSGGALFLSLMAGLIGLSTREIVML
DAGLSRTRWPLILASGTLAAYYAIRLVVFLAAGPRSGIFTSWFGTPSTTLITLVLLVVVS
FSMASLSGEQAAKMFAARAATSRQELVDGGSVQRRLLPQARPRSARLPGRRRMRP-----
------QRGGERRLLRLAAHRGRPRG----------------------------------
----------------DARRRHGQGRGGGHDRGHRPCCAAGRIDFP--------------
------------------------------------------------------------
--------------
>fig|2.1418.peg.1802|594099
----------------------------------------MLDSITLRVAFGVTTLTLFL
LFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQVWGNPLGNGLIVAGAACVWM
GSRSLRDRATPW------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>fig|2.1425.peg.2873|594242
----------------------------------------MLDSITLRVAFGVTTLTLFL
LFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQVWGNPLGNGLIVAGAACVWM
GSRSLRDRATPW------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>fig|33013.175.peg.586|614133
----------------------------------------MLDSITLRVAFGVTTLTLFL
LFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQVWGNPLGNGLIVAGAACVWM
GSRSLRDRATPW------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>fig|33013.181.peg.1227|614141
----------------------------------------MLDSITLRVAFGVTTLTLFL
LFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQVWGNPLGNGLIVAGAACVWM
GSRSLRDRATPW------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>fig|6666666.374469.peg.2578|645144
----------------------------------------MLDSITLRVAFGVTTLTLFL
LFALVTFRATRSPFSFWWCTALVLFMGGSLAYLQDGTASQVWGNPLGNGLIVAGAACVWM
GSRSLRDRATPW------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
