>fig|2.1421.peg.2044|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MVRVREQVERPDGAELVAALGEQGHVA
GERDGVARHVDDLRGTQLGERVDDGLLGTGARRVEDDGRALQPAALRGARLAHEVLEVAV
DAGGQRRGPHPLRQVVAGELGGDLVALHARDAHGVAEAVAHGGRQQPDAPVEVEVRGARV
EEGLVDRGLDGVVQRLGRAAVHLPEAAGLQLELPVAHALGDGVATLRLAVDEEHAHVAVR
RGDQVDPLDAGEALAEGRRAVDARGGEGQRLDGDHAVRARGVRTHAAVAVDVQADARAPA
EAVRLVVAGERPDLDLAVDARHAGQGVDDDPALELALVRQVDVAELGAADPVLGRAVDRG
LGPHVRTAVRGGVQHLDRVGAPEGLLGVLRDARAHPLAGDRVRDEDHPAVVPGDGDSPVR
DVGHVHLDLAAHLLTHAATLTHAGTPGRRSRSRR--------------------------
----HLGRACHDDPMTTRLHLASTSPARLALLRSAGVEPVVLHSDVDEPAAVAAAEAAHG
PLAPEEMVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDGVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADIDDDEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGVAWPDLWNRPGAVAARLV
>fig|33013.175.peg.2130|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------MVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDDVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|33013.181.peg.1987|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------MVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDDVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|2.1418.peg.1237|594099
MEHVALAPAELGLREVAVRVDGGRPLQVVEHVAACDGGDGRHDGLRGRRLGDHPGGTGGQ
RLADARDAVGDAVDEHRGTRALRGLDVVGDGGSVPQREVEDDHVALPADQALDELAGVRG
REDELEPGVEARGLEAEPHRLVVVDDGDADGRTAFGHLIGSLRGLGHPDPPRRVVPSSSD
DRLAHCIARLPRPLGGGCPRSGGGGHQHGHALDVVGVREEVERTHRAELVAALGEQRHVA
GQRDGIARHVDDLSRAQLGERVDDGLLGAGARRVEHDGRRLQATALGGARLADEVLQVAV
DARRERRGAHPLRQVVAGELGRDLVALHARDPHGVAEAVAHGGGQQADTAVEVEVRGARV
EEGLVDGGLHGVVERLGRAAVHLPEAARLELELAVVDALGDGVAALRLAVDEEHAHVAVG
GGDEVDPLDAGEALPEGRRAVDAGGGERQRLDGDHPVRARGVRADQAVVGHVQADARAPA
EPVGLIVAGERLHLDVHVDVRHAGERVDHDLPLELALVGEADVAELGAADAVLGGAVDGG
LGPDVRAAVRRRVEHLDRVGAPERLLGVLGDARPHPLAGDRVRDEDHPAVVPGHGDPSVR
HVRHVHLDLAAHLLTHPATLTHAGAARTHTRQRTAPLTHAGAARTHTRQRTAPLTHTGVS
PGRADAARACHHVGVTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
PLGAEAMVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDDVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|2.1425.peg.1839|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
PLGAEAMVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDDVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|6666666.374469.peg.292|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
PLGAEAMVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDDVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|6666666.68540.peg.140|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
PLGAEAMVQLLARAKAEAVVGQLVAGAPLTGLVLGGDSAFEIDDVVHGKPHTVERATERW
RAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLLVA
GSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAGRLL
