>fig|2.1421.peg.1488|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSDIENPRDPADRDLDDTGVDEEELVG
AADRDAREAIDAERVVPL-EADAVEADDADGGLGIDITESDGPDLEAGDDLDTGAAIR
>fig|33013.175.peg.415|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MPLDDDDGVADDDADGGLGIDITESDGPDLEAGDDLDPRAAIR
>fig|6666666.374469.peg.2084|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSDIENPRDPADRDLDDTGVDEEELVG
ADAREAQEAVDAERIVPL-DDDGVADDDADSGLGIDITESDGPDLEAGDDLDTGAAIR
>fig|6666666.68540.peg.1421|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSDIENPRDPADRDLDDTGVDEEELVG
ADAREAQEAVDAERIVPL-DDDGVADDDADGGLGIDITESDGLDLEAGDDLDTGAAIR
>fig|2.1418.peg.2562|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSDIENPRDPADRDLDDTGVDEEELVG
ADAREAQEAVDAERIVPLDDDDGVADDDADGGLGIDITESDGPDLEAGDDLDTGAAIR
>fig|33013.181.peg.1643|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSDIENPRDPADRDLDDTGVDEEELVG
ADAREAQEAVDAERIVPLDDDDGVADDDADGGLGIDITESDGPDLEAGDDLDTGAAIR
>fig|2.1425.peg.2376|594242
MRVQRGRREPDRQRALARLSHPPPARAREADHGRRHGALHEPGRLDREHAARGAHGSRPR
VDPRGRHERRAPAAAARLPGADGRARPLRLRLRDEVGHRAQGHDLRRGRRLLVDPRLDRA
RPHQDGLPHRHPALRRARGRGTHRDRRHGLGAAHRHREGGGARRRGRLGRGDAGRRRRCR
HVAAVVVRVGRGERIPQRRGARHRHHGRDADLRRGAARPRRRDGLAPDHRRRLLSRAALP
SLDGGTGPAGTEPGRVPSTHGASAPHRRAKESTVSDIENPRDPADRDLDDTGVDEEELVG
ADAREAQEAVDAERIVPLDDDDGVADDDADGGLGIDITESDGPDLEAGDDLDTGAAIR
