>fig|2.1421.peg.1412|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MPSHAPDRFDEVPGDLSRVGAHRAPRPRHHRLRVFAWAALATGLLVGLG
VVGLFVIDDRVSFTDIIPSDSSSAEATPAEVPTAAPTTVPGMIVTVLNGTKTSGLSARAS
TVLDKAGWKVGSRANASTSDITTTTVYYYDDADEGAARGLAAALGVGDVQQSDQFRPAEG
TSAATAPRLTAVLGSDYAARG
>fig|33013.175.peg.232|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MGAHRAPRPPHHRFRAFAWAALATGLLVGLG
VVGLFVINDRVSFTDIIPSGGSSEEAAPTEEPTAAPTAVPGMVVTVLNGTRTSGLSARAA
TALQKEGWAIASRLNASSTDIATTTVYYYDDADEGAARGLVAELGVGDVAQSDQFRPAEG
TAAAQASKLTAVLGADYAAKG
>fig|2.1425.peg.2902|594242
MSGTGDRGAPPGRVRPSRGCRARTGRGFRPPDAAARRSLRGAERHGDRVHAEPVAGGGLR
RVVEDVPEVRAAAGADDLDALHAEARVRVQLDGVALLRRVEARPSAVGVELGVAREELGA
AGLAAVDAGALLVQQLAGPGALGGLLAQHRVLLRGELLAPLVVGLLDLVGHVRVLSRWSI
LGAASQRASMDNRRGPPSIPACGGRSAPGCERTRCGAAVPVAVRGHPGMLREALSEAHLV
CGGCRGRSMPWTSARPAPRPLRRPDRIRSSSSMPATARSSTSSGTGRVTPGRRRRPSARP
SASRPRATTSCSDPCSRRARPSPTTRSSSGASCDSARRAPPRAQHAPCPPVSRTDRPRAD
PAPHRGDTRPPMPSHAPDRFDEVPGDLSRVGAHRAPRPPHHRFRAFAWAALATGLLVGLG
VVGLFVINDRVSFTDIIPSGGSSEEAAPTEEPTAAPTAVPGMVVTVLNGTRTSGLSARAA
TALQKEGWAIASRLNASSTDIATTTVYYYDDADEGAARGLVAELGVGDVAQSDQFRPAEG
TAAAQASKLTAVLGADYAAKG
>fig|6666666.68540.peg.1571|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MPSHAPDRFDEVPGDLSRVGAHRAPRPPHHRFRAFAWAALATGLLVGLG
VVGLFVINDRVSFTDIIPSGGSSEEAAPTEEPTAAPTAVPGMVVTVLNGTRTSGLSARAA
TALQKEGWAIASRLNASSTDIATTTVYYYDDADEGAARGLVAELGVGDVAQSDQFRPAEG
TAAAQASKLTAVLGADYAAKG
>fig|2.1418.peg.946|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MPSHAPDRFDEVPGDLSRVGAHRAPRPPHHRFRAFAWAALATGLLVGLG
VVGLFVINDRVSFTDIIPSGGSSEEAAPTEEPTAAPTAVPGMVVTVLNGTRTSGLSARAA
TALQKEGWAIASRLNASSTDIATTTVYYYDDADEGAARGLVAELGVGDVAQSDQFRPAEG
TAAAQASKLTAVLGADYAAKG
>fig|6666666.374469.peg.1916|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MPSHAPDRFDEVPGDLSRVGAHRAPRPPHHRFRAFAWAALATGLLVGLG
VVGLFVINDRVSFTDIIPSGGSSEEAAPTEEPTAAPTAVPGMVVTVLNGTRTSGLSARAA
TALQKEGWAIASRLNASSTDIATTTVYYYDDADEGAARGLVAELGVGDVAQSDQFRPAEG
TAAAQASKLTAVLGADYAAKG
>fig|33013.181.peg.902|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MPSHAPDRFDEVPGDLSRVGAHRAPRPPHHRFRAFAWAALATGLLVGLG
VVGLFVINDRVSFTDIIPSGGSSEEAAPTEEPTAAPTAVPGMVVTVLNGTRTSGLSARSA
TALQKEGWAIASRLNASSTDIATTTVYYYDDADEGAARGLVAELGVGDVAQSDQFRPAEG
TAAAQASKLTAVLGADYAAKG
