>fig|2.1421.peg.930|594133
MAPPTSTSAFGMPAPSRVPLPAATTTTPRRGPSTDAPSVARADGTTGSWLIRPGYRRRRR
APTAGGSGGEDLVEQRGRVLLVGLLREGQLAHEDAARLLEHALLARGQAAILVAAPQVAH
DLGHLQHVARRELLEVRLVAPRPVGGLLRELGAQHREHALHALAADDVAHADHVDVLRRD
LDLEPALADVELEVQLLLAADDALFHLDDGRRPVMRVHDGLADLEDHGLPVPQTAAQGTS
RVPRADGRSRRSASRRLGGSADTRADAPGRPGAGPVRQPEGPVRARTASSIVLAALIAVG
TSSCTFITPQATQISYFPSDGFDATVGDIEVRNAILLSEDGSAAGASLVVTLVNNSGDSQ
RVAFQHELTPGSADRETRTVTAAPGLTKFGAEDSQRIVFDSVDPTPGSLTKIYIQYGDAE
GVEMDVPVLNGDQETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLEDDTN
>fig|6666666.68540.peg.1580|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------MLNGDQETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLGDSTN
>fig|2.1418.peg.937|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MRARTASSIVLAALIAVG
TSSCTFITPQATQISYFPSDGFDATVGDIEVRNAILLTEGGSAAGASLVVTLVNNSGDSQ
RVAFQHELTEGSADRETRTVTAAPGLTKFGAEDSQRITFDSVDPTPGSLTKIYIQYGDAE
GVEMDVPVLNGDQETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLGDSTN
>fig|2.1425.peg.314|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MRARTASSIVLAALIAVG
TSSCTFITPQATQISYFPSDGFDATVGDIEVRNAILLTEGGSAAGASLVVTLVNNSGDSQ
RVAFQHELTEGSADRETRTVTAAPGLTKFGAEDSQRITFDSVDPTPGSLTKIYIQYGDAE
GVEMDVPVLNGDQETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLGDSTN
>fig|33013.181.peg.890|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MRARTASSIVLAALIAVG
TSSCTFITPQATQISYFPSDGFDATVGDIEVRNAILLTEGGSAAGASLVVTLVNNSGDSQ
RVAFQHELTEGSADRETRTVTAAPGLTKFGAEDSQRITFDSVDPTPGSLTKIYIQYGDAE
GVEMDVPVLNGDQETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLGDSTN
>fig|6666666.374469.peg.1905|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MRARTASSIVLAALIAVG
TSSCTFITPQATQISYFPSDGFDATVGDIEVRNAILLTEGGSAAGASLVVTLVNNSGDSQ
RVAFQHELTEGSADRETRTVTAAPGLTKFGAEDSQRITFDSVDPTPGSLTKIYIQYGDAE
GVEMDVPVLNGDQETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLGDSTN
>fig|33013.175.peg.1401|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MRARTASSIVLAALIAVG
TSSCTFITPQATQISYFPSDGFDATVGDIEVRNAILLTEGGSAAGASLVVTLVNNSGDSQ
RVAFQHELTEGSADRETRTVTAAPGLTKFGAEDSQRITFDSVDPTPGSLTKIYIQYGDAE
GVEMDVYVLNGDKETYTNLVPGETGSTPDTKVTTTPGTTEGDEGLGDSTN
