>fig|2.1421.peg.1959|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------M
LRLAYGPRGDGTPGRYVPSGGGLYPLDLHVVARSVTGLEPGIHQLDPLEETLVDVSGLER
ASRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGADPGARRFAEEEASHD
>fig|6666666.374469.peg.1616|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MSTIETDATPERAEAATGPSARADP
ATLASGRSLGSVGPIFSVGGAVDRPAGDPAEDFHEASKITRITHPGWTDVRYAHQMAQEA
QGITDAGPGGATSAPRLLPALPLPRALPLRHELGATLAARRSAEPRTLGRPVELAELATV
LRLAYGPRGDGTPGRFVPSGGGLYPLDLHVVARSVVGLEPGIHQLDPLEETLVDVSGLDR
DGRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGAEPGARRFAEEEASHD
>fig|2.1418.peg.301|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MSTIETDATPERAEAATGPSARADP
ATLASGRSLGSVGPIFSVGGAVDRPAGDPAEDFHEASKITRITHPGWTDVRYAHQMAQEA
QGVTDAGPGGATSAPRLLPALPLPRALPLRHELGATLAARRSAEPRTLGRPVELAELATV
LRLAYGPRGEGTPGRFVPSGGGLYPLDLHVVARSVVGLEPGIHQLDPLEETLVDVSGLDR
DGRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGAEPGARRFAEEEASHD
>fig|33013.181.peg.1048|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MSTIETDATPERAEAATGPSARADP
ATLASGRSLGSVGPIFSVGGAVDRPAGDPAEDFHEASKITRITHPGWTDVRYAHQMAQEA
QGVTDAGPGGATSAPRLLPALPLPRALPLRHELGATLAARRSAEPRTLGRPVELAELATV
LRLAYGPRGEGTPGRFVPSGGGLYPLDLHVVARSVVGLEPGIHQLDPLEETLVDVSGLDR
DGRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGAEPGARRFAEEEASHD
>fig|6666666.68540.peg.1863|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MSTIETDATPERAEAATGPSARADP
ATLASGRSLGSVGPIFSVGGAVDRPAGDPAEDFHEASKITRITHPGWTDVRYAHQMAQEA
QGVTDAGPGGATSAPRLLPALPLPRALPLRHELGATLAARRSAEPRTLGRPVELAELATV
LRLAYGPRGDGTPGRFVPSGGGLYPLDLHVVARSVVGLEPGIHQLDPLEETLVDVSGLDR
DGRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGAEPGARRFAEEEASHD
>fig|33013.175.peg.1382|614133
MRPPPLRRRGLAVAGMSRGGAGVVSPYTGLVEHAHPMAFTPDAIPDALYSGRSADTGFLT
GTESERFSMGPGGSRMEARRSCIGEAVERMSLAGAPGGFRAPLGADARQVGPDAFQRFHP
TQREDPAFHYERAQAGDLLTWMPARSLHRGDAVHVPAQMVVFDDPHRADGHREPHVEPAT
SSGVAAGPHFGFAAGRAVLELIERDAFQRSWLRGSTPPAFDWSGSSRLTDATLRELERLE
ELCGRFGASFTVRVLDAAADVPVLLAVMRSDRIGVAVGCAADFRLDRAILNAVREALHTH
NWCLRLLAEPTIDPEDVVEFEDHIRLHCRPSARPLTAALDASDERVAAIGGPDSWAEGVA
GLDREGIEVLLADITAPEVRAAGFHVVRALSPDLVALDVVHAARFLGHPRLYRRWRDGPA
IDGPADLVHVAHPVPGRAAPPVPAAVPPPSHQEDPMSTIETDATPERAEAATGPSARADP
ATLASGRSLGRVGPIFSVGGAVDRPAGDPAEDFHEASKITRITPPGWTDVRYAHQMAQEA
QGVTDAGPGGATSAPRLLPALPLPRALPLRHELGATLAARRSAEPRTLGRPVELAELATV
LRLAYGPRGEGTPGRFVPSGGGLYPLDLHVVARSVVGLEPGIHQLDPLEETLVDVSGLDR
DGRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGAEPGARRFAEEEASHD
>fig|2.1425.peg.2494|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------M
LRLAYGPRGEGTPGRFVPSGGGLYPLDLHVVARSVVGLEPGIHQLDPLEETLVDVSGLDR
DGRLARFRRAAPSLMAPIPETAAVTVVITGSFERSRCKYGLRGYRLTLLEAGHVGQNALL
VATALGLPVLGWVGFVDHELDAVLGLDGVTQSSLYAISFGGAEPGARRFAEEEASHD
