>fig|2.1421.peg.597|594133
-MRADLSKKPGQVSAMFDEVSSAYDRTNTFLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRHAGNPRIEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMRTVAPALTKLV
SSNASAYEYLNESIQAWPDQATLSSWLREAGFASVEHRDLTAGIVALH------------
------------------------------------------------------------
------------------------------------------------------------
-----------------RGV----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KPAGRHAAP-------RPAAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>fig|33013.175.peg.862|614133
MMRADLSKKPGQVSAMFDEVSSAYDRTNTLLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRLAGNDRVEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMKAVAPSLVKLV
SSNASAYEYLNESIQAWPDQETLASWLREAGFASVEHRNLTAGIVALHAASSRPAVRRSP
SRRVLTAREPPQTRTPIMSPSIPLARRGASVASHASLTERLFSSSDDRRMARSIDDGLAL
VEEQLLREVRFADDVADVTTRYLLDAGGKRVRPMLALLIAQLGEGNTQQVVDAAVAIEIT
HLASLYHDDVMDEADMRRGVPSAQAVWGNSVAILAGDLLFARASKIFADLGPSAIRLQAA
TFERLVLGQLHETIGPRDDQDPLEHYLDVLADKTGSLIACAAQMGVIYSGADPELESAVL
AFGARTGVAFQLVDDVLDLADQPEETGKLAGTDLRAGVATLPLLYLRRLAESDAAAASLL
APGSNATSRTRRRPSPRPTSRQPSPSCATTRSRPAPSRRRTAGPPRQSTRSRPSRRARSR
RRSRASPPPSSSARASCRSSPCRPSRGSAPPRPRTAGTGTTTNRRTSDQAQAGHRGRRAR
GHLRGRHHPEGREAVRRLHRPLRAPPRAVRPGPLRRRARPPAHQGHHRRAARRARPRRHP
HLRQRRLRPRHHAGGPPEALPTRSSSPRARSATPSSTSPASTCRAPTARPTSSTGSTDTR
TSRAIGRSTPARSPSSASATWRATWLACSPSTLTTCCPPRSRTTSTRASSTRPSPTCTSS
AAAVPRRSSSRRWSSASWARCPTST
>fig|2.1425.peg.948|594242
MMRADLSKKPGQVSAMFDEVSSAYDRTNTLLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRLAGNDRVEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMKAVAPSLVKLV
SSNASAYEYLNESIQAWPDQETLASWLREAGFASVEHRNLTAGIVALH------------
------------------------------------------------------------
------------------------------------------------------------
-----------------RGV----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KPAGRHAAP-------RPAAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>fig|6666666.374469.peg.1581|645144
-MRADLSKKPGQVSAMFDEVSSAYDLTNTLLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRLAGNDRVEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMKAVAPSLVKLV
SSNASAYEYLNESIQAWPDQETLASWLREAGFASVEHRNLTAGIVALH------------
------------------------------------------------------------
------------------------------------------------------------
-----------------RGV----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KPAGRHAAP-------RPAAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>fig|6666666.68540.peg.1893|151744
-MRADLSKKPGQVSAMFDEVSSAYDRTNTLLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRLAGNDRVEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMKAVAPSLVKLV
SSNASAYEYLNESIQAWPDQETLASWLREAGFASVEHRNLTAGIVALH------------
------------------------------------------------------------
------------------------------------------------------------
-----------------RGV----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KPAGRHAAP-------RPAAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>fig|2.1418.peg.269|594099
-MRADLSKKPGQVSAMFDEVSSAYDRTNTLLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRLAGNDRVEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMKAVAPSLVKLV
SSNASAYEYLNESIQAWPDQETLASWLREAGFASVEHRNLTAGIVALH------------
------------------------------------------------------------
------------------------------------------------------------
-----------------RGV----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KPAGRHAAP-------RPAAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>fig|33013.181.peg.103|614141
-MRADLSKKPGQVSAMFDEVSSAYDRTNTLLSVGNDQLWRVATTRAVAPVAGERILDLAA
GTGTSSAALAASGAHVVAADFSEGMLEVGRRRLAGNDRVEFVHADATDLPFDDDSFDAVT
ISFGLRNVVEPRKGLDELLRVLKPGGRIVICEFSTPPVPLVRRGYDLYMKAVAPSLVKLV
SSNASAYEYLNESIQAWPDQETLASWLREAGFASVEHRNLTAGIVALH------------
------------------------------------------------------------
------------------------------------------------------------
-----------------RGV----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KPAGRHAAP-------RPAAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
