>fig|2.1421.peg.179|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------MPPVRLTPP-----
----------------------------STTAAMELSRYCVLKAGFEPTFHHHAGTFVES
PAEVDRFLDAVDVGLTLDTGHLVIAGGDPVQAVARWGSRITHLHLKDVDGVELRRVLAAG
GGMREVWSSGAFAAFGRGDVDLASAMTAIEAHGYDGWIVVEQDVLNAPDADIRAFLAERA
EDQRVNREALRPWA
>fig|33013.175.peg.2795|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MTETDTAPAS--------------------
---------------RERRSGPGRRIARPLAVATALALGLSALVASPAEAATVAIADVQG
TGSATPFAGRVVTVEGV------------VTADYRGASGYAGIVIQTPGSGGATDQT---
--------------------------------------------------------PGAS
DGIFVYLASADPAVAIGDLVRVTGTASERQGQTQLAATATDLVRAGVGVPA------ATP
LPDTLRGA--------------DRESLESMLVTPTGDYRVGSAHQLDTFGTLWLSAGADL
-PVKATDVVRPGAEADPLDDAAWSRLVRNTARAAEITR----AAGFEPTFHHHAGTFVES
PEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAELGRVLAAG
GGMREVWSSGAFVAFGLGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIRGFRAERT
EDQRVNREALRTWA
>fig|2.1425.peg.312|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MFQFGW-----------GASLIGLES----------SGPILSFLP-----
----------------------------------EITR----AAGFEPTFHHHAGTFVES
PEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAELGRVLAAG
GGMREVWSSGAFVAFGLGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIRGFRAERT
EDQRVNREALRTWA
>fig|6666666.374469.peg.500|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPLSDDDAFQASLPELAASLRVFQEAAESGPTRLPLPTLADA
GSATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITR----AAGFEPTFHHHAGTFVES
PAEIDRFLDAVDVGLTLDTGHLVIAGGDPLAAISRWGARITHLHLKDVDAAELRRVLAAG
GGMREVWSSGAFVAFGRGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIRGFRAERT
EDQRVNREALRTWA
>fig|6666666.68540.peg.2866|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MRGSDAVVARGRHEHALERLAVGAAERVGQRGGGGHADAGPHEVR
RGRGELGLALALGRGARDADEVADRDGRVGAREVDEDPVGGAGRLVGRAAGARGLDHDAG
IPARPAVVGGDDALDRDDATGERGRAAGALHVGDGDGRGLGGRRDERGQAERQGGRDGER
AGDAAPRAGSALSGCGCGVGLGHGVVPLGVAVPPRGGSPVERRPGATPGGGPPPDRHRLV
TRSSRHAGAGRPARWRGTAATYYRQDKHPPYGPRSSATPHGPDPHHPRIPRRLDGPPEPT
RGIRRVRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPLSDDDAFQASLPELAASLRVFQEAAESGPTRLPLPTLADA
GSATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITR----AAGFEPTFHHHAGTFVES
PEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAELGRVLAAG
GGMREVWSSGAFVAFGRGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIRGFRAERT
EDQRVNREALRAWA
>fig|33013.181.peg.1941|614141
MACAASAAACSLRAATSTARTSSMSDSSAGAGSAPAWLKISVWSLKIISVGMAEMFACCA
RNCCDSVSTLPWTMSACFSLDLSKTGANCLQGPHQSAQKSTTTMPLESTMLSKFSAVSSV
VAMVRPLLVLGSCGLGVQPGARPAHSASGRRLPDEDDRRPDGARPLRLVVARVARGEQVD
PAGQARQRHGRAAGVGRRDVDGGDRAAPVEDLHAAGRSRRAGGELHRVPHRLPAADEQAV
GVPDEGRRVADRVEADLHGVVVARAEGAGSVRRGPAVLARGPLRCVDVPDADARDRGGAR
AGGEHVVERSDLAVERVRALAGRLRGHEVDEAGVTEDLDRVLLRVGVEVAEEVDEVGSAR
RLELAREARDGLRLRDAVGVEEPLAVGRLRSGPGLRLEVVRDHREGPVAAAEGLRDGLAR
VAPDRLVDLRGRLAHGRHGVRAVDDRVLDLVGRRRLQLGGRAHVVPHGLPRGVVEAAHEV
GRRGVRRLAEARRVLDLHQRHDLRVEAGDGRDDLRALLPELLRGGGAALPERREVVEDVE
PGDADVAAHLGRGRRTRVPAREGRHAAGRVERRERRRGLEAPVVEAVGEHVRDGREDRDV
AVADHAVGRVVGLRRARGIGRVRELDVVAVVEQEPARAVVGGDPVGLGARPHDVGGLDGQ
IRAGAQPERAEGVELVRGSDAVVARGRHEHALERLVVGAAERVGQRGGGGHADAGPHEVR
RGRGELGLALALGRGARDADEVADRDGRVGAREVDEDPVGGAGRLVGRAAGARGLDHDAG
IPARPAVVGGDDALDRDDATGERGRAAGALHVGDGDGRGLGGRRDERGQAERQGGRDGER
AGDAAPRAGSALSGCGCGVGLGHGVVPLGVAVPPRGGSPVERRPGATPGGGPPPDRHRLV
TRSSRHAGAGRPARWRGTAATYYRQDKHPPYGPRSSATPHGPDPHHPRIPRRLDGPPEPT
RGIRRVRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPLSDDDAFQASLPELAASLRVFQEAAESGPTRLPLPTLADA
GSATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITR----AAGFEPTFHHHAGTFVES
PEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAELGRVLAAG
GGMREVWYSGAFVAFGLGDVDLASVMTAIEAQGSDGWVVVEQDVLNAPDADIRGFRAERT
EDQRVKREALRTWA
>fig|2.1418.peg.1435|594099
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------MD
PAGQARQRHGRAAGVGRRDVDGGDRAAPVEDLHAAGRSRRAGGELHRVPHRLPAADEQAV
GVPDEGRRVADRVEADLHGVVVARAEGAGSVRRGPAVLARGPLRCVDVPDADARDRGGAR
AGGEHVVERSDLAVERVRALAGRLRGHEVDEAGVTEDLDRVLLRVGVEVAEEVDEVGSAR
RLELAREARDGLRLRDAVGVEEPLAVGRLRSGPGLRLEVVRDHREGPVAAAEGLRDGLAR
VAPDRLVDLRGRLAHGRHGVRAVDDRVLDLVGRRRLQLGGRAHVVPHGLPRGVVEAAHEV
GRRGVRRLAEARRVLDLHQRHDLRVEAGDGRDDLRALLPELLRGGGAALPERREVVEDVE
PGDADVAAHLGRGRRTRVPAREGRHAAGRVERRERRRGLEAPVVEAVGEHVRDGREDRDV
AVADHAVGRVVGLRRARGIGRVRELDVVAVVEQEPARAVVGGDPVGLGARPHDVGGLDGQ
IRAGAQPERAEGVELVRGSDAVVARGRHEHALERLAVGAAERVGQRGGGGHADAGPHEVR
RGRGELGLALALGRGARDADEVADRDGRVGAREVDEDPVGGAGRLVGRAAGARGLDHDAG
IPARPAVVGGDDALDRDDATGERGRAAGALHVGDGDGRGLGGRRDERGQAERQGGRDGER
AGDAAPRAGSALSGCGCGVGLGHGVVPLGVAVPPRGGSPVERRPGATPGGGPPPDRHRLV
TRSSRHAGAGRPARWRGTAATYYRQDKHPPYGPRSSATPHGPDPHHPRIPRRLDGPPEPT
RGIRRVRATVAGAPVSFGVFELTPEGAEVVTPDDMVEALAETGYAGIDLGPVGYLGRGRE
LRDRLAGAGLELAGGWIQLPLSDDDAFQASLPELAASLRVFQEAAESGPTRLPLPTLADA
GSATRAAAPGRGAEADPLDDAAWSRLVRNTARAAEITR----AAGFEPTFHHHAGTFVES
PEEIDRFLDQVDVGLTLDTGHLVIAGGDPIAAISRWGARITHLHLKDVDAAELGRVLAAG
GGMREVWSSGAFVAFGLGDVDLASVMTAIEAQGYDGWVVVEQDVLNAPDADIRGFRAERT
EDQRVNREALRTWA
