>fig|2.1421.peg.235|594133
MREVGADLGGLLRPAGHGDAPAGDDRGAEERRRVGEVRLDGDLAAGDGGGAHDPEAGLRA
LDDDAALRERADRHLDVRHARQSGARVPEPEPLDEARRREQQARDELAGGGRVDGDLAAR
HLARAVEAEREGAAAVVVDVHAERAERLDRAGHGTAAGARVAVEGDRAEGERGDRRQEAH
DRAGEAALDGDAARELRRGDPQVGTEGAVAVDLLDHRAEGAQRLDHEPRVPRAERGAQRR
GGVGEGGQHQLAVGQALGSRQRHARVERPLGDRRGPRPVVVGHRRMGPVVVVRAEGRTGI
PEDLHGFTRVPGTRPAGPDPGPGRKTRDHEDSTGGPLRRARARRRICLDGQFEEHQSRRA
GRHHRGRREARVGGARGARGGRRAVHGGRRGPAGGRAGRGRGAARGPARRQPRALRGAGA
PLHRPALRRGPAHDAQPRRRAGPGPGDVREGLHGLPPVQAGHEPQGLAVPDPHEHLHQQL
PQEAAGPVQRHHRRARGLAARRSHLRHRHDHALRRGGGHRPPAGQHRQGRAAVHPGGLPD
GRLLRGRRGLLLPGDRRHHEDPRGHRHEPPAPRPPDAAGPPFRLRARAGHLHRAPHWSDQ
MSDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACTEA
APEDLRTQVMEKLRAIQATH
>fig|6666666.68540.peg.460|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MSDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACKEA
APEDLRTQVMDKLRAIQATH
>fig|2.1418.peg.2309|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MSDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACKEA
APEDLRTQVMDKLRAIQATH
>fig|2.1425.peg.139|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MSDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACKEA
APEDLRTQVMDKLRAIQATH
>fig|33013.175.peg.619|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MSDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACKEA
APEDLRTQVMDKLRAIQATH
>fig|6666666.374469.peg.3114|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MSDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACKEA
APEDLRTQVMDKLRAIQATH
>fig|33013.181.peg.1533|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------MGPVVVVRAEGGTGI
PEDLHGFTRVPGSRPAGPDPGPGRITRDHEDSTGGPVRRARARRRICPDGHFREHQSRRA
GRHHRGRRAHRIRRARGARGGRRALHRGGRRPAGGGAGGGRGAPQGPARRQPRALRGAGA
PVHRPAVRRGPAHDAQSRRRAGPGTGDVREGLHGLPPVQAGHEPQGLAVPDPHEHLHQQL
PQEAAGPLQRHHRRARGLAAGRRDERHGDHHALRRGRGHRPPPGQHRQGRAAVHPGGLPH
GRLLRGRRGLLLPGDRRHHEDPRRHRHEPPAPRPPDAAEPAFRLRARAGHLHRAPHWSDE
ISDCGCDKAKKDLEEYLHHELDKADAADIREHMANCPDCAREHRVGVVLRDTVRRACKEA
APEDLRTQVMDKLRAIQATH
