>fig|2.1425.peg.2368|594242
------------------------------------------------------------
--------MTHAADVVDL------------------------------------------
------------------------------------------------------------
---------------------------LAGLAP---------------------------
------------------------------------------------------------
------------------------------------------------------------
-DHPLRLIRD-------------LRPDARANAQRSF----------------------EA
LLEPAE--PGAFT----------YAERY-------------AVAAFVARLHGSD------
--RAAA------------------------------------------------------
------------------------FYADLLG----------------------DADAALV
----------------------------------------------PVID----------
----------GAARQGAT-------------------AGPTGTYRE--------PGLAAE
SVATDPWT-----------------PDAATCDAVGPRLAAVLTHAQADRPAADPRSDIS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>fig|2.1421.peg.1649|594133
MRRRVASGLPRRCGSCGSTACPAPDGPRARARRPRDESTQLEDHLHTWPGNPYPLGATFD
GSGTNFALFSEVAEQVQLCLFEEDGTETRVDVTEVDAHVWHCYLPHVQPGQRYGYRVTGP
YEPENGHRSNPAKLLLDPYAKATCGEFDWHPSLFAYDFGDPSSRNDEDSGPHMMLGVVVN
PFFDWDGDRLPRTPYSETVVYEAHVKGLTQLHPRIPEELRGTYAGIAHPAVIDHLQHLGV
TAIELMPVHQFVQDNTLLEKGLRNYWGYNTIGFFAPHNAYSSTGELGQQVQEFKSMVRAL
HAAGIEVILDVVYNHTAEGNHLGPTLSFKGIDNQAYYRLMEDDPTYYMDYTGTGNSLNVR
HPHSLQLIMDSLRYWVTEMHVDGFRFDLASALAREFYDVDKLATFFELVQQDPVVSQVKL
IAEPWDVGPGGYQVGNFPPQWTEWNGKYRDTVRDFWRGEASSLGEFAARITGSADLYEHS
GRRPVASINFITAHDGFTIADLVSYNEKHNEANGEGNADGESHNRSWNMGAEGPTDDPGI
LTMRGRQQRNMLATMILSQGVPMILHGDELGRTQQGNNNTYAQDNEISWVHWDQADQPLA
EFTASVVRLRKEHPTFRRGRFFDGRPVRRGEGEPLPDIVWLDADATPMVDDDWESGLRAI
GMFLNGNGIRGRDRRGEDIYDTHFLLYFNAHDEPVSFTLPSDEYADAWETVIDTAGVGAD
STALRASSVVDVAAKALVVLRAYTEPEVEPDHSVAASL-AVLTHAQADRPAADPRSDIS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>fig|6666666.68540.peg.570|151744
--------------------------------------------MHTWPGNPYPLGATFD
GSGTNFALFSEAAEQVQLCLIDEDGTETRVDVTEVDAHVWHCYLPHVQPGQRYGYRVTGP
YEPENGHRSNPAKLLLDPYAKATCGEFDWDPSLFAYEFGDPSSRNDEDSGPHMMLGVVVN
PFFDWDGDRLPRTPYSETVVYEAHVKGLTQLNPRIPEELRGTYAGIAHPAVIDHLQRLGI
TAIELMPVHQFVQDNTLLEKGLRNYWGYNTIGFFAPHNAYSSTGELGQQVQEFKSMVRAL
HAAGIEVILDVVYNHTAEGNHLGPTLSFKGIDNQAYYRLMEDDPTYYMDYTGTGNSLNVR
HPHALQLIMDSLRYWVTEMHVDGFRFDLASALAREFYDVDKLATFFELVQQDPVVSQVKL
IAEPWDVGPGGYQVGNFPPQWTEWNGKYRDTVRDFWRGEASSLGEFAARITGSADLYEHS
GRRPVASINFITAHDGFTIADLVSYDEKHNEANGEDNKDGESHNRSWNMGVEGPTDDPTI
ATLRGRQQRNMLATMILSQGVPMILHGDELGRTQQGNNNTYAQDNEISWVHWDQADQPLV
EFTASVVRLRKEHPTFRRGRFFDGRPVRRGEGEPLPDIVWLDADATPMVDDDWESGLRAI
GMFLNGNGIRGRDRRGEDIYDTHFLLYFNAHDEPVSFTLPSDEYADAWETVIDTAGVGAD
STALRASSVVDVAAKALVVLRAYTEPEVEPDHSVAASL-AVLTHAQADRPAADPRSDIS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>fig|6666666.374469.peg.3000|645144
--------------------------------------------MHTWPGNPYPLGATFD
GSGTNFALFSEAAEQVQLCLIDEDGTETRVDVTEVDAHVWHCYLPHVQPGQRYGYRVTGP
YEPENGHRSNPAKLLLDPYAKATCGEFDWDPSLFAYEFGDPSSRNDEDSGPHMMLGVVVN
PFFDWDGDRLPRTPYSETVVYEAHVKGLTQLNPRIPEELRGTYAGIAHPAVIDHLQRLGI
TAIELMPVHQFVQDNTLLEKGLRNYWGYNTIGFFAPHNAYSSTGELGQQVQEFKSMVRAL
HAAGIEVILDVVYNHTAEGNHLGPTLSFKGIDNQAYYRLMEDDPTYYMDYTGTGNSLNVR
HPHALQLIMDSLRYWVTEMHVDGFRFDLASALAREFYDVDKLATFFELVQQDPVVSQVKL
IAEPWDVGPGGYQVGNFPPQWTEWNGKYRDTVRDFWRGEASSLGEFAARITGSADLYEHS
GRRPVASINFITAHDGFTIADLVSYDEKHNEANGEDNKDGESHNRSWNMGVEGPTDDPTI
ATLRGRQQRNMLATMILSQGVPMILHGDELGRTQQGNNNTYAQDNEISWVHWDQADQPLV
EFTASVVRLRKEHPTFRRGRFFDGRPVRRGEGEPLPDIVWLDADATPMVDDDWESGLRAI
GMFLNGNGIRGRDRRGEDIYDTHFLLYFNAHDEPVSFTLPSDEYADAWETVIDTAGVGAD
STPLRASSVVDVAAKALVVLRAYTEPEVEPDHSVAASL-AVLTHAQADRPAADPRSDIS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>fig|2.1418.peg.2200|594099
--------------------------------------------MHTWPGNPYPLGATFD
GSGTNFALFSEAAEQVQLCLIDEDGTETRVDVTEVDAHVWHCYLPHVQPGQRYGYRVTGP
YEPENGHRSNPAKLLLDPYAKATCGEFDWDPSLFAYEFGDPSSRNDEDSGPHMMLGVVVN
PFFDWDGDRLPRTPYSETVVYEAHVKGLTQLNPRIPEELRGTYAGIAHPAVIDHLQRLGI
TAIELMPVHQFVQDNTLLEKGLRNYWGYNTIGFFAPHNAYSSTGELGQQVQEFKSMVRAL
HAAGIEVILDVVYNHTAEGNHLGPTLSFKGIDNQAYYRLMEDDPTYYMDYTGTGNSLNVR
HPHALQLIMDSLRYWVTEMHVDGFRFDLASALAREFYDVDKLATFFELVQQDPVVSQVKL
IAEPWDVGPGGYQVGNFPPQWTEWNGKYRDTVRDFWRGEASSLGEFAARITGSADLYEHS
GRRPVASINFITAHDGFTIADLVSYDEKHNEANGEDNKDGESHNRSWNMGVEGPTDDPAV
LTLRGRQQRNMLATMILSQGVPMILHGDELGRTQQGNNNTYAQDNEISWVHWDQADQPLV
EFTASVVRLRKEHPTFRRGRFFDGRPVRRGEGEPLPDIVWLDADATPMVDDDWESGLRAI
GMFLNGNGIRGRDRRGEDIYDTHFLLYFNAHDEPVSFTLPSDEYADAWETVIDTAGVGAD
STALRASSVVDVAAKALVVLRAYTEPEVEPDHSVAASL-AVLTHAQADRPAADPRSDIS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>fig|33013.175.peg.48|614133
--------------------------------------------MHTWPGNPYPLGATFD
GSGTNFALFSEAAEQVQLCLIDEDGTETRVDVTEVDAHVWHCYLPHVQPGQRYGYRVTGP
YEPENGHRSNPAKLLLDPYAKATCGEFDWDPSLFAYEFGDPSSRNDEDSGPHMMLGVVVN
PFFDWDGDRLPRTPYSETVVYEAHVKGLTQLNPRIPEELRGTYAGIAHPAVIDHLQRLGI
TAIELMPVHQFVQDNTLLEKGLRNYWGYNTIGFFAPHNAYSSTGELGQQVQEFKSMVRAL
HAAGIEVILDVVYNHTAEGNHLGPTLSFKGIDNQAYYRLMEDDPTYYMDYTGTGNSLNVR
HPHALQLIMDSLRYWVTEMHVDGFRFDLASALAREFYDVDKLATFFELVQQDPVVSQVKL
IAEPWDVGPGGYQVGNFPPQWTEWNGKYRDTVRDFWRGEASSLGEFAARITGSADLYEHS
GRRPVASINFITAHDGFTIADLVSYDEKHNEANGEDNKDGESHNRSWNMGVEGPTDDPAV
LTLRGRQQRNMLATMILSQGVPMILHGDELGRTQQGNNNTYAQDNEISWVHWDQADQPLV
EFTASVVRLRKEHPTFRRGRFFDGRPVRRGEGEPLPDIVWLDADATPMVDDDWESGLRAI
GMFLNGNGIRGRDRRGEDIYDTHFLLYFNAHDEPVSFTLPSDEYADAWETVIDTAGVGAD
STALRASSVVDVAAKALVVLRAYTEPEVEPDHSVAASL-AVLTHAQADRPAADPRSDISW
RTPISTYRFQARESFDLAAVAEQLPYVKDLGADWVYLSPILAAEPGSDHGYDVVDHSQVD
PSRGGAAGMKAVADRAHELGLGVLVDIVPNHVGVATPVESLWWWDLLTHGTASRYADAFD
VDWDFGQGKVRIPVLRDGETELDELTLVRGDDGTVELRYYDQRFPVAPGTAEDAADARTV
HERQSYELINWRRADAELNYRRFFAVNTLAGIRVELPRVFEESHAEISRWFREGLADGLR
VDHPDGLLDPKGYLDDLARITGGAYVLVEKILEPGETLPTDWATAGTTGYDALAEIDRVL
VDPDGQVELDHLEASLRGLPQGELTSWADMIRGTKRGIADGILRSEVLRLERLVEDAAAD
AADALAELLATFPVYRSYLPGGLHHLEEAAEAARASRPDLVATIDALMPQLSDPSPAVAQ
RFQQTSGMVMAKGVEDTAFYRYSRLVSLNEVGADPSIFAIDVDDFHARQQERHRIAPHAM
TTLSTHDTKRGEDVRARIDVLSETPEAWRDALGQLREVAPTGDGPFENLLWQTLVGTWPA
SRERLHAYAEKASREAGDSTTWTAPDEAFAERMHALVDAAFDDPRARTIVAGLYDRLSGP
GWSNSLAAKAIQLTAPGMPDVYQGSELWETSLVDPDNRREVDFGMRRAALDAVLKGAEPA
IDETGAAKLLVTARALRLRREHPELFTGYEPVRATGDAAAPVIAFDRGGAIPVATRLPVG
LETGGGWGSTTITLPEGELVDHVSGRRLDGGRVSVAALLADYPVAILAPASTAADLTPGS
RA
>fig|33013.181.peg.758|614141
------------------------------------------------------------
---------------MQLCLIDEDGTETRVDVTEVDAHVWHCYLPHVQPGQRYGYRVTGP
YEPENGHRSNPAKLLLDPYAKATCGEFDWDPSLFAYEFGDPSSRNDEDSGPHMMLGVVVN
PFFDWDGDRLPRTPYSETVVYEAHVKGLTQLNPRIPEELRGTYAGIAHPAVIDHLQRLGI
TAIELMPVHQFVQDNTLLEKGLRNYWGYNTIGFFAPHNAYSSTGELGQQVQEFKSMVRAL
HAAGIEVILDVVYNHTAEGNHLGPTLSFKGIDNQAYYRLMEDDPTYYMDYTGTGNSLNVR
HPHALQLIMDSLRYWVTEMHVDGFRFDLASALAREFYDVDKLATFFELVQQDPVVSQVKL
IAEPWDVGPGGYQVGNFPPQWTEWNGKYRDTVRDFWRGEASSLGEFAARITGSADLYEHS
GRRPVASINFITAHDGFTIADLVSYDEKHNEANGEDNKDGESHNRSWNMGVEGPTDDPAV
LTLRGRQQRNMLATMILSQGVPMILHGDELGRTQQGNNNTYAQDNEISWVHWDQADQPLV
EFTASVVRLRKEHPTFRRGRFFDGRPVRRGEGEPLPDIVWLDADATPMVDDDWESGLRAI
GMFLNGNGIRGRDRRGEDIYDTHFLLYFNAHDEPVSFTLPSDEYADAWETVIDTAGVGAD
STALRASSVVDVAAKALVVLRAYTEPEVEPDHSVAASL-AVLTHAQADRPAADPRSDIS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
