>fig|33013.181.peg.1031|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------MGAPGR
PLSARRRVRGSSRVGGAGDDGRMTDARPQPDDERRTEVLVRRSPRYFRFMGVGAVLGIIV
AMVITLTFPPNPEFSEAQVLAFLALFAVVLFGGLAALIALALDRAASRRSRVLTPERERG
EPGA
>fig|2.1418.peg.1471|594099
MLRPVERQPPDGLVDARPRLHERGPRRDDAEHPPARGDEPRLRLRGGGVRDAHALDALRL
VHARDDASRPGRLRVALARDHHGDGDVVGELRPRDAAELAGRGREQQLRERRDEAGQHDL
RLRIPEARVELDDPDAVRGEDEPAVEQPDERRLLLRELPHGGQRDGVDDLVDEAGRQPRQ
RRVRAHAARVRSGVAVAQALVVLRGGERDHVVPVGEEEERHLLPGEELLDEHGALAEVVP
RVLEGERAVGGDQHALAGREAVRLDDVGGAVLVERRLDLVDGAGLGGSARGDARLLHDAL
GEGLGSLQRGGGAARPEDRDAPRAQRVRDPGDERRLGPHDDQLEALRERVLRDDDRVVDV
HLHDGHDACYPCVAGRRDELVARVLPEQGRDDGVLARTGTEYQDLHAPTLSTPTPPVRAP
GGAGGRGASASRDGGRRPGGGWEADPPRVRRGSAPCPLRRSSGPPAGTSSLPSRGRGRPR
EGGRPAVPGGSCHRGALPYTVMDVPQSADAGRRPIRRGAATAGERPDPAALASWDDGQGA
HPPHRRTARRAGRARQGRRRRPGDAGHRGPLPAAVARGSRTRRHRRGARPAVRRRPVHRG
PGPHARHAPERHRDRPRHVDRARDGRHDLGRGRRGGCRARVRAPRRPPRPPPRAVGAPGR
PLSARRRVRGSSRVGGAGDDGRMTDARPQPDDERRTEVLVRRSPRYFRFMGVGAVLGIIV
AMVLTLTFPPNPEFSEAQVLAFLALFAVVLFGGLAALIALALDRAASRRSRVLTAERERG
EPGA
>fig|6666666.68540.peg.2832|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------MHRG
PGPHARHAPERHRDRPRHVDRARDGRHDLGRGRRGGCRARVGAPRRPPRPPPRAVGAPGR
PLSARQRVRGSSRVGGAGDDGRMTDARPQPDDERRTEVLVRRSPRYFRFMGVGAVLGIIV
AMVLTLTFPPNPEFSEAQVLAFLALFAVVLFGGLAALIALALDRAASRRSRVLTAERERG
EPGA
>fig|33013.175.peg.938|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------MTDARPQPDDERRTEVLVRRSPRYFRFMGVGAVLGIIV
AMVLTLTFPPNPEFSEAQVLAFLALFAVVLFGGLAALIALALDRAASRRSRVLTAERERG
EPGA
>fig|6666666.374469.peg.536|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------MTDARPQPDDERRTEVLVRRSPRYFRFMGVGAVLGIIV
AMVLTLTFPPNPEFSEAQVLAFLALFAVVLFGGLAALIALALDRAASRRSRVLTAERERG
EPGA
