>fig|6666666.68540.peg.368|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MIIAVVLAFSAAVSLRDGIVPLWAFLGLTGG
GIAAGLLLYAVKPARLRWLLIALVVGLAVALRVSAMPGAMAPWLLGVVAGSFLSRDEWPW
RRSPEERQRERQPRPLASIRPWSGSGLMASLAEVPIGRRGATETGVLLAAGGVTARVRVD
ELHRLVSGRAGIAESVDSDDADSSGRTVYLTRVDTSSPDSIVGEVLVGLPGDALAFLRIT
DPMPASPEAVLTGSDLVAFREWALTVPAP
>fig|6666666.374469.peg.59|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MSAPKPSRAPRTVRERRGSMILTGAILAVVLAFSAAVSLRDGIVPPWAFLGLTGG
GIAAGLLLYAVKPAGLRWLLIALVVGLAVALRISAMPGAMAPWLLGVVAGSFLSRDEWPW
RRSPEERQRERQPRPLASIRPWSGSGLTASLAEVPIGRRGATETGVLLAAGGVTARVRVD
ELHRLVSGRAGIAESVDSDDADSSGRTVYLTRVDTSSPDSIVGEVLVGLPGDALAFLRIT
DPMPASPEAVLTGSDLVGFREWALTVPAP
>fig|33013.181.peg.144|614141
MSAFSPPCGPVVGWTDGDVVRATGIPYATAARFAPPVPHPDWTEPRAATSWAPACPQPPM
EELDAVLGSFAGLAVDEDCLRVSVTMPRDVRPDDALPVLVWLHGGSYVSGAGDVPIMDPA
PLVAEQRVVVVTVTYRLGLLGYLGDGRDRPANLGLLDQLEAFRWVARNIRAFGGDPDRVT
AFGQSAGGDAVAQLLAVPEAAGLFRRAIVQSAPLGISRGRGRMAAAMARASRGLTAEMPV
AEVLARQAEVERAAVPFGLLGAMPFGTQYGHAPLPPESGIDAAWDAAAPGEDVLIGNTAE
EARLFLPGIPWLARLTRLPVAGPLVRRAAVAAVTGIVYGVPGRRLRPTPRARRRHGAPLR
DPLVGARQPVRRRAHRGPAAALRRRGGVARRRPPRRRGLGGDPARRPARAAGVGRLRARA
DPDEAADPGRAGAAARARLRRADARSRAARHPLGGRGARRGGSSRPAGWADPHPDAVRAA
APEEPMSASKPSRAPRNVRERRGSMILTGAIIAVVLAFSAAVSLRDGIVPPWAFLGLTGG
GIAAGLLLYAVKPAGLRWLLIALVVGLAVALRISAMPGAMAPWLLGVVAGSFLSRDEWPW
RRSPEERQRERQPRPLASIRPWSGSGLTASLAEVPIGRRGATETGVLLAAGGVTARVRVD
ELHRLVSGRAGIAESVDSDDADSSGRTVYLTRVDTSSPDSIVGEVLVGLPGDARAFLRIT
DPMPASPEAVLTGSDLVAFREWALTVPAP
>fig|2.1418.peg.1014|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MSASKPSRAPRNVRERRGSMILTGAIIAVVLAFSAAVSLRDGIVPPWAFLGLTGG
GIAAGLLLYAVKPAGLRWLLIALVVGLAVALRISAMPGAMAPWLLGVVAGSFLSRDEWPW
RRSPEERQRERQPRPLASIRPWSGSGLTASLAEVPIGRRGATETGVLLAAGGVTARVRVD
ELHRLVSGRAGIAESVDSDDADSSGRTVYLTRVDTSSPDSIVGEVLVGLPGDALAFLRIT
DPMPASPEAVLTGSDLVAFREWALTVPAP
>fig|33013.175.peg.2627|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MSASKPSRAPRNVRERRGSMILTGAIIAVVLAFSAAVSLRDGIVPPWAFLGLTGG
GIAAGLLLYAVKPAGLRWLLIALVVGLAVALRISAMPGAMAPWLLGVVAGSFLSRDEWPW
RRSPEERQRERQPRPLASIRPWSGSGLTASLAEVPIGRRGATETGVLLAAGGVTARVRGD
ELHRLVSGRAGIAESVDSDDADSSGRTVYLTRVDTSSPDSIVGEVLVGLPGDALAFLRIT
DPMPASPEAVLTGSDLVAFREWALTVPAP
