>fig|33013.181.peg.2081|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--MSTPDAPFSLRAVALPALLPALLFSIGEGAIIPIIPIVAGSLGASLAIAAFIGGMIMI
GELVGDIPSGSVVSRIGERTAMIGAAFVSIGGLVLCLLAPNPLVLGIGVFLIGVSTAVFA
LARHAFMTSFVPQAYRARALSTLGGTFRAGYFVGPFLAAGVIHLTGASQSAFVIHIVACL
AAAVTLLVLPDPMDVVRRNRTADLRSAAPAT-----------------PASRRTTSP---
-WR---------------------------------------------------------
------------------------------RPRAPL------------------------
-------PQRASRP------------------------------------------GSRA
RC----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------GGSRACS------------------------------------------
------------------------------------------------------
>fig|33013.175.peg.384|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MTFCAFSVSSQRSGTHRLG
AQLLDLLLQALDADHRADVGVGVAQFCDPRREVLVDHGAAQPTVRAVGGVRGGGRPRVGS
GAMSTPDAPFSLRAVALPALLPALLFSIGEGAIIPIIPIVAGSLGASLAIAAFIGGMIML
GELVGDIPSGSVVSRIGERTAMIGAAFVSIGGLVLCLLAPNPLVLGIGVFLIGVSTAVFA
LARHAFMTSFVPQAYRARALSTLGGTFRAGYFVGPFLAAGVIHLTGASQSAFVIHIVACL
AAAVTLLVLPDPMDVVRRNRTADLRSAAPATAGEPQDDESVAATAGAAPPARESAGLART
LWRFKGVLVKLGSGAALIGAMRAGRGVLLPLWAVSIGISDANTALLIGIAGGVDFALFYA
SGQIMDRFGRLWSAVPSMVGLGLGYLVLAFTPDLPTSVQWFIGVAMFMSVANGVGSGILM
TLGADLAPREDPAPFLGAWRFTGDAGSAASPLLIAALTSAASLAVASGVMGVLGLIGAGI
PCGTSRGMCRGSRGRPPEGHSPTSRRPDRRGARPHQHAAGGARDVDAHAVGGEQRGDRRD
PRGGEGDARAAAVRRRGAVDAEVVDAGRRLVGEERRDRGGDARVREGRERDAVVADRDSR
RSAPVHVEGLGARQRGRVREGEEPDAFEVERGRRGHHEDHGEAERAGRDHERKDRTLVLG
RGDRRDRRAAATRPRPAGGHRPPRAKTETRSSASPWTATDPGASGPATGGARGSSAATRT
DTCTSDRGAWQLCGSGVHVMSRAIPPGAIPWSASATSTADRASRRPAASSSART
>fig|6666666.374469.peg.3129|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--MSTPDAPFSLRAVALPALLPALLFSIGEGAIIPIIPIVAGSLGASLAIAAFIGGMIML
GELVGDIPSGSVVSRIGERTAMIGAAFVSIGGLVLCLLAPNPLVLGVGVFLIGVSTAVFA
LARHAFMTSFVPQAYRARALSTLGGTFRAGYFVGPFLAAGVIHLTGASQSAFVIHIVACL
AAAVTLLVLPDPMDVVRRNR-ADLQSAAAATAGEPQDDESVGASAGAAPPARESAGLART
LWRFKGVLVKLGSGAALIGAMRAGRGVLLPLWAVSIGISDANTALIIGIAGGVDFALFYA
SGQIMDRFGRLWSAVPSMVGLGIGYLVLALTPDLPTNVQWFIGVAMFMSVANGVGSGILM
TLGADLAPREDPAPFLGAWRFTGDAGSAASPLLIAALTSAASLAVASGVMGVLGLIGAGI
LV----------------------------------------------------------
------------------------------------------------------------
RYVPRYV-----------------------------------------------------
----------PRKPRPTA------------------------------------------
------------------------------------------------------
>fig|6666666.68540.peg.447|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--MSTPDAPFSLRAVALPALLPALLFSIGEGAIIPIIPIVAGSLGASLAIAAFIGGMIML
GELVGDIPSGSVVSRIGERTAMIGAAFVSIGGLVLCLLAPNPLVLGIGVFLIGVSTAVFA
LARHAFMTSFVPQAYRARALSTLGGTFRAGYFVGPFLAAGVIHLTGASQSAFVIHIVACL
AAAVTLLVLPDPMDVVRRNRTADLRSAAPATAGEPQDDESVAATAGAAPPARESAGLART
LWRFKGVLVKLGSGAALIGAMRAGRGVLLPLWAVSIGISDANTALLIGIAGGVDFALFYA
SGQIMDRFGRLWSAVPSMVGLGLGYLVLAFTPDLPTSVQWFIGVAMFMSVANGVGSGILM
TLGADLAPREDPAPFLGAWRFTGDAGSAASPLLIAALTSAASLAVASGVMGVLGLIGAGI
LV----------------------------------------------------------
------------------------------------------------------------
RYVPRYV-----------------------------------------------------
----------PRKPRPTA------------------------------------------
------------------------------------------------------
>fig|2.1418.peg.2322|594099
MLRAEVLDHLVRREHVAAHLVAPARGDVAGELLLGGRLLLALHEEQARLQHPEGGGAVLD
LALLVLAGDDDAGRQVGDAYGRVGRVHGLAAGAGRAEDVDAHLVLGDLDRLRLLDERHDL
DCRERRLALPRGVEGAHAHEAVRAGLDRERAECVRRVDLEGGGLDARLLRVGGVEHGGGV
VVLLGPAQVHAHQHLGEVRGVDAAGARADRDDRGARVELAVEERLHLELVHDLGDAGELD
DRLLGGLLVVLGHLDEHVEVVQAALQLVDALQLRLPVAQVARDLLRLLGVVPEVRLARLG
AQLLDLLLQALDADHRADVGVGVAQFCDPRREVLVDHGAAQPTVRAVGGVRGGGRPRVGS
GAMSTPDAPFSLRAVALPALLPALLFSIGEGAIIPIIPIVAGSLGASLAIAAFIGGMIML
GELVGDIPSGSVVSRIGERTAMIGAAFVSIGGLVLCLLAPNPLVLGIGVFLIGVSTAVFA
LARHAFMTSFVPQAYRARALSTLGGTFRAGYFVGPFLAAGVIHLTGASQSAFVIHIVACL
AAAVTLLVLPDPMDVVRRNRTADLRSAAPATAGEPQDDESVAATAGAAPPARESAGLART
LWRFKGVLVKLGSGAALIGAMRAGRGVLLPLWAVSIGISDANTALLIGIAGGVDFALFYA
SGQIMDRFGRLWSAVPSMVGLGLGYLVLAFTPDLPTSVQWFIGVAMFMSVANGVGSGILM
TLGADLAPREDPAPFLGAWRFTGDAGSAASPLLIAALTSAASLAVASGVMGVLGLIGAGI
LV----------------------------------------------------------
------------------------------------------------------------
RYVPRYV-----------------------------------------------------
----------PRKPRPTA------------------------------------------
------------------------------------------------------
