>fig|33013.175.peg.2552|614133
-----------------------------------------MWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQARHGGAPVVPQWASGRERILLVVAL
VGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDLVCGPLLV
SAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>fig|6666666.68540.peg.664|151744
------------------------------------------------------------
-------------------------------------------MPQWASGRERILLVVAL
VGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDLVGVPLLV
SAGYYASAFMYVFYGAFTLTGLFVWMRARGTDAPAVETAFPDPRIVEAPAER--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>fig|33013.181.peg.1457|614141
MAALEWLFDAQLRIGDQAILWREIVGNLFGLASALGGMRRKVWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQARHGGAPVVPQWASGRERILLVVAL
VGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDLVGVPLLV
SAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAERGVTAPGSL
GPGRPAEVVAHEHAGPRVGHVPDLLGPHVPEPDALVEVDGRRQVDAAAEHDGARSPSSCL
VERGQEQPPPGPPPADGLVDRHLGELPHAVALGDQGHAADDAVPIAGEEHRAAAVDDLAA
GVRQHALVVGLEREQRRDPCLVEGAEGVGVGVAAERRDLDRGGRGRGRALGVRGHGSSFP
AAASRVQYERHRSDSFREWISTSASSAPSSPSPTSGTSAGPPSSSASRSRCCPSRCSASS
AGSA
>fig|6666666.374469.peg.2905|645144
MAALEWLFDAQLRIGDQAILWREIVGNLFGLASALGGMRRKVWAWPVGIVGNVLLFTVFL
GAVFGTPNPVNLLGQAGRQVMFIAVSVYGWYRWQQARHGGAPVVPQWASGRERILLVVAL
VGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDLVGVPLLV
SAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>fig|2.1418.peg.2109|594099
------------------------------------------------------------
------------------------MSVYGWYRWQQARHGGAPVVPQWASGRERILLVVAL
VGGTAILTPVFRALGSYEPVWADAWIFVGSLLATYGMAKGWVEFWLVWVAVDLVGVPLLV
SAGYYASAFMYVFYGAFTLTGFFVWMRARGTDAPAVETAFPDPRIVEAPAER--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
