>fig|6666666.68540.peg.2352|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------MYHHRDVRRVIANACEWARPDRRETPTLLRYE
LGEYYDGTDYAGALER
>fig|2.1418.peg.2774|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------MYHHRDVRRVIANACEWARPDRRETPTLLRYE
LGEYYDGTDYAGALER
>fig|6666666.374469.peg.1036|645144
MTDTASPLRVTVWGENRHEQIEQHVRDRYPTGMHGAVAEGVQENLPDAHVEIATMDQPEH
GLTEELLARTDVLTWWGHAAHAEVDDEVVARVHRHVLDGMGLIVLHSGHWSKIFTKLMGT
TCTLRWRSEHDRELVWTVNPQHPITRGVPNPIVIDEQEMYGEYFDVPTPDELVFISGFTG
GEVFRSGMTYRRGFGRIFFFSPGDQDFPVYHHRDVRRVIANACEWARPDRRETPTLLRYE
LGEYYDGTDYAGALER
