>fig|2.1422.peg.1019|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MRVCLASTSPARLMLLRQAGIEPEARSPQVDEEAVIAEVEATEA
RRLPAPEHVLLLARRKAADVAHRLRAEEPDFDGFVIGGDSMFALGDEILGKPYTPDAATA
RWRGMRGRTGVLHSGHSVFRLSPGSEPREAHAVAEAAVTFAGDVDDAEIAAYVATGEPLL
VAGAFTVDSLGGAFIERVDGDPSTVVGMSLSTVRRLVRELGGSWTELWNRS--------
>fig|2.1421.peg.2044|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MVRVREQVERPDGAELVAALGEQGHVA
GERDGVARHVDDLRGTQLGERVDDGLLGTGARRVEDDGRALQPAALRGARLAHEVLEVAV
DAGGQRRGPHPLRQVVAGELGGDLVALHARDAHGVAEAVAHGGRQQPDAPVEVEVRGARV
EEGLVDRGLDGVVQRLGRAAVHLPEAAGLQLELPVAHALGDGVATLRLAVDEEHAHVAVR
RGDQVDPLDAGEALAEGRRAVDARGGEGQRLDGDHAVRARGVRTHAAVAVDVQADARAPA
EAVRLVVAGERPDLDLAVDARHAGQGVDDDPALELALVRQVDVAELGAADPVLGRAVDRG
LGPHVRTAVRGGVQHLDRVGAPEGLLGVLRDARAHPLAGDRVRDEDHPAVVPGDGDSPVR
DVGHVHLDLAAHLLTHAATLTHAGTPGRRSRSRR--------------------------
----HLGRACHDDPMTTRLHLASTSPARLALLRSAGVEPVVLHSDVDEPAAVAAAEAAHG
-PLAPEEMVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDGVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADIDDDEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGVAWPDLWNRPGAVAARLV
>fig|33013.175.peg.2130|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------MVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|33013.181.peg.1987|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------MVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|2.1418.peg.1237|594099
MEHVALAPAELGLREVAVRVDGGRPLQVVEHVAACDGGDGRHDGLRGRRLGDHPGGTGGQ
RLADARDAVGDAVDEHRGTRALRGLDVVGDGGSVPQREVEDDHVALPADQALDELAGVRG
REDELEPGVEARGLEAEPHRLVVVDDGDADGRTAFGHLIGSLRGLGHPDPPRRVVPSSSD
DRLAHCIARLPRPLGGGCPRSGGGGHQHGHALDVVGVREEVERTHRAELVAALGEQRHVA
GQRDGIARHVDDLSRAQLGERVDDGLLGAGARRVEHDGRRLQATALGGARLADEVLQVAV
DARRERRGAHPLRQVVAGELGRDLVALHARDPHGVAEAVAHGGGQQADTAVEVEVRGARV
EEGLVDGGLHGVVERLGRAAVHLPEAARLELELAVVDALGDGVAALRLAVDEEHAHVAVG
GGDEVDPLDAGEALPEGRRAVDAGGGERQRLDGDHPVRARGVRADQAVVGHVQADARAPA
EPVGLIVAGERLHLDVHVDVRHAGERVDHDLPLELALVGEADVAELGAADAVLGGAVDGG
LGPDVRAAVRRRVEHLDRVGAPERLLGVLGDARPHPLAGDRVRDEDHPAVVPGHGDPSVR
HVRHVHLDLAAHLLTHPATLTHAGAARTHTRQRTAPLTHAGAARTHTRQRTAPLTHTGVS
PGRADAARACHHVGVTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|2.1425.peg.1839|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|6666666.374469.peg.292|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAARLL
>fig|6666666.68540.peg.140|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTTRLHLASTSPARLALLRSAGIEPVVLPSDVDEPAAVAAAEAGQG
-PLGAEAMVQLLARAKAEAVVGQLVAGAP-LTGLVLGGDSAFEIDDVVHGKPHTVERATE
RWRAQRGREGRLHSGHWLIEVADGRIVRGIGRAAVADVRFRADITDAEIDAYVATGEPLL
VAGSFTIDSLGAAFIERIQGDPSTVVGLSLPTLRGLVRELGTEWTDLWNRQGAVAGRLL
