>fig|2.1422.peg.218|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MIAAGLLLVAVG
AVDLLRQMVRSRRWIAFAAAAVALVLVSAALDAVIAGLLAVAVASIWTWVVPEDGPARAG
LWPVALLALAAAACVVIA-PGRARPGLLGAAWATYSPGNAVSIDVVVLVIGCLVFLLESG
NAVVRIALRSEMGGRVELNTRPVASG---TAPVGVDAAAPVAPAPG---LKGGRLIGPLE
RILVFVLTLTGAYTLLAAVLAAKGIVRFPEISRDRDDGDRAEYFLIGSLVSWVTALAAAF
LVWWGVRAG
>fig|2.1421.peg.1252|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPAEVAA------SAVLC------VLVTASL---VLALLAMR-------------SPRTG
LVAASAGALAAALVLGLALAGPASRLVVG------------YLGLVMVVLAVL-----GG
GSASTVVLALATRGSVP----AGAYGGILVPPRGREDDPSAIRRPTREVLRGGATIGMLE
RLAVVAVILAGYPEALAVVIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAA
VVLV-DR--
>fig|33013.181.peg.2522|614141
MFVITADQKGSRTDVDRAGTGRDDLASRFEGRLVLPVDRTSGDELQALVADADTALDMAL
VLTRAGHWSVGLGIGTVRTPLPRATREANRPGLHRRARRGRRGEAQRDEVRARGGSACSP
ETRWSGIRPPGLRTPRPRRGRGAHHAAAPGAGPPHLPGLGRRRPHGRREHAAGGRRRARR
HAPGREHAAARQRVARRAGRDPGARRAARPPRRAGDPRCGHRGIRTAIHRRGDALVIPVG
TPGEITA------WIALC------VLVTAAL---VLALLTVR-------------APRTG
RVVAAAGTLACALALGLALSGPASPLVVG------------FTGLVAVVLAVL-----GG
GSASTVVLALATRGSVP----PGAFGGILVAPRGHEDDASASRRPTREVLRGGATIGLLE
RLAVVAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIFGTLVSWLWAATCAA
VVLV-VR--
>fig|6666666.68540.peg.1115|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------MLVTAAL---VLALLTVR-------------APRTG
RVVAAAGTLACALALGLALSGPASPLVVG------------FTGLVAVVLAVL-----GG
GSASTVVLALATRGSVP----PGAFGGILVAPRGHEDDASASRRPTREVLRGGATIGMLE
RLAVVAVTLAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAA
VVLV-VR--
>fig|2.1425.peg.2772|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------MVVG------------FTGLVAVVLAVL-----GG
GSASTVVLALATRGSVP----PGAFGGILVAPRGHEDDASASRRPTREVLRGGATIGMLE
RLAVVAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAA
VVLV-VR--
>fig|33013.175.peg.542|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPGEITA------WIALC------VLVTAAL---VLALLTVR-------------APRTG
RVVAAAGTLACALALGLALSGPASPLVVG------------FTGLVAVVLAVL-----GG
GSASTVVLALATRGSVP----PGAFGGILVAPRGHEDDASASRRPTREVLRGGATIGMLE
RLAVVAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAA
VVQV-VR--
>fig|2.1418.peg.685|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPGEITA------WIALC------VLVTAAL---VLALLTVR-------------APRTG
RVVAAAGTLACALALGLALSGPASPLVVG------------FTGLVAVVLAVL-----GG
GSASTVVLALATRGSVP----PGAFGGILVAPRGHEDDASASRRPTREVLRGGATIGMLE
RLAVVAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAA
VVLV-VR--
>fig|6666666.374469.peg.2419|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MIPVG
TPGEITA------WIALC------VLVTAAL---VLALLTVR-------------APRTG
RVVAAAGTLACALALGLALSGPASPLVVG------------FTGLVAVVLAVL-----GG
GSASTVVLALATRGSVP----PGAFGGILVAPRGHEDDASASRRPTREVLRGGATIGMLE
RLAVVAVILAGYPEALAVIIAIKGVGRFSELGEAAEARER---FIIGTLVSWLWAATCAA
VVLV-VR--
