>fig|2.1422.peg.930|594139
MSELRVLLVDDHAMMRAGFRTILSLEDDITVVGEAASGRAAIDAARELRPDVICMDVQMP
DMDGLEATRLLTADPASDAAILIVTTFDRDDYLFAALAAGASGFLLKNAGPEELVSAVRI
VGAGDALLAPEVTRRVIERFSAQGAGDVASGSSFASPAPTSTVTETAVRRADTLHLSEPL
TERESEVLALVAEALSNAEIAARLFIGEATVKTHVSNVLQKLGARDRVQAVVLAHRHGLA
-------
>fig|2.1421.peg.1992|594133
MSALL-----DH--------------------GHPARG----------------------
--------------------------------------IGTDAELAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENHVV
EPLGATR
>fig|6666666.68540.peg.2608|151744
MSALV-----DH--------------------GHAAHG----------------------
--------------------------------------MGAD--LAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENRVV
EPLASTR
>fig|6666666.374469.peg.783|645144
MSALV-----DH--------------------GHAAHG----------------------
--------------------------------------MGAD--LAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENRVV
EPLASTR
>fig|2.1418.peg.889|594099
MSALV-----DH--------------------GHAAHG----------------------
--------------------------------------MGAD--LAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENRVV
EPLAMTR
>fig|2.1425.peg.1816|594242
MSALV-----DH--------------------GHAAHG----------------------
--------------------------------------MGAD--LAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENRVV
EPLAMTR
>fig|33013.175.peg.377|614133
MSALV-----DH--------------------GHAAHG----------------------
--------------------------------------MGAD--LAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENRVV
EPLAMTR
>fig|33013.181.peg.2854|614141
MSALV-----DH--------------------GHAAHG----------------------
--------------------------------------MGAD--LAR-------------
-----------------------------------------------------------L
TAREREILVLVARGLSNAEIAGRLFLAPTTVKTHVSRTLDKLGVRDRLHATIWAYENRVV
EPLAMTR
