>fig|2.1422.peg.503|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAGRGARSG-SGRRRG---------VSMIRCAGLGVRLGGREVLRDVSL
DLSARTIALIGDNGSGKSTLARVLAGLVRRTEGDLRVLGCDPDRDPAALRAKVALVLSNP
DAQIMMPTVAEDVALSLRAARLPRRERDARVEAALARFGLDGLGDRPAQDLSGGQKQLLA
LCGAFVREPALVIADEPTALLDGRNARRVADHLLADAGHALVLVTHDLALARRCESAVLI
ADGRVAASGASFDVVDAYEEALAC
>fig|2.1421.peg.1613|594133
MGEERRAQRGGPVAHALVPRSLAGRSTRSVLLRLGDDPVRDLREQALLVREVPVERARLH
LEHGGQAPHREIGEAVLVEDPQGGPGDVVARVPPAAARLRHAATIVNGVQVNAVQEIDPD
PEEEHDHVPARPAGARLPRGRHRPGPRGRPGRGDRRARAAGRHQRPRRRAHHGADPGRDA
RRGDPRSVAGRPLHPGAAGARRRRPAPPLRRHGRDRRLRRADRGLPRRLGARRPRGRRAG
PPRRAEARPRPHRRRHGHRRHPRDLRRRDPRAERRDAPPAPRDPLHEPRLRPGRPGQGRD
RHGHRDDARARLPARLPPSGRVDPRRAAGVRHDDRVTAALRLDGVGVGLGDVDVLADVSL
DLDARTVAVIGENGSGKSTFARLVGGLVPRSSGEVRVLGLDPARDARELRRRVALVFSNP
DAQIVMPTVREDVAFSLRSERLARDESAARVTDALARFGLADLADRPSHDLSGGQKQLLA
LAGAFVRQPELVIADEPTAYLDARNARRVADHLFEE-GHRLVLVTHDLDVARRCDAAVLF
AGGRLTRVGTPVEVVAAYEALLG-
>fig|33013.175.peg.1136|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTPPEG-VD-------------TAALRLVDVGVRLGDVDALRDVTL
EMDARTVAVIGENGSGKSTFARLVGGLVGRTTGELRVLGVDPDRGSRELRRRVALVFSNP
DAQIVMPTVAEDVAFSLRPERLSRAESDARVSECLRRFGIQHLAAPATHELSGGQKQLLA
LAGAFVRRPELVIADEPTAYLDARNARRVADHLFED-GHRLVLVTHDLAAAARCEAAVLF
AGGRLVRTGGPADVIAEYEAMLG-
>fig|2.1418.peg.2010|594099
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTPPEG-VD-------------TAALRLVDVGVRLGDVDALRDVTL
EMDARTVAVIGENGSGKSTFARLVGGLVGRTTGELRVLGVDPDRGSRELRRRVALVFSNP
DAQIVMPTVAEDVAFSLRPERLSRAESDARVSECLRRFGIQHLADRSSHELSGGQKQLLA
LAGAFVRRPELVIADEPTAYLDARNARRVADHLFED-GHRLVLVTHDLAAAARCEAAVLF
AGGRLVRTGGPADVIAEYEAMLG-
>fig|2.1425.peg.1917|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTPPEG-VD-------------TAALRLVDVGVRLGDVDALRDVTL
EMDARTVAVIGENGSGKSTFARLVGGLVGRTTGELRVLGVDPDRGSRELRRRVALVFSNP
DAQIVMPTVAEDVAFSLRPERLSRAESDARVSECLRRFGIQHLADRSSHELSGGQKQLLA
LAGAFVRRPELVIADEPTAYLDARNARRVADHLFED-GHRLVLVTHDLAAAARCEAAVLF
AGGRLVRTGGPADVIAEYEAMLG-
>fig|33013.181.peg.1309|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTPPEG-VD-------------TAALRLVDVGVRLGDVDALRDVTL
EMDARTVAVIGENGSGKSTFARLVGGLVGRTTGELRVLGVDPDRGSRELRRRVALVFSNP
DAQIVMPTVAEDVAFSLRPERLSRAESDARVSECLRRFGIQHLADRSSHELSGGQKQLLA
LAGAFVRRPELVIADEPTAYLDARNARRVADHLFED-GHRLVLVTHDLAAAARCEAAVLF
AGGRLVRTGGPADVIAEYEAMLG-
>fig|6666666.374469.peg.2796|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTPPEG-VD-------------TAALRLVDVGVRLGDVDALRDVTL
EMDARTVAVIGENGSGKSTFARLVGGLVGRTTGELRVLGVDPDRGSRELRRRVALVFSNP
DAQIVMPTVAEDVAFSLRPERLSRAESDARVSECLRRFGIQHLADRSSHELSGGQKQLLA
LAGAFVRRPELVIADEPTAYLDARNARRVADHLFED-GHRLVLVTHDLAAAARCEAAVLF
AGGRLVRTGGPADVIAEYEAMLG-
>fig|6666666.68540.peg.764|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MTPPEG-VD-------------TAALRLVDVGVRLGDVDALRDVTL
EMDARTVAVIGENGSGKSTFARLVGGLVGRTTGELRVLGVDPDRGSRELRRRVALVFSNP
DAQIVMPTVAEDVAFSLRPERLSRAESDARVSECLRRFGTQHLADRSSHELSGGQKQLLA
LAGAFVRRPELVIADEPTAYLDARNARRVADHLFED-GHRLVLVTHDLAAAARCEAAVLF
AGGRLVRTGGPADVIAEYEAMLG-
