>fig|2.1422.peg.2859|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MTRHPYLSPDAPHVLAHRGLVTPDAATLGIAENSFAAVAEA
HAAGAVYVESDCHLTADGVVVLFHDDDLQRVAGDPRAIADVRVHELEELMADRGGLI-TL
AQALEAFPEVRFNLDVKAAAAAEGVGRLV--APHAERVLVTSFSDERRLEALRAAATAGA
AQRPATSPGSATIARLVAARALHQTRRVRALLADVDALQIPEKQGPLRLVTPGLLRDAHA
AGVEVHVWTVNDESDMARLLDAGVDGLVTDRADAALALVNER-----GTAPV
>fig|2.1421.peg.1743|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------MLAVVGARLGLAPVVRLALRGLDAVQMPCRVLGIRTVSPAMVGRLAR
AVREVHVWTVDDPDEAVRLVEAGVHGVVTDRPDLVLAAFDGRDWDSPGNRTS
>fig|6666666.68540.peg.817|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MLGGDRVDDRARDLGRELRDVVETPGRLLAL
LDGLGVHAAEERGGDGALDHVAGDDDEADAPLVELRDELTQGVLPRALAARDGLVLGHRL
GGADEVGLVARDEDDPAALGQERQRAAQDVQLRVAVERHGVVLGHAALHAAGCVQDEHVE
AAELGADGLHEAVDGLGIREVRPDRDGLRAALDQLRDELLGARGLVAVVDDHVGARLGEV
RDRVGADPAGRAGDERAAAAELVGGEGADLVDGAHSGTPPGVRAVRARRVVRRGTDRDGP
RGRDTTLTARRAYRPPSGRWARFGSSGPRSEGAAGDGPARRPRVDRLARPRRDGGRRGDA
AARPDGALRRCRCARGPAVRPRGRALVAAGGRRPRGRVRPARIRATGAAPRPARRGPPRG
RRPRTGRPGCHVRRRRTARVTRSAWFDGAVPRVLAHRGWTGS-----GAVENTLDAFRAA
WELGATHLETDVHVTADGACVLWHDADLRRLTGRPGLVRDATLEELRAIDLGSGARVATL
GELLAALPDARLNIDVKGRDAPAAAARAIRDADAVDRVLVTSFSGSRRRRAL--ALLPGA
----ATSADAGRLVLAVLGARLALAPVVRLALRGVDAVQMPCRVIGIRTVSPMMVGRLGR
AVREVHVWTVDDPGEMIRLVRAGVHGIVTDRADLALAAIGDRDWDSPGNRVS
>fig|6666666.374469.peg.2739|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MTRSAWFDGAVPRVLAHRGWTGS-----GAVENTLDAFRAA
WELGATHLETDVHVTADGACVLWHDADLRRLTGRPGLVRDATLEELRAIDLGSGARVATL
GELLAALPDARLNIDVKGRDAPAAAARAIRDADAVDRVLVTSFSGSRRRRAL--ALLPGA
----ATSADAGRLVLAVLGARLALAPVVRLALRGVDAVQMPCRVIGIRTVSPVMVGRLGR
AVREVHVWTVDDPGEMIRLVRAGVHGIVTDRADLALAAIGDRDWDSPGNRVS
>fig|2.1418.peg.1957|594099
MVLAREDEHLGLDPRPHERQVVPLGLRQRAAEVVLGVDDERRRAHLVRERLRALRATRLL
VVARVLLAEERADVGRAGEQLRVEEPAFDDGALEAVLVRDGPRGEVAAVGAAHDAGAGPV
DGVVHRDRAVEEVEHVVHVDRAHALLDDAAVLLAVAGGAARVAQQHRVAGVGVDLRLVEE
VHAVGGVGPAVDHEEDRVRPLPLRQHDPAVHRVAVAALDHQLVQRSDPRVAQRCGEVGER
DERGAGVGGTVGADEREVAVRARVGEGDHDGPSPDADPGDLDLVVHERLDGAIRGDAQQL
HGAARSVEHEHGVAVLHRDAAAAEVDGLGVREDAWRGVVGVEDVERGVAGDEVHARLPEV
LSQQVDPAALDGRDLRDAEPGLVRHHGADLGHAARGLTASGDRDRVGTREQVVVTAVVAR
GHEQDLGPVGGEARRVVVDGLVGEADDRRDTRALGGGGLRVDAVAAHGGIRGIRVAGRHR
GHEGLRVQRGQIHEEELRVPVRGPAEAVREVLRGGDAAGGLRRGRHALDAPVPPGLGHAR
GIDDARAVGRPVERADTEQLVGEGDRLAAGRPDDVQLRRPLRLRAEERDDRSVRREPRRS
VAEAARDASRRRGPVGGHLPQLAGVRVGVHPRARHRDDGQAAVGRYGGAGDGGEEVEIRG
LHRIEPSPGSSPGPGSLGAEAARVADESEVLGGDRVDDRARDLGRELRDVVETPGRLLAL
LDGLGVHAAEERGGDGALDHVAGDDDEADAPLVELRDELTQGVLPRALAARDGLVLGHRL
GGADEVGLVARDEDDPAALGQERQRAAQDVQLRVAVERHGVVLGHAALHAAGCVQDEHVE
AAELGADGLHEAVDGLGIREVRPDRDGLRAALDQLRDELLGARGLVAVVDDHVGARLGEV
RDRVGADPAGRAGDERAAAAELVGGEGADLVDGAHSGTPPGVRAVRARRVVRRGTDRDGP
RGRDTTLTARRAYRPPSGRWARFGSSGPRSEGAAGDGPARRPRVDRLARPRRDGGRRGDA
AARPDGALRRCRCARGPAVRPRGRALVAAGGRRPRGLVRPARIRATGAAPRPARRGPPRG
RRPRTGRPGCHVRRRRTARVTRSAWFDGAVPRVLAHRGWTGS-----GAVENTLDAFRAA
WELGATHLETDVHVTADGACVLWHDADLRRLTGRPGLVRDATLEELRAIDLGSGARVATL
GELLAALPDARLNIDVKGRDAPAAAARAIRDADAVDRVLVTSFSGSRRRRAL--ALLPGA
----ATSADAGRLVLAVLGARLALAPVVRLALRGVDAVQMPCRVIGIRTVSPVMVGRLGR
AVREVHVWTLDDPGEMIRLVRAGVHGIVTDRADLALAAIGDRDWDSPGNRVS
>fig|33013.175.peg.2473|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MTRSAWFDGAVPRVLAHRGWTGS-----GAVENTLDAFRAA
WELGATHLETDVHVTADGACVLWPDADLRRLTGRPGLVRDATLEELRAIDLGSGARVATL
GELLAALPDARLNIDVKGRDAPAAAARAIRDADAVDRVLVTSFSGSRRRRAL--ALLPGA
----ATSADAGRLVLAVLGARLALAPVVRLALRGVDAVQMPCRVIGIRTVSPVMVGRLGR
AVREVHVWTLDDPGEMIRLVRAGVHGIVTDRADLALAAIGDRDWDSPGNRVS
>fig|33013.181.peg.1974|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MTRSAWFDGAVPRVLAHRGWTGS-----GAVENTLDAFRAA
WELGATHLETDVHVTADGACVLWHDADLRRLTGRPGLVRDATLEELRAIDLGSGARVATL
GELLAALPDARLNIDVKGRDAPAAAARAIRDADAVDRVLGTSFSGSRRRRAL--ALLPGA
----ATSADAGRLVLAVLGARLALAPVVRLALRGVDAVQMPCRVIGIRTVSPVMVGRLGR
AVREVHVWTLDDPGEMIRLVRAGVHGIVTDRADLALAAIGDRDWDSPGNRVS
>fig|2.1425.peg.2597|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------MTRSAWFDGAVPRVLAHRGWTGS-----GAVENTLDAFRAA
WELGATHLETDVHVTADGACVLWHDADLRRLTGRPGLVRDATLEELRAIDLGSGARVATL
GELLAALPDARLNIDVKGRDAPAAAARAIRDADAVDRVLVTSFSGSRRRRAL--ALLPGA
----ATSADAGRLVLAVLGARLALAPVVRLALRGVDAVQMPCRVIGIRTVSPVMVGRLGR
AVREVHVWTLDDPGEMIRLVRAGVHGIVTDRADLALAAIGDRDWDSPGNRVS
