>fig|2.1422.peg.75|594139
---MSFGSASVRPSATDACPCGEGE-FGTHCGPLLDGE-PAPGAERLMRSRYTAFAVGDA
AHLARSWHPRTRPDEIEVGDGTRWIGLDIVSAEEGA---DAAVVSFRARWRHGSEAGELR
ERSRFVRRAGRWVYVDGDVDERGGRAARGEASSPNGRVGGSAYGRERILGERTRMIPDAH
RDLLENPNYGSLGTVRPDGTVQVNPMWFDFDGEHLLFTHTTTRQKFRNLQQNPSMSLMVF
DPAQPYRYIEVRGRLVEAEPDPTGAFYVHLGKRYGNAEQEAPPDSADRVILKMSIEKVGG
Q
>fig|2.1421.peg.2136|594133
MTRLSPDAPWSTPDDDAWCPCTSGDPYGACCGPLHRGDSRAPTAERLMRSRFAAYARGDA
AYLARSWHPSTRPAELDLDPSIRWFRLTIVRTAQGGPDDATGVVEFEAAYRHKGGRGSQH
EASRFARYAGSWVYVD--------------------------------------------
------------------------------------------------------------
------------------------AM----------------------------------
-
>fig|33013.181.peg.1213|614141
-----------------------------------------------MRSRFAAYARGDA
AYLARSWHASSRPEEIDLDPSVRWFRLPIHRTSLGGPDDATGVVDFEASFRHDGERGSQR
EASRFVRHAGPGVYLD--------------------------------------------
------------------------------------------------------------
------------------------AF----------------------------------
-
>fig|6666666.374469.peg.2591|645144
MTRLSPDAPWSTPDDDAWCPCTSGDAYGACCGPLHRGDTAAPTAERLMRSRFAAYARGDA
AYLARSWHASSRPEEIDLDPSVRWFRLTIHRTSLGGPDDATGVVDFEASFRHDGERGSQR
EASRFVRHAESWVYLD--------------------------------------------
------------------------------------------------------------
------------------------AF----------------------------------
-
>fig|2.1418.peg.1813|594099
MTRLSPDAPWSTPDDDAWCPCTSGDAYGACCGPLHRGDTAAPTAERLMRSRFAAYARGDA
AYLARSWHASSRPEEIDLDPSVRWFRLTIHRTSLGGPDDATGVVDFEASFRHDGERGSQR
EASRFVRHAGSWVYLD--------------------------------------------
------------------------------------------------------------
------------------------AF----------------------------------
-
>fig|6666666.68540.peg.960|151744
-----------------------------------------------MRSRFAAYARGDA
AYLARSWHASSRPEEIDLDPSVRWFRLTIHRTSLGGPDDATGVVDFEASFRHDGERGSQR
EASRFVRHAGSWVYLD--------------------------------------------
------------------------------------------------------------
------------------------AL----------------------------------
-
>fig|2.1425.peg.2463|594242
-----------------------------------------------MRSRFAAYARGDA
AYLARSWHASSRPEEIDLDPSVRWFRLTIHRTSLGGPDDATGVVDFEASFRHDGERGSQR
EASRFVRHAGSWVYLD--------------------------------------------
------------------------------------------------------------
------------------------AF----------------------------------
-
>fig|33013.175.peg.573|614133
-----------------------------------------------MRSRFAAYARGDA
AYLARSWHASSRPEEIDLDPSVRWFRLTIHRTSLGGPDDATGVVDFEASFRHDGERGSQR
EASRFVRHAGSWVYLD--------------------------------------------
------------------------------------------------------------
------------------------AF----------------------------------
-
