>fig|2.1422.peg.80|594139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MAREKKTRRASGRRSPLAAAALIGIGLLLTGGVYAGASAAMAAT
SDTPVSEANSATAVEEGQKLFQANCATCHGLDLQGSDQGPSLFGVGELSVHFQVSTGRMP
LQAQGPQAPVKPVQFTEEQTNAIAAYVQSAAPGPSYPSNELLDGEGDLSHGAELFRINCA
MCHNVAGAGGALTEGKYAPDLHSTTPVNIYAAMVTGPQNMPVFNDLNLTPEDKRDVISYL
MYLQKTDSPGGYALGSLGPVSEGLFIWIFGIGALIALTVWITAKSN
>fig|2.1421.peg.1291|594133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MSTTTARARRTGRRSPLTTVALLAIGLLFTGGAYALIQTGTASA
E----VDLKSAQTIDEGQKLFGSNCATCHGMDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAEEKPTQFTDDQVKELAAYVASLAPGPAIPASQYLDGQGDPSNGAELFRINCA
MCHNVAGAGGALTEAKFAPSLKGVDPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEQNSNVGGADLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
>fig|6666666.68540.peg.969|151744
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAPEKPTQFTDTQVKELAAYVASLAPGPAIPDGQYLDGKGDPANGAELFRINCA
MCHNVAAAGGALTEGKFAPSLEGVAPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEENSTVGGANLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
>fig|33013.175.peg.582|614133
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAPEKPTQFTDTQVKELAAYVASLAPGPAIPDGQYLDGKGDPANGAELFRINCA
MCHNVAAAGGALTEGKFAPSLEGVAPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEENSTVGGANLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
>fig|2.1418.peg.1806|594099
MRPSSAARATSTGRRGSGARRRRPLLELRGGAAGVHGVGGDRDLLAQPARHGLLNARRIP
HQVEGLEARRRVQQHDVALRAGLSGEDAADHLRVLLHALAEERLDGSPRDPELERVEVVL
GDRAPADLPDVAVTGGRELVDPVVAPVHERGRAAGPEDAHHERHAREVGDPHRGCLRARR
VAERAEHVEQRRDAELAPRGRCVPEARVEERGVRVGDAGLAEHLRHALRRDAEVDSECRE
HVGRARGGARPAVPVLDDGDARGSGDDRGHRGDVEDGAVRVASRPHDVEGARIRVERQRL
LEDGVAEADDLVDGLAGCPQRDQEPAQLRGSGLPAHHLAHGPGGLGHRQVAPLDQRGDER
GPGRGGGHADQPNERLDRISRAAGWASGVVGLGHNGTCDDHLNLPSIDRAGGEPAEHGRR
RHHRVARQRGDVLRGSLRDLLHPPLHVRCPLGVRGGTPQCALLPREHAHPRVELVHLPVR
RLRGRAAAGAGHGLEAQPVGHGRVVLPHLRPRRHLRRGPDLRVRHPRHRGHHAQQQRLRL
GVLHDHWVPRPARHRRAHRLPPRHRAHLRGPVHGAQGGDERHRRVLLLALRRRRLDRALP
GHLRPQIAPSGSINHSMSTNTARARRTGRRSPLTTIALLAIGLLTTGGAYAMIQSGTASA
E----VDLKSAQTIDEGQKLFGSNCATCHGMDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAPEKPTQFTDTQVKELAAYVASLAPGPAIPDGQYLDGKGDPANGAELFRINCA
MCHNVAAAGGALTEGKFAPSLEGVAPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEENSTVGGANLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
>fig|2.1425.peg.1560|594242
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MSTNTARARRTGRRSPLTTIALLAIGLLTTGGAYAMIQSGTASA
E----VDLKSAQTIDEGQKLFGSNCATCHGMDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAPEKPTQFTDTQVKELAAYVASLAPGPAIPDGQYLDGKGDPANGAELFRINCA
MCHNVAAAGGALTEGKFAPSLEGVAPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEENSTVGGANLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
>fig|33013.181.peg.1223|614141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MSTNTARARRTGRRSPLTTIALLAIGLLTTGGAYAMIQSGTASA
E----VDLKSAQTIDEGQKLFGSNCATCHGMDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAPEKPTQFTDTQVKELAAYVASLAPGPAIPDGQYLDGKGDPANGAELFRINCA
MCHNVAAAGGALTEGKFAPSLEGVAPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEENSTVGGANLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
>fig|6666666.374469.peg.2582|645144
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MSTNTARARRTGRRSPLTTIALLAIGLLTTGGAYAMIQSGTASA
E----VDLKSAQTIDEGQKLFGSNCATCHGMDATGTGVAPSLIGVGAASVDFQVGTGRMP
LQGTTVQAPEKPTQFTDTQVKELAAYVASLAPGPAIPDGQYLDGKGDPANGAELFRINCA
MCHNVAAAGGALTEGKFAPSLEGVAPVHIYEAMVTGPQNMPVFNDTNISPEDKRDIITSL
QYIEENSTVGGANLGGLGPVSEGLFMWIFGLGGIVALTVWLTARSN
